### ISSUE TITLE
Adguard doesn't start when restarting docker service

### ISSUE THREAD

**Issue by gdiciancia** [hassio-addons/addon-adguard-home#10]
# Problem/Motivation

I am using the Router option, meaning Adguard is the DNS for the whole network.
Adguard doesn't start when restarting the docker service (and perhaps the same would happen when restarting the host server).

## Expected behavior

Adguard should start in order to resolve DNS requests for the whole network

## Actual behavior

The hassio-supervisor doesn't start because there is no internet (since Adguard is not started).
And Adguard is not starting because it cannot connect to the hassio API for authentication.

## Steps to reproduce

Install/run Adguard
Setup Adguard as DNS server in your router WAN setup
Restart the docker service or host server
Hassio supervisor will not start since the router cannot resolve DNS requests
Adguard will not start because hassio is not started

## Proposed changes

Add the ability to start Adguard without API connection (perhaps via command line), or perhaps removing the use of the hassio authentication, due to the nature of this Add-on.

A less than ideal workaround is to change the router settings temporarily to a non-local DNS, but this causes all network devices (router, 2 switches, several access points) to be re-configured, which takes time to setup and to revert back to the desired state. This allows to start the supervisor and then Adguard, finally the network devices needs to be setup to use Adguard again.

**Comment by tjorim** [comment]
This isn't an actual issue. A client can't/shouldn't become a client of itself anyway. Hence step 1 of the installation instructions: https://github.com/hassio-addons/addon-adguard-home#installation

**Comment by gdiciancia** [comment]
I have 1 server for multiple things, therefore I'm not sure I will be able to do that. However, I remove it as an issue. Thanks. Perhaps I'll put a feature request to be able to config/choose to use the Auth API or not.
