### ISSUE TITLE
DNS request for DNS rewrite entries not served when no upstream DNS servers are available

### ISSUE THREAD

**Issue by matthijsberg** [hassio-addons/addon-adguard-home#101]
# Problem/Motivation

> My internet connection failed recently. After that I could not reach my HA instance and my Ubiquiti network disengaged. Both are relying on DNS. HA uses TLS and is accessed on hostname to not have errors. UI devices use DNS to resolve the container on my server that hosts the UI server. It looks like AdGuard stops serving DNS responses when the upstream servers cannot be reached (it can't do that), but also stops for DNS rewrites.

## Expected behavior

> I expect the AdGuard to still serve DNS rewrites when no upstream server is available so that my local DNS resolving continues to operate and HA / UI keep working. I cannot find any config setting for this. Not sure if this can be changed in the add-on or is a AdGuard config setting / change request.

## Actual behavior

> DNS stopped, also for local DNS resolve / services

## Steps to reproduce

> Pull the connection to the internet.

## Proposed changes

> It would be great if there is a config option to have AdGuard still serve DNS request for rewrite entries when there is no upstream DNS resolver available.

**Comment by frenck** [comment]
This is an add-on, and add-on wrap existing applications. In this case AdGuard Home.

If you want new features into AdGuard Home itself, you should report them to the AdGuard team.

**Comment by matthijsberg** [comment]
Thank you Frenck, you're absolutely right. for future reference; https://github.com/AdguardTeam/AdGuardHome/issues/2596
