### ISSUE TITLE
unable to spawn - Exec format error

### ISSUE THREAD

**Issue by allenlarkins** [hassio-addons/addon-adguard-home#108]
# Problem/Motivation

I used to have Adguard running but something went wrong.
Getting an error when trying to start up the plug-in. I have uninstalled, rebooted, installed, rebooted and then configured, rebooted before trying again.

### Config file
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
log_level: debug

### Log file (Adguard)
if: fatal: unable to spawn /bin/s6-overlay-preinit: Exec format error

Core
Version
core-2021.1.5

Supervisor
Version
supervisor-2021.01.7
Cannot see anything in the Homeassistant log file

**Comment by frenck** [comment]
Could you please provide the output of:

`ha info`

**Comment by allenlarkins** [comment]
Running on a PI4 with SSD

pi@rasspi4:~ $ sudo ha info
arch: armv7
channel: stable
docker: 19.03.12
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.1.5
hostname: rasspi4
logging: info
machine: raspberrypi4
operating_system: Raspbian GNU/Linux 10 (buster)
supervisor: 2021.01.7
supported: false
supported_arch:
- armv7
- armhf
timezone: Pacific/Auckland

**Comment by frenck** [comment]
Meh. You system is not a supported system by the project.

`Raspbian GNU/Linux 10 (buster)`

Rapsbian is not a valid OS to run Home Assistant Supervised on.

That said, it seems like your system is pulling the wrong image, that doesn't match the capabilities of your CPU. (Which is weird, since the Pi should be able to run both armv7 & armhf).

**Comment by allenlarkins** [comment]
I suppose I can try to rebuild the system as it used to work but I had a system crash which I tried to recover from. Thanks for the lead though, something for me to at least look into
