### ISSUE TITLE
Block youtube ads

### ISSUE THREAD

**Issue by Gaspard-Bourgeois** [hassio-addons/addon-adguard-home#114]
## Proposed changes

Are they any way to block youtube ads from adguard ? What would be the change necessary to do so ?

I read some stuff about it one this [link](https://www.reddit.com/r/Adguard/comments/c4950y/adguard_home_and_youtube/) but they don't develop the reasons.

If you know more about it I'm interested.

**Comment by sinclairpaul** [comment]
No, DNS based ad blockers cannot block Youtube ads, Google have to get their revenue somehow..... 

You will find more information at the Adguard site itself.
