### ISSUE TITLE
Latest Version of AdGuard refuses to start

### ISSUE THREAD

**Issue by awshirley** [hassio-addons/addon-adguard-home#133]
# Problem/Motivation

> AdGuard refuses to start

## Expected behavior

> AdGuard to start

## Actual behavior

> AdGuard fails on start up

## Steps to reproduce

> Start AdGuard and review logs.
Logs show:
[08:58:18] INFO: Starting AdGuard Home server...
2021/03/12 08:58:18 [info] AdGuard Home, version v0.105.2, channel release, arch linux amd64
2021/03/12 08:58:18 [error] Couldn't parse config file: invalid IP address: 192.168.1.46/24
192.168.1.34
2021/03/12 08:58:18 [error] Failed to parse configuration, exiting

## Proposed changes
Please fix AdGuard so it can find the current valid IP.  I'm using a fix IP address, so there isn't any reason it shouldn't find it.

**Comment by sinclairpaul** [comment]
Can you post the output of ```ha network info``` which can be run from the SSH addon

**Comment by frenck** [comment]
seems like you have multiple IP-addresses bound to the same interface?

**Comment by ElastixHA** [comment]
I have the same issue. How to fix this?

**Comment by frenck** [comment]
@ElastixHA Maybe you could provide more information in that case? As requested by sinclairpaul in the first response in this issue?

**Comment by ElastixHA** [comment]
@frenck Let me start by saying that I absolutely love your ADDONS. And I am very new at Raspberry Pi and Home assistant.

I got it working for a week before update 4.0.0 and then it stopped.
The log is posted below. IP 192.168.2.70 is my home assistant and 192.168.2.201 is my PI. I also wouldn't know if it is possible to change the IP's other than in Homeassistant. 

P.s. When my adguard broke we didn't have internet in the house. Is there a way to have a regular DNS as backup? Or will the ads go through the secondary DNS when I use Googles DNS as secondary DNS?

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[14:23:48] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:23:49] INFO: Starting AdGuard Home server...
2021/03/16 14:23:49 [info] AdGuard Home, version v0.105.2, channel release, arch linux arm v7
2021/03/16 14:23:49 [error] Couldn't parse config file: invalid IP address: 192.168.2.70/24
192.168.2.201
2021/03/16 14:23:49 [error] Failed to parse configuration, exiting
[14:23:50] INFO: Starting AdGuard Home server...
2021/03/16 14:23:50 [info] AdGuard Home, version v0.105.2, channel release, arch linux arm v7
2021/03/16 14:23:50 [error] Couldn't parse config file: invalid IP address: 192.168.2.70/24
192.168.2.201
2021/03/16 14:23:50 [error] Failed to parse configuration, exiting
[14:23:51] INFO: Starting AdGuard Home server...
2021/03/16 14:23:51 [info] AdGuard Home, version v0.105.2, channel release, arch linux arm v7
2021/03/16 14:23:51 [error] Couldn't parse config file: invalid IP address: 192.168.2.70/24
192.168.2.201
2021/03/16 14:23:51 [error] Failed to parse configuration, exiting
[14:23:52] INFO: Starting AdGuard Home server...
2021/03/16 14:23:52 [info] AdGuard Home, version v0.105.2, channel release, arch linux arm v7
2021/03/16 14:23:52 [error] Couldn't parse config file: invalid IP address: 192.168.2.70/24
192.168.2.201
2021/03/16 14:23:52 [error] Failed to parse configuration, exiting`

**Comment by frenck** [comment]
@ElastixHA the question was:

> Can you post the output of ha network info which can be run from the SSH addon

See first comment. Thanks.

**Comment by ElastixHA** [comment]
This is the output of my ssh

```
Last login: Thu Feb 25 21:17:43 2021 from 192.168.2.68
~ $ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: null
interfaces:
- connected: true
  enabled: true
  interface: eth0
  ipv4:
    address:
    - 192.168.2.70/24
    - 192.168.2.201/24
    gateway: 192.168.2.254
    method: static
    nameservers:
    - 1.1.1.1
  ipv6:
    address:
    - fe80::7210:9fdf:b3ad:157/64
    gateway: null
    method: auto
    nameservers: []
  primary: true
  type: ethernet
  vlan: null
  wifi: null
- connected: false
  enabled: false
  interface: wlan0
  ipv4:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
  primary: false
  type: wireless
  vlan: null
  wifi: null
supervisor_internet: true
```

**Comment by frenck** [comment]
Thanks! That explains it!

Could you be so kind to drop a screenshot from:

Supervisor -> System tab -> Host card click "CHANGE" next to the IP Address field. Next, expand the IPv4 accordion, like this:

![image](https://user-images.githubusercontent.com/195327/111536926-252eb300-876b-11eb-8a89-b9f659c8edd3.png)

**Comment by ElastixHA** [comment]
![Screenshot_2021-03-17-22-04-03-354_io homeassistant companion android](https://user-images.githubusercontent.com/78592366/111538340-d97d0900-876c-11eb-86c4-44578a6ddd16.jpg)

This is mine

**Comment by frenck** [comment]
Awesome, thanks! 👍

**Comment by ElastixHA** [comment]
Deleted the second IP. Now it works again. Thank you so much.

**Comment by awshirley** [comment]
Sorry I haven't been able to get back to this sooner.  I've been traveling without my PC.

When I do ip a, this is what I get:

2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:2b:9e:58 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.46/24 brd 192.168.1.255 scope global dynamic noprefixroute enp1s0
       valid_lft 914233sec preferred_lft 914233sec
    inet 192.168.1.34/24 brd 192.168.1.255 scope global secondary dynamic noprefixroute enp1s0
       valid_lft 914230sec preferred_lft 914230sec

I have HA running in a vm with a bridged network.  I'm using DHCP with the IP's coming from a windows server.  I have reservations on the windows server using the mac address of the network interface.  I have no idea how a second IP is getting assigned.  Now I have to figure out how to delete it and prevent it from coming back.  Any suggestions??

**Comment by awshirley** [comment]
Not sure how a new line was added to the network config file, but I removed it, rebooted and now it works.

Thanks for the comments on here.  It pointed me to my solution.
