### ISSUE TITLE
IPv6 support missing since v4.0.0

### ISSUE THREAD

**Issue by elcajon** [hassio-addons/addon-adguard-home#134]
# Problem/Motivation

Because of binding DNS server to IPv4 interface, the IPv6 interface is missing.
For my network setup, which consists of IPv4 and IPv6 addresses , ad blocking is broken ever since. 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/52052494/111032034-c552a800-840a-11eb-9d36-271df11e8fcd.png">

## Expected behavior

Binding of DNS services to IPv4 and IPv6 relevant interfaces.

## Actual behavior

Only blocking for IPv4 interface is enabled.

## Steps to reproduce

Clean installation of add-on version 4.0.0

## Proposed changes

Since there seems to be no option to add more than one standard interface to bind to (see [issue](https://github.com/AdguardTeam/AdGuardHome/issues/1401)), I would appreciate if you could undo PR #126 changes.

**Comment by frenck** [comment]
I will not undo it, as it fixes other issues.

**Comment by madmurl0c** [comment]
Could you leave this issue open so we can keep track of it? Unfortunately I'll have to stay on 3.0.0 until IPv6 works again. Do you have any workaround for now? :)

**Comment by frenck** [comment]
The issue is tracked upstream, there is nothing to do on this end. Keeping the issue open merely pollutes my work environment.
