### ISSUE TITLE
Interface default does not exist error

### ISSUE THREAD

**Issue by AlecRust** [hassio-addons/addon-adguard-home#135]
# Problem/Motivation

After upgrading to addon version 4.0.0 I have the following in my logs:

```sh
[cont-init.d] adguard.sh: executing... 
[10:18:23] ERROR: Got unexpected response from the API: Interface default does not exist
[cont-init.d] adguard.sh: exited 0.
```

And on the "Setup Guide" section of AdGuard Home it shows `<nil>` where there should be an IP address:

![screenshot](https://i.imgur.com/XvANgBX.png)

I notice the [release notes](https://github.com/hassio-addons/addon-adguard-home/releases/tag/v4.0.0) mention:

> AdGuard Home will now bind solely to the main network interface. The Supervisor provides this network information, thus having a proper, Supervisor supported and managed, network configuration is now required.

I have `NetworkManager` set up via the supervised install script on Ubuntu, but not sure what other network configuration is required?

## Expected behavior

- No such error in addon logs
- Visible IP address in "Setup Guide"

## Actual behavior

- Error in addon logs
- No visible IP address in "Setup Guide"

**Comment by frenck** [comment]
Please provide the output of the following commands:

- `ha info`
- `ha resolution info`

**Comment by AlecRust** [comment]
`ha info`
```
arch: amd64
channel: stable
docker: 20.10.5
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.3.4
hostname: alecs-nuc
logging: info
machine: qemux86-64
operating_system: Ubuntu 20.04.2 LTS
state: running
supervisor: 2021.03.6
supported: false
supported_arch:
- amd64
- i386
timezone: Europe/London
```

`ha resolution info`
```
checks:
- enabled: true
  slug: addon_pwned
- enabled: true
  slug: core_security
- enabled: true
  slug: free_space
issues: []
suggestions: []
unhealthy: []
unsupported:
- os
```

**Comment by AlecRust** [comment]
I have resolved this. Somehow the "DNS Servers" field had been cleared at Supervisor > System > Network Settings.

Setting this to `1.1.1.1, 1.0.0.1` (which I assume is the correct value instead of AGHs) and rebooting host fixes the notice in the logs and the `<nil>` on the "Setup guide" page.
