### ISSUE TITLE
Default Interface binding breaks IPv6 support for me

### ISSUE THREAD

**Issue by zmbcgn** [hassio-addons/addon-adguard-home#136]
# Problem/Motivation

With update to 4.0.0 there comes the change that adguard will soley listen to the default interface ip address. Obviously this only reflects IPv4 adresses. I am using IPv6 ULA for my LAN. I am dual stacked on my clients, so this isn't a big issue for me. But currently all my ipv6 dns request will time out.

## Expected behavior

Listen on ipv4 and ipv6 addresses of the default interface

## Actual behavior

listening solely on ipv4

## Steps to reproduce

configure ipv6 on default interface

## Proposed changes

add ipv6 address to the listening interfaces.

**Comment by frenck** [comment]
Unfortunately, this is an upstream issue: <https://github.com/AdguardTeam/AdGuardHome/issues/1401>
