### ISSUE TITLE
Adguard no longer listens on ipv6 address.

### ISSUE THREAD

**Issue by jancolle** [hassio-addons/addon-adguard-home#138]
I have a Homeassistant installation that runs dualstack IPv4 and IPv6, but after the latest upgrade, Adguard only listens on IPv4.

**Comment by frenck** [comment]
This is not an add-on limitation.

https://github.com/AdguardTeam/AdGuardHome/issues/1401

**Comment by debsahu** [comment]
@frenck The upstream [issue](https://github.com/AdguardTeam/AdGuardHome/issues/1401) is resolved. Wiki has been updated to say one can bind interfaces in [v0.160.0](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration). Could we bump the AdGaurd version to v0.160.0 or higher?

**Comment by frenck** [comment]
@debsahu There is no 1.6.0 release as of yet, see: <https://github.com/AdguardTeam/AdGuardHome/releases>
