### ISSUE TITLE
Since 4.0.0, No support for multiple IP's on eth0 interface

### ISSUE THREAD

**Issue by basdejong95** [hassio-addons/addon-adguard-home#140]
# Problem/Motivation

Hi, before the Adguard Home 4.0.0 update, i was using 2 ip addresses for home assistant/adguard on the eth0 interface. For example, 192.168.1.10/24 and 192.168.1.11/24. 
However, after updating adguard failed to start saying it had an invalid IP configuration. 

## Expected behavior

Normal startup like 3.x.x and Adguard being available on multiple IP addresses.

## Actual behavior

Unable to start the plugin, error saying invalid IP configuration

## Steps to reproduce

Have adguard 3.x.x and 2 ip adresses on interface eth0. Update adguard home to 4.0.0.

## Proposed changes

Please support multiple ip addresses via comma separated values.

Extra info:
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7l
arch | armv7l
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4806
Installed Version | 1.11.3
Stage | running
Available Repositories | 838
Installed Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 29, 2021, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 116.5 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.0.0), File editor (5.2.0), Home Assistant Google Drive Backup (0.103.1), MariaDB (2.2.1), Portainer (1.4.0), SSH & Web Terminal (8.1.0), Samba share (9.3.1), deCONZ (6.8.0), phpMyAdmin (0.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 8
views | 8
mode | storage

</details>

**Comment by frenck** [comment]
Correct, AdGuard does not support binding multiple interfaces specifically. Multiple issues already closed, this is an upstream issue.

**Comment by basdejong95** [comment]
Hi @frenck , i am not referring to multiple **interfaces**, but multiple ip's on the same interface. 

so ETH0 has 192.168.0.10 **and** 192.168.0.11 as an IP address. 

This solves the issue of having only one DNS ip address for my internal network, which makes ad blocking in Android Phones impossible, because google "injects 8.8.8.8" as a default DNS ip address for the secondary. 

As a workaround, is it possible to run the Adguard docker container twice with both different ip addresses somehow?

**Comment by frenck** [comment]
See my answer above.

**Comment by alexdlm** [comment]
@frenck Now that AdGuard does support multiple bind interfaces can this be reopened for support after the next version bump?

https://github.com/AdguardTeam/AdGuardHome/issues/1401
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file `bind_hosts (since v0.106.0)`

**Comment by Duckle29** [comment]
@alexdlm Reading that doc it seems it still doesn't support multiple IPs on the same interface. Only multiple IPs on multiple interfaces
