### ISSUE TITLE
AdGuard changes the config file wrong on startup

### ISSUE THREAD

**Issue by LeoLTM** [hassio-addons/addon-adguard-home#141]
# Problem/Motivation

After the last update, I wasn't able to connect to the web interface of AdGuard. The log says that there are two IP adresses for the DNS to bind to.

## Expected behavior

AdGuard should bind the DNS to 192.168.2.200/24

## Actual behavior

AdGuard overwrites my config file and enters 2 IP adresses for the DNS to bind to. That causes the startup process to fail.

## Steps to reproduce

Register 2 IP adresses on the eth0 network adaptor; update AdGuard; change the config file so that only one IP adress will be used for the DNS; restart AdGuard; look into the config file

## Proposed changes

AdGuard should somehow be blocked from changing the file everytime I start the addon

**Comment by frenck** [comment]
AdGuard itself does not support binding to multiple.
This is an upstream issue, not something the add-on can fix or change.

**Comment by dorinvlas** [comment]
@frenck But how about binding to multiple interfaces NOT ip's? Many thanks for your support.

`General settings
bind_host (before v0.106.0) - IP address on which to serve DNS queries.

bind_hosts (after v0.106.0) - IP addresses on which to serve DNS queries. For each network interface there can only be one IP address of each IP version. Examples of valid configurations:

# Different network interfaces.
'dns':
    'bind_hosts':
    - '127.0.0.1'
    - '192.168.1.1'
# Same network interface, different IP versions.
'dns':
    'bind_hosts':
    - '127.0.0.1'
    - '::1'
If you want your server to accept requests on all interfaces and using both IP versions, for example if you run a public server, put one item with the unspecified IP of any version:

'dns':
    'bind_hosts':
    - '0.0.0.0'`

**Comment by frenck** [comment]
That isn't a released feature of AdGuard Home yet... Thus that is a useless suggestion.
