### ISSUE TITLE
Since 4.0, DNS stops working after a few hours. Plugin restart fixes it

### ISSUE THREAD

**Issue by Duckle29** [hassio-addons/addon-adguard-home#146]
# Problem/Motivation

I've been using AdGuard Home for a while as my DHCP and DNS server, and it's been working great. After updating to 4.0, I've been having issues with my desktop "loosing internet" because all of a sudden it can't resolve DNS queries. Looking on the queries page of the plugin I don't see any queries received. Checking the logs of the plugin doesn't seem to give any clues either.

A restart of the plugin resolves the issue pretty much immediately and sites that had failed to load automatically come alive

## Expected behavior

Normal websites work as DNS works

## Actual behavior

Websites fail to load because DNS queries suddenly aren't being answered

## Steps to reproduce

Set up HA with AdGuard Home plugin. Have it handle DNS and DHCP. Use a desktop running W10 pro 2004 build 19041.867  

## Hardware
RPi4 4GB
Boot from USB3 (SSD enclosure)

How would I go about testing this? With a bit of guidance I could probably do some wireshark captures

**Comment by Duckle29** [comment]
So it happened again. I've had Wireshark running a capture with the DNS filter, and it seems after a while the DNS server starts returning "Server failure" respones

![image](https://user-images.githubusercontent.com/2756925/114303943-ddcce580-9ad0-11eb-94f7-ad618bfe7a93.png)

Here's the first failure

![image](https://user-images.githubusercontent.com/2756925/114303964-f3420f80-9ad0-11eb-9c13-a2801e4432da.png)


Seems to be the same response for other domains too.

The stuff about authoritative or not doesn't seem to be an issue. Previous successful queries have that too. Only difference being the Reply code being 2

After a good while of this the DNS server just stops responding

**Comment by Duckle29** [comment]
It doesn't seem to be related to time directly, as it works fine in the morning. To me that suggests it has something to do with X amount of queries?

**Comment by pattyland** [comment]
I'm having the exact same problems. I even wrote an automation the checks AGH every minute and restart the add-on if necessary... I still didn't find out of is this a problem of this add-on or AGH in general. I would assure later one

**Comment by PizzaPino** [comment]
For me it works at the beginning and then suddenly out of nowhere just stops working again.

**Comment by Duckle29** [comment]
Personally it means adguard is useless to me, so I have put up a spare rpi with pi.hole for now :/ I still have the adguard setup for testing if devs need additional info

**Comment by terasankka** [comment]
Adguard died today. It is running on HomeAssistant RasberryPi server - restart does not help. Re-install does not help. Here is the LOG: 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment]
@terasankka This is not related to this issue, thus marked your answer off-topic. Your report is a duplicate of #175

**Comment by pattyland** [comment]
@Duckle29 What Upstream servers are you using? I was using DNS-over-TLS and was adviced from a agh dev to try DNS-over-HTTPS. Since I switched to `https://cloudflare-dns.com/dns-query` and my stability is much better than before, since weeks without a downtime

**Comment by ilarrain** [comment]
I'm having exactly the same issue. I was out of home when it happened. A plugin restart fixed it immediately.
![Screenshot_20210520-184221_Home Assistant](https://user-images.githubusercontent.com/775978/119057877-4befac80-b99b-11eb-81ae-ab21311ea7ae.jpg)

**Comment by ilarrain** [comment]
I don't have logs, but the add-on page and the AdGuard DHCP server were forking fine, but the DNS server was not, and the request log was empty.
![Screenshot_20210520-185009_Home Assistant](https://user-images.githubusercontent.com/775978/119058607-b6edb300-b99c-11eb-874b-7f01190d01b3.jpg)

**Comment by Duckle29** [comment]
@pattyland https://dns10.quad9.net/dns-query with 1.1.1.1:53 as bootstrap. I'm using DNSSEC not sure if that plays in to this
