### ISSUE TITLE
Support for IPv6 address

### ISSUE THREAD

**Issue by rmandjes** [hassio-addons/addon-adguard-home#153]
# Problem/Motivation

>I'm missing the IPv6 address for adguard home instance

## Expected behavior

>I was expecting that the DNS servers was also listing to the IPv6 address from HA

## Actual behavior

> No IPv6 shown in the interface.

## Steps to reproduce

> Go to the last tab (Installation steps). There you see the IP addresses from Adguard.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This was limited in the current version, because of an upstream limitation. AdGuard released a new version yesterday, so we can now start working on bringing back additional interfaces (including the IPv6 ones).
