### ISSUE TITLE
Feature request: DHCP server new client ha sensor

### ISSUE THREAD

**Issue by tyjtyj** [hassio-addons/addon-adguard-home#166]
# Problem/Motivation
When adguard assign new ip address not listed in static lease. Update dhcp lease sensor. 
This can be use to send notification "New device join the network. eg. ip:xxx host:xxx: mac:xxx.
> (Why the issue was filed)

## Expected behavior
home assistant sensor. dhcp lease with ip address and mac address and hostname in attribute
> (What you expected to happen)

## Actual behavior
not implemented
> (What actually happened)

## Steps to reproduce
n/a
> (How can someone else make/see it happen)

## Proposed changes
n/a
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is an add-on not the Home Assistant integration.
