### ISSUE TITLE
Error on start adguard home

### ISSUE THREAD

**Issue by brunolinsalves** [hassio-addons/addon-adguard-home#175]
# Problem/Motivation

After install the adguard home addon for home assistant, it fail to start with this log messages: 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Expected behavior

I expect the addon to start...

**Comment by MiguelAngelLV** [comment]
For me, error binding port

```
[06:25:24] INFO: Starting AdGuard Home server...
2021/05/20 06:25:24.493643 [info] AdGuard Home, version v0.106.3
2021/05/20 06:25:24.499825 [info] dhcp: loaded leases v4:87  v6:0  total-read:87 from DB
2021/05/20 06:25:24.533629 [info] Initializing auth module: /data/adguard/data/sessions.db
2021/05/20 06:25:24.534539 [info] auth: initialized.  users:0  sessions:0
2021/05/20 06:25:24.534634 [info] Initialize web module
2021/05/20 06:25:24.597209 [info] dhcpv4: listening
[dhcpv4] 2021/05/20 06:25:24 Server listening on 0.0.0.0:67
[dhcpv4] 2021/05/20 06:25:24 Ready to handle requests
2021/05/20 06:25:24.598722 [info] Go to http://127.0.0.1:45158
2021/05/20 06:25:25.062482 [info] Starting the DNS proxy server
2021/05/20 06:25:25.062519 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 06:25:25.062537 [info] The server is configured to refuse ANY requests
2021/05/20 06:25:25.062554 [info] DNS cache is enabled
2021/05/20 06:25:25.062574 [info] MaxGoroutines is set to 50
2021/05/20 06:25:25.062601 [info] Creating the UDP server socket
2021/05/20 06:25:25.062778 [info] Listening to udp://192.168.1.2:53
2021/05/20 06:25:25.062800 [info] Creating the UDP server socket
2021/05/20 06:25:25.234258 [fatal] couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp [fe80::73a2:9e9b:11ec:b5a4]:53: bind: invalid argument
```

**Comment by shirou93** [comment]
when i updated to  4.1.2  addon stop working.

`2021/05/20 08:13:46.459029 [fatal] couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp [fe80::1cbf:e7d8:37ac:e5fb]:53: bind: invalid argument`

**Comment by rlewis187** [comment]
I am also seeing this since I woke up this morning:
```
2021/05/20 07:23:41.360223 [info] Creating the UDP server socket
2021/05/20 07:23:41.366802 [fatal] couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp [fe80::85f7:9576:5bc:eecf]:53: bind: invalid argument

```
Current version: 4.1.2, I think it updated in the night/just before I woke up

**Comment by Nenodema** [comment]
Same error here!

```
2021/05/20 08:24:38.998993 [info] AdGuard Home, version v0.106.3
2021/05/20 08:24:39.003965 [info] Initializing auth module: /data/adguard/data/sessions.db
2021/05/20 08:24:39.004046 [info] auth: initialized.  users:0  sessions:0
2021/05/20 08:24:39.004080 [info] Initialize web module
2021/05/20 08:24:39.017941 [info] Go to http://127.0.0.1:45158
2021/05/20 08:24:39.249445 [info] Starting the DNS proxy server
2021/05/20 08:24:39.249513 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 08:24:39.249534 [info] The server is configured to refuse ANY requests
2021/05/20 08:24:39.249551 [info] DNS cache is enabled
2021/05/20 08:24:39.249564 [info] MaxGoroutines is set to 50
2021/05/20 08:24:39.249593 [info] Creating the UDP server socket
2021/05/20 08:24:39.249680 [info] Listening to udp://x.x.x.x:53
2021/05/20 08:24:39.249724 [info] Creating the UDP server socket
2021/05/20 08:24:39.260188 [fatal] couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp [fe80::5ee4:db55:a005:dedb]:53: bind: invalid argument
```

**Comment by frenck** [comment]
@shirou93 @rlewis187 @Nenodema Your logs are not the same as the initial log reported in this issue. Your issue is tracked here #174. I've marked your comments as offtopic to avoid confusion.

**Comment by pboos** [comment]
I just installed this addon this morning for the first time and got the same error mentioned in the first post:
```
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
```

**Comment by pboos** [comment]
Seems like this commit is what introduced the problem:
https://github.com/hassio-addons/addon-adguard-home/commit/6d7a84906e273be3cb85a78f1f0f3ea8d9ce52ff

**Comment by frenck** [comment]
I don't see how this variable can be unbound 😟 

```bash
# Bump schema version in case this is an upgrade path
schema_version=$(yq read "${CONFIG}" schema_version)
if bashio::var.has_value "${schema_version}"; then
    if [[ "${schema_version}" -eq 7 ]]; then           # <--- line 27, but it is already used in 26...
        # Clean up old interface bind formats
```

**Comment by bartsmykla** [comment]
same here
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by bmrp** [comment]
Seems like I'm having the same errors, pasting them below anyway in case it can be of any assistance:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (amd64 / qemux86-64)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Cyr-ius** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[09:11:55] DEBUG: Requested API resource: http://supervisor/network/interface/default/info
[09:11:55] DEBUG: Request method: GET
[09:11:55] DEBUG: Request data: {}
[09:11:55] DEBUG: API HTTP Response code: 200
[09:11:55] DEBUG: API Response: {"result": "ok", "data": {"interface": "eth0", "type": "ethernet", "enabled": true, "connected": true, "primary": true, "ipv4": {"method": "static", "address": ["192.168.1.2/24"], "nameservers": ["192.168.1.2", "1.1.1.1"], "gateway": "192.168.1.1"}, "ipv6": {"method": "auto", "address": ["fe80::b53d:4022:465f:94e0/64"], "nameservers": [], "gateway": null}, "wifi": null, "vlan": null}}
[09:11:56] INFO: Adding 192.168.1.2
[09:11:56] INFO: Adding fe80::b53d:4022:465f:94e0
[09:11:56] INFO: Adding 172.30.32.1
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[09:11:57] DEBUG: Requested API resource: http://supervisor/discovery
[09:11:57] DEBUG: Request method: POST
[09:11:57] DEBUG: Request data: {"service":"adguard","config":{"host":"127.0.0.1","port":45158}}
[09:11:57] DEBUG: API HTTP Response code: 200
[09:11:57] DEBUG: API Response: {"result": "ok", "data": {"uuid": "83e8a0190dcf4558a88aec52b3899cf4"}}
[09:11:57] DEBUG: Filtering response using: .uuid
[09:11:57] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[09:11:58] DEBUG: Requested API resource: http://supervisor/addons/self/info
[09:11:58] DEBUG: Request method: GET

**Comment by basschipper** [comment]
After auto-update I'm seeing the same behaviour as #174. After removing and reinstalling the addon I'm also getting this unbound var error. Maybe they are related?

**Comment by Cyr-ius** [comment]
iIf I remove the IPv6 address from the /data/adguard/adguardhome.yaml file and that I kill the process in the container it works

**Comment by Cyr-ius** [comment]
![Capture-20210520090844-374x159](https://user-images.githubusercontent.com/1258123/118935613-01930f00-b94c-11eb-8f77-de69608a1e84.png)

**Comment by Cyr-ius** [comment]
> After auto-update I'm seeing the same behaviour as #174. After removing and reinstalling the addon I'm also getting this unbound var error. Maybe they are related?

If I uninstall and reinstall actually I have the same mistake 



[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.

**Comment by frenck** [comment]
v4.1.3 is available, which should address this issue.

Sorry for the inconvenience this might have caused 🙏

**Comment by Nenodema** [comment]
@frenck 

Thanks for the quick effort!
