### ISSUE TITLE
AdGuard doesn't start: [error] Couldn't parse config file: invalid IP address

### ISSUE THREAD

**Issue by trunneml** [hassio-addons/addon-adguard-home#177]
# Problem/Motivation

Since today AdGuard Home doesn't start.

## Expected behavior

AdGuard starts without an error

## Actual behavior

AdGuard Home doesn't start. In the log is an error about parsing the IPv6 Address.

```
[09:19:42] INFO: Starting AdGuard Home server...
2021/05/20 09:19:42.801825 [info] AdGuard Home, version v0.106.3
2021/05/20 09:19:42.807884 [error] Couldn't parse config file: invalid IP address: 2a02:8351:81c1:c412:990a:cfc7:c2f7:2d3c/64
fd00::64fc:512a:ad0a:b075
2021/05/20 09:19:42.807944 [error] parsing configuration file: invalid IP address: 2a02:8351:81c1:c412:990a:cfc7:c2f7:2d3c/64
fd00::64fc:512a:ad0a:b075

## Steps to reproduce

In my case just starting AdGuard Home is enough.

**Comment by hulkhaugen** [comment]
I got the same. Sure you already got what you need, but in case it's helpful, here is what keeps repeating in my logs:
```[09:59:19] INFO: Starting AdGuard Home server...
2021/05/20 09:59:19.311504 [info] AdGuard Home, version v0.106.3
2021/05/20 09:59:19.328021 [info] Initializing auth module: /data/adguard/data/sessions.db
2021/05/20 09:59:19.328181 [info] auth: initialized.  users:0  sessions:0
2021/05/20 09:59:19.328242 [info] Initialize web module
2021/05/20 09:59:19.361171 [info] Go to http://127.0.0.1:45158
2021/05/20 09:59:19.681744 [info] Starting the DNS proxy server
2021/05/20 09:59:19.681788 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 09:59:19.681794 [info] The server is configured to refuse ANY requests
2021/05/20 09:59:19.681799 [info] DNS cache is enabled
2021/05/20 09:59:19.681811 [info] Creating the UDP server socket
2021/05/20 09:59:19.681933 [info] Listening to udp://192.168.1.3:53
2021/05/20 09:59:19.681943 [info] Creating the UDP server socket
2021/05/20 09:59:19.686582 [fatal] couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp [fe80::fb3:6ab6:58be:3a4e]:53: bind: invalid argument```

**Comment by frenck** [comment]
@hulkhaugen your issue is not the same, you are looking for #174

**Comment by tuxflo** [comment]
I'm facing the same problem: digging through the logs with log_level set to "trace" I found out that this change https://github.com/hassio-addons/addon-adguard-home/commit/6d7a84906e273be3cb85a78f1f0f3ea8d9ce52ff#diff-93dabd0dabaa0dd45cf3e5131d0b87b34d0d0f61d3dbb642c299cfc14e7703e7 is causing issues. The log tells me that there is an unbound variable, maybe its the "schema_version" that is missing? I already tried to set this as a config value in the yaml but it didn't help.

**Comment by frenck** [comment]
@tuxflo Fix is linked just above your comment...

**Comment by tuxflo** [comment]
Ah sorry, I my browser didn't refresh the page while I was looking for the diff so I didn't see that you already commented. Thanks for the super fast response 🙏

**Comment by frenck** [comment]
v4.1.3 is available, which should address this issue.

Sorry for the inconvenience this might have caused 🙏
