### ISSUE TITLE
Error occurred while communicating with AdGuard Home

### ISSUE THREAD

**Issue by cjmjmartens** [hassio-addons/addon-adguard-home#178]
Hi, 

since the upgrade to the latest version (4.1.2), the CPU usage for this addon is much higher (around 25%). The system is running on raspberry4 with HA OS with latest versions of alle software components. I have checked the HA logbook:

Logger: homeassistant.config_entries
Source: config_entries.py:300 
First occurred: 9:25:01 (1 occurrences) 
Last logged: 9:25:01

Config entry 'AdGuard Home' for adguard integration not ready yet: Error occurred while communicating with AdGuard Home.; Retrying in background

Then I checked the log of the add-on:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
/var/run/s6/etc/cont-init.d/adguard.sh: line 27: null: unbound variable
[cont-init.d] adguard.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Reinstalling the addon and restarting the system did not solve the issue.

**Comment by frenck** [comment]
Duplicate
