### ISSUE TITLE
[fatal] unexpected type of dns.bind_host: <nil>

### ISSUE THREAD

**Issue by Lucus123** [hassio-addons/addon-adguard-home#188]
# Problem/Motivation

> installing and starting adguard 4.1.5 throws a fatal error

## Expected behavior

> startup of adguard

## Actual behavior

> fatal error starting adguard, addon doesnt load past the [fatal] unexpected type of dns.bind_host: <nil>

## Steps to reproduce

> uninstall current adguard version, reinstall version 4.1.5 thru community addon repo

**Comment by frenck** [comment]
Duplicate of #181
