### ISSUE TITLE
Migration from pihole to adguard stopped HassIO dns resolving

### ISSUE THREAD

**Issue by keneanung** [hassio-addons/addon-adguard-home#19]
# Problem/Motivation

Today I migrated from the working pihole HassIO addon to adguard. DNS lookups work fine in the overall network, however, home assistant (including addons) can't resolve DNS names anymore.

## Expected behavior

Home Assistant and addons are able to resolve DNS hostnames.

## Actual behavior

Home Assistant and addons are unable to resolve DNS hostnames, returning errors along the lines of `try again`. Manual calls to `dig google.com` via the SSH-Addon time out.

## Steps to reproduce

Not sure if reproducible or not. Moving back to pihole does not seem to restore DNS resolution.

## Proposed changes

None.

**Comment by keneanung** [comment]
In case it's not clear from the description above, I run the image from https://www.home-assistant.io/hassio/installation/ on an raspberry pi and currently have no direct host machine access.

**Comment by sinclairpaul** [comment]
Does your Pi have an external static DNS server set as per the release notes?

https://github.com/hassio-addons/addon-adguard-home

**Comment by keneanung** [comment]
The release notes are not clear enough for me. What does it mean? My DHCP DNS settings point to the Pi and other devices are clearly using adguard for resolving DNS and adguard is correctly relaying unblocked hostnames to the router, which in turn correctly relay them to my ISPs DNS.

It's only HassIO and the addons that have issues. And those should go through adguard as well, so I'm not sure if I'm missing that step and if so, how I'd set that external static DNS server.

**Comment by sinclairpaul** [comment]
It should not be a client of itself, I would recommend setting the DNS server on you Hassio instance to be your router or a suitable external DNS server.  Instructions can be found at https://github.com/home-assistant/hassos/blob/dev/Documentation/network.md

**Comment by keneanung** [comment]
Why should HassOS not go through adguard as well, which will then ask the upstream DNS? Using pi-hole worked fine before without configuring an exception.

Additionally, the issue seems to be that Hassio does not follow the DHCP settings, but instead, the docker containers are configured to use a docker internal container as DNS which exists but has port 53 closed.

**Comment by keneanung** [comment]
An update: I switched back to pihole and it "just worked". All docker containers on the pi were able to do name resolution again.

Since I'd like to switch to adguard if possible, I'd be interested in ideas and testing if needed.

**Comment by frenck** [comment]
This is documented. It should not become a client of itself, hence the big warning in the docs.
