### ISSUE TITLE
Changes to adguard.sh break dns bind host/IP

### ISSUE THREAD

**Issue by bertieuk** [hassio-addons/addon-adguard-home#191]
# Problem/Motivation

New method to populate dns: bind_host: in adguard.sh picks wrong / incorrect IP when multiple IPs are available

## Expected behavior

Binds to primary (or a selected interface)

## Actual behavior

Binds to hassio interface

## Steps to reproduce

Install on system with multiple interfaces

## Proposed changes

Make selectable or use interface selected on AdGuard > Settings > DHCP Settings

From Logs:

```
2021/05/20 12:26:16.421274 [info] Starting the DNS proxy server
2021/05/20 12:26:16.421305 [info] Cache TTL override is enabled. Min=30, Max=30
2021/05/20 12:26:16.421313 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 12:26:16.421320 [info] The server is configured to refuse ANY requests
2021/05/20 12:26:16.421328 [info] DNS cache is enabled
2021/05/20 12:26:16.421336 [info] MaxGoroutines is set to 300
2021/05/20 12:26:16.421348 [info] Creating the UDP server socket
2021/05/20 12:26:16.421464 [info] Listening to udp://172.30.32.1:53
2021/05/20 12:26:16.421476 [info] Creating a TCP server socket
2021/05/20 12:26:16.421538 [info] Listening to tcp://172.30.32.1:53
2021/05/20 12:26:16.421733 [info] Entering the tcp listener loop on 172.30.32.1:53
2021/05/20 12:26:16.421831 [info] Entering the UDP listener loop on 172.30.32.1:53`

172.30.32.1 is my hassio docker IP not main system IP
```

**Comment by frenck** [comment]
Please provide the output of `ha info`

**Comment by bertieuk** [comment]
# ha info
arch: amd64
channel: stable
docker: 20.10.6
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.5.5
hostname: ibm-x3550
logging: info
machine: qemux86-64
operating_system: Ubuntu 20.04.2 LTS
state: running
supervisor: 2021.04.3
supported: false
supported_arch:
- amd64
- i386
timezone: Europe/London

**Comment by frenck** [comment]
The network section is empty, thus the add-on has nothing to run with.

> Ubuntu 20.04.2 LTS

Is not a supported system by the Home Assistant project, which might be the root cause of your issues.

This is not an add-on issue.

**Comment by bertieuk** [comment]
The new code in adguard.sh under

 # Add interface to bind to, to AdGuard Home

is rewriting AdGuardHome.yaml and is what has broken my install

**Comment by frenck** [comment]
It always rewrote that.
Running an unsupported installation may break things unexpectedly. That is your issue, not ours.
If you want to run stuff more flawless, tested and stuff to be fixed if broken in weird fashions, run a supported installation method.

**Comment by Beduir** [comment]
Possibly related. After upgrade adguard is unavailable by system ip-address (192.168.1.149:53).

Before upgrade
```
[18:39:43] INFO: Starting NGinx...
2021/05/20 18:39:43 [info] Starting the DNS proxy server
2021/05/20 18:39:43 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 18:39:43 [info] The server is configured to refuse ANY requests
2021/05/20 18:39:43 [info] DNS cache is enabled
2021/05/20 18:39:43 [info] MaxGoroutines is set to 50
2021/05/20 18:39:43 [info] Creating the UDP server socket
2021/05/20 18:39:43 [info] Listening to udp://192.168.1.149:53
2021/05/20 18:39:43 [info] Creating a TCP server socket
2021/05/20 18:39:43 [info] Listening to tcp://192.168.1.149:53
2021/05/20 18:39:43 [info] Creating a TLS server socket
2021/05/20 18:39:43 [info] Listening to tls://192.168.1.149:853
2021/05/20 18:39:43 [info] Creating a QUIC listener
2021/05/20 18:39:43 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2021/05/20 18:39:43 [info] Listening to quic://192.168.1.149:784
2021/05/20 18:39:43 [info] Entering the tcp listener loop on 192.168.1.149:53
2021/05/20 18:39:43 [info] Entering the tls listener loop on 192.168.1.149:853
2021/05/20 18:39:43 [info] Entering the DNS-over-QUIC listener loop on 192.168.1.149:784
2021/05/20 18:39:43 [info] Entering the UDP listener loop on 192.168.1.149:53
2021/05/20 18:39:44 [error] os.Chtimes(): chtimes /data/adguard/data/filters/2.txt: no such file or directory
2021/05/20 18:39:44 [info] Failed to update filter https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt: data is HTML, not plain text

```

After upgrade
```
[18:58:27] INFO: Starting NGinx...
2021/05/20 18:58:27.916910 [info] Starting the DNS proxy server
2021/05/20 18:58:27.916956 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 18:58:27.916968 [info] The server is configured to refuse ANY requests
2021/05/20 18:58:27.916977 [info] DNS cache is enabled
2021/05/20 18:58:27.916990 [info] MaxGoroutines is set to 50
2021/05/20 18:58:27.917008 [info] Creating the UDP server socket
2021/05/20 18:58:27.917259 [info] Listening to udp://127.0.0.1:53
2021/05/20 18:58:27.917281 [info] Creating a TCP server socket
2021/05/20 18:58:27.917380 [info] Listening to tcp://127.0.0.1:53
2021/05/20 18:58:27.917430 [info] Creating a TLS server socket
2021/05/20 18:58:27.917555 [info] Listening to tls://127.0.0.1:853
2021/05/20 18:58:27.917570 [info] Creating a QUIC listener
2021/05/20 18:58:27.917974 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2021/05/20 18:58:27.918190 [info] Listening to quic://127.0.0.1:784
2021/05/20 18:58:27.922946 [info] Entering the DNS-over-QUIC listener loop on 127.0.0.1:784
2021/05/20 18:58:27.923028 [info] Entering the UDP listener loop on 127.0.0.1:53
2021/05/20 18:58:27.923231 [info] Entering the tcp listener loop on 127.0.0.1:53
2021/05/20 18:58:27.923254 [info] Entering the tls listener loop on 127.0.0.1:853
```

Also lost interface language setting.

```
 Add-on version: 4.1.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
```

**Comment by frenck** [comment]
@Beduir Not related at all. Restart the add-on once more to complete the upgrade and you are ready to go.

**Comment by Beduir** [comment]
@frenck Thank you, it works.

**Comment by bertieuk** [comment]
@frenck Clean install on new supported Debian 10 install, exactly the same. AdGuard binds to 172.30.32.1 (docker) IP

`# ha info
arch: amd64
channel: stable
docker: 20.10.6
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.5.5
hostname: debian
logging: info
machine: qemux86-64
operating_system: Debian GNU/Linux 10 (buster)
state: running
supervisor: 2021.04.3
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/London`

`# nslookup www.google.com 127.0.0.1
;; connection timed out; no servers could be reached

# nslookup www.google.com 172.30.32.1
Server:		172.30.32.1
Address:	172.30.32.1#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.16.228
Name:	www.google.com
Address: 2a00:1450:4009:821::2004`

**Comment by bertieuk** [comment]
Fixed it with two iptables rules

`# iptables -A PREROUTING -t nat -i eth0 -p udp --dport 53 -j DNAT --to 172.30.32.1:53`
`# iptables -A FORWARD -p udp -d 172.30.32.1 --dport 53 -j ACCEPT`
