### ISSUE TITLE
The DNS Server isn't responding

### ISSUE THREAD

**Issue by pantha007** [hassio-addons/addon-adguard-home#193]
# Problem/Motivation
After fresh install on update 4.1.6 window is telling me "The DNS Server isn't responding" 
2021/05/20 12:39:43.503518 [info] Listening to tcp://127.0.0.1:53 (dont know but i swear this had my ip of my pi in previously ? (192.168.0.132) ??
> (Why the issue was filed)
Adblock not working :-(
## Expected behavior
DNS Queries to be logged and processed
> (What you expected to happen)
DNS Queries to be logged and processed
## Actual behavior
DNS Queries not logged and not processed
> (What actually happened)
nothing from windows
## Steps to reproduce
Fresh install on Raspberry pi
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Restart the add-on... (Just once more, so it completes the migration).
