### ISSUE TITLE
No port binding on host interface

### ISSUE THREAD

**Issue by nicolasvila** [hassio-addons/addon-adguard-home#194]
# Problem/Motivation

No port binding on host interface

## Expected behavior

DNS should be available on the LAN not only on the host running home assistant.

## Actual behavior

DNS available only on 172.30.32.1 which is the Docker interface. It should be reachable from 192.168.x.y

```[14:11:02] INFO: Starting AdGuard Home server...
2021/05/20 14:11:03.068198 [info] AdGuard Home, version v0.106.3
2021/05/20 14:11:03.132043 [info] Initializing auth module: /data/adguard/data/sessions.db
2021/05/20 14:11:03.134347 [info] auth: initialized.  users:0  sessions:0
2021/05/20 14:11:03.134481 [info] Initialize web module
2021/05/20 14:11:04.406166 [info] Go to http://127.0.0.1:45158
[14:11:04] INFO: Starting NGinx...
2021/05/20 14:11:16.967425 [info] Starting the DNS proxy server
2021/05/20 14:11:16.967510 [info] Ratelimit is enabled and set to 20 rps
2021/05/20 14:11:16.973904 [info] The server is configured to refuse ANY requests
2021/05/20 14:11:16.974272 [info] DNS cache is enabled
2021/05/20 14:11:16.974329 [info] MaxGoroutines is set to 50
2021/05/20 14:11:16.974400 [info] Creating the UDP server socket
2021/05/20 14:11:17.076037 [info] Listening to udp://172.30.32.1:53
2021/05/20 14:11:17.076145 [info] Creating a TCP server socket
2021/05/20 14:11:17.076444 [info] Listening to tcp://172.30.32.1:53
2021/05/20 14:11:17.076796 [info] Entering the UDP listener loop on 172.30.32.1:53
2021/05/20 14:11:17.077185 [info] Entering the tcp listener loop on 172.30.32.1:53
```

## Steps to reproduce

Upgrade to 4.1.2+

## Proposed changes

How can we force upgrade to most recent version ? (4.1.6)

**Comment by frenck** [comment]
Supervisor -> Add-on Store -> Top right menu ... -> Reload

**Comment by nicolasvila** [comment]
Thanks for the tip, but the issue is not fixed with latest version :-(

**Comment by frenck** [comment]
Could you provide the output of `ha info` ?

**Comment by martymarty004** [comment]
I have the same issue, after updating the DNS server only listens to 127.0.0.1

Here's my `ha info` output:
```
arch: armv7                                               
channel: stable                                           
docker: 19.03.15                                          
features:                                                 
- reboot                                                  
- shutdown                                                
- services                                                
- network                                                 
- hostname                                                
- hassos                                                  
hassos: "5.13"                                            
homeassistant: 2021.5.4                                   
hostname: homeassistant                                   
logging: info                                             
machine: raspberrypi4                                     
operating_system: Home Assistant OS 5.13                  
state: running                                            
supervisor: 2021.04.3                                     
supported: true                                           
supported_arch:                                           
- armv7                                                   
- armhf                                                   
timezone: Europe/Rome                                     
~ $ ^C                                                    
~ $ ha info
arch: armv7
channel: stable
docker: 19.03.15
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.13"
homeassistant: 2021.5.5
hostname: homeassistant
logging: info
machine: raspberrypi4
operating_system: Home Assistant OS 5.13
state: running
supervisor: 2021.04.3
supported: true
supported_arch:
- armv7
- armhf
timezone: Europe/Rome
```

**Comment by frenck** [comment]
@martymarty004 That is not the same issue. Restart your add-on to complete your upgrade.

**Comment by frenck** [comment]
@nicolasvila That is not a supported system by the Home Assistant project and will cause issues.

**Comment by martymarty004** [comment]
> @martymarty004 That is not the same issue. Restart your add-on to complete your upgrade.

You were right, a simple restart fixed the issue. Thanks!

**Comment by nicolasvila** [comment]
> @nicolasvila That is not a supported system by the Home Assistant project and will cause issues.

Yes and No. It is one of the possible installation method. https://www.home-assistant.io/installation/linux#install-home-assistant-supervised
That's too bad because I could solve my problem with an iptable rule (dirty fix) in order to redirect the DNS requests on the LAN interface to the hassio docker interface. UDP/53 and TCP/53 (missing in config) should be configurable 
BTW,  I don't understand why that's not possible to have TCP/53 available on LAN interface in my case, whereas TCP/80 works well when activated

**Comment by tjorim** [comment]
@nicolasvila it is not:
1. First make sure you understand the requirements. -> https://www.github.com/home-assistant/architecture/tree/master/adr%2F0014-home-assistant-supervised.md

**Comment by nicolasvila** [comment]
I understand the requirements and of course I admit I use ArchLinux ARM instead of Debian 10. Port forwarding is a basic Docker feature though.
Nevertheless, I will have to consider migrating my installation to a full HassOS set up with a dedicated hardware.
Thanks for your time and commitment.
