### ISSUE TITLE
Huge amount of request since 4.1.6

### ISSUE THREAD

**Issue by Gunth** [hassio-addons/addon-adguard-home#197]
# Problem/Motivation

Since the update to the 4.1.6 Home assistant is requesting a huge amount of DNS requests.

![image](https://user-images.githubusercontent.com/1955976/119108475-85b6c680-ba20-11eb-9673-3a83c63433a6.png)

If i'm looking to Supervisor->System->Log Provider->DNS i can find a large number of those logs :

```
[INFO] 172.30.32.1:46684 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,rd,ra 43 1.002099974s
[INFO] 172.30.32.1:41806 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,rd,ra 43 1.001301207s
[INFO] 172.30.32.1:44227 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,rd,ra 43 1.003298088s
[INFO] 172.30.32.1:52511 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,aa,rd,ra 43 0.890525032s
[INFO] 172.30.32.1:56904 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,rd,ra 43 1.002256399s
[INFO] 172.30.32.1:50330 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,rd,ra 43 1.001957328s
[INFO] 172.30.32.1:49075 - 32946 "PTR IN 13.0.168.192.in-addr.arpa. udp 54 true 2048" SERVFAIL qr,aa,rd,ra 43 0.89248856s
.......
```

## Expected behavior

Usually i had 2500, 3000 DNS queries on average / hours

## Actual behavior

Now i have more than 80000 DNS queries / hours

## Steps to reproduce

Upgrade to 4.1.6 ( If it's linked to the update not sure, but based on the dns queries charts in adguard, the increasing queries has been produced in the same time and i didn't update other addons since  ).

**Comment by frenck** [comment]
The addon does not point things to itself, it runs a DNS server.... if queries get here, that is because an client has been configured to use this DNS. 

This is not related or controlled by the addon

**Comment by Gunth** [comment]
What is strange is when a disable the AdGuard Addon the Log Provider DNS in Supervisor doesn't containe anymore log PTR IN 13.0.168.192.in-addr.arpa. ...
