### ISSUE TITLE
Not listening on VLAN interfaces anymore

### ISSUE THREAD

**Issue by brywithawhy** [hassio-addons/addon-adguard-home#198]
# Problem/Motivation

Since updating to 4.16, service does not listen on sub interface eth0.2 address. Only primary and docker addresses. This is needed so the IoT vlan can use the adguard service

## Expected behavior

Service to listen on all interfaces

## Actual behavior

Only eth0 and a 172.x address (docker?) are listening to dns requests

## Steps to reproduce

Create a sub interface on a different network and start the AdGuard Home add on

Adguard Log:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.1.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.5.5
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[16:59:09] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:59:10] INFO: Starting AdGuard Home server...
2021/05/22 16:59:10.600995 [info] AdGuard Home, version v0.106.3
2021/05/22 16:59:10.624287 [info] Initializing auth module: /data/adguard/data/sessions.db
2021/05/22 16:59:10.624892 [info] auth: initialized.  users:0  sessions:0
2021/05/22 16:59:10.624937 [info] Initialize web module
2021/05/22 16:59:10.686651 [info] Go to http://127.0.0.1:45158
[16:59:10] INFO: Starting NGinx...
2021/05/22 16:59:11.265221 [info] Starting the DNS proxy server
2021/05/22 16:59:11.265686 [info] Ratelimit is enabled and set to 20 rps
2021/05/22 16:59:11.265843 [info] The server is configured to refuse ANY requests
2021/05/22 16:59:11.266067 [info] DNS cache is enabled
2021/05/22 16:59:11.266267 [info] MaxGoroutines is set to 300
2021/05/22 16:59:11.266559 [info] Creating the UDP server socket
2021/05/22 16:59:11.267112 [info] Listening to udp://10.0.0.250:53
2021/05/22 16:59:11.267474 [info] Creating the UDP server socket
2021/05/22 16:59:11.267861 [info] Listening to udp://172.30.32.1:53
2021/05/22 16:59:11.268142 [info] Creating a TCP server socket
2021/05/22 16:59:11.268391 [info] Listening to tcp://10.0.0.250:53
2021/05/22 16:59:11.268693 [info] Creating a TCP server socket
2021/05/22 16:59:11.269057 [info] Listening to tcp://172.30.32.1:53
2021/05/22 16:59:11.270538 [info] Entering the tcp listener loop on 172.30.32.1:53
2021/05/22 16:59:11.270701 [info] Entering the UDP listener loop on 172.30.32.1:53
2021/05/22 16:59:11.270985 [info] Entering the tcp listener loop on 10.0.0.250:53
2021/05/22 16:59:11.271329 [info] Entering the UDP listener loop on 10.0.0.250:53`

**Comment by albertoxamin** [comment]
I think it is related to #195
