### ISSUE TITLE
Addon UI credentials different from HA user credentials?

### ISSUE THREAD

**Issue by NicoLeOca** [hassio-addons/addon-adguard-home#201]
I just can't find which password I need to use to connect to the web UI directly.
My final purpose is to use this soft to sync 2 AGH instances:
https://github.com/bakito/adguardhome-sync
It requires to authenticate.
However my HA user credentials just don't work.
Also when I try to hit http://myinternalIP:80 directly, it refuses my credentials too.
This seems logical though.

Can you help please?

**Comment by sinclairpaul** [comment]
It is the Home Assistant credentials, assuming you have exposed the web interface on a port.
