### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by sydney-d** [hassio-addons/addon-adguard-home#215]
Hello,

I clicked the link to install adGaurd home : 
https://my.home-assistant.io/redirect/config_flow_start?domain=adguard

And it openned this screen: 
![image](https://user-images.githubusercontent.com/46789893/123062232-9d60e080-d40c-11eb-87b3-db674936eb9b.png)
How do I fill it ?

Host: is it my local network home assistant IP ? `192.168.0.11` doesn't work.
Port: should it be 8123 ?

Username and Password are the ones I use to connect to home assistant ? 

Thanks

**Comment by frenck** [comment]
Hi there @sydney-d 👋 

Your question is about a Home Assistant Integration, however, this is the repository and issue tracker of the Home Assistant Add-on. Those are not the same things and not related.

../Frenck
