### ISSUE TITLE
Add IPV6 Client configuration

### ISSUE THREAD

**Issue by PortalFreak** [hassio-addons/addon-adguard-home#23]
# Problem/Motivation
Clients
Configure devices connected to AdGuard Home. 
It is not possible to add IPV6 Client IP to resolve connected clients into their clientname

> (Why the issue was filed)

## Expected behavior
See on the Dashboard for tile -> 
Top clients
for the last 24 hours

(for example)
Notebook (fd00::0000:dddd:eeee:ffff) 

validate IPV6 clientip in the setting, by adding clients to the list of clients
> (What you expected to happen)

## Actual behavior

IPV6 Client ip is not supported during the form validation

> (What actually happened)

## Steps to reproduce
go to:
Settings -> Client Settings -> add client
use ipv6 adress

-> Error by the formvalidation:  Invalid IPv4 format

> (How can someone else make/see it happen)

runnings version hassio 0.94.4 
AdGuard 2.0.0
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an add-on issue, but a limitation of AdGuard itself.

There is already an issue/feature request open for it. You can track it here:
<https://github.com/AdguardTeam/AdGuardHome/issues/809>
