### ISSUE TITLE
AddGuard Home add-on binds to one interface only

### ISSUE THREAD

**Issue by rondoval** [hassio-addons/addon-adguard-home#239]
# Problem/Motivation

AddGuard Home add-on binds to one interface only (the 'default' one).

## Expected behavior

I would expect the add-on to bind the DNS service to all available interfaces.

## Actual behavior

AdGuard Home add-on binds to the 'default' interface only. I think this generates two issues:
a) There is only one network interface where the DNS service is exposed
b) That interface appears to be randomly selected, i.e. in my setup with three network interfaces, each reboot of HassOS changes the default interface.

## Steps to reproduce

HassOS running in a VM (ESXi) with several network interfaces configured.

## Proposed changes

I have a patch prepared which enumerates all network interfaces using bashio::network.interfaces and adds their IP adressess to the hosts array. The change would be in rootfs/etc/cont-init.d/adguard.sh - see https://github.com/rondoval/addon-adguard-home/commit/57cf8840ae037be70cf65520b155db96959777b4
That is if you agree with the expected behavior described above of course.

**Comment by tbrtje** [comment]
That should be the expected behaviour considering other addons also expose their service on all interfaces.
Maybe you can open a pull request for those commits.
