### ISSUE TITLE
AdGuard Filter Switch not working

### ISSUE THREAD

**Issue by thekayman** [hassio-addons/addon-adguard-home#241]
# Problem/Motivation
AdGuard configured and working but when I use the HA integration and toggle the AdGuard Filtering switch nothing happens

HA installed on a NUC using supervisor image
Installed AdGuard 4.1.9
Home Assistant OS 6.2
Supervisor-2021.06.8
Core-2021.8.8

## Expected behavior

When the AdGuard Filtering switch is toggled the AdGuard filtering should be turned off or on.

## Actual behavior

The switch makes no difference the filtering is always on no mater what state the switch is in.
I tested using nslookup on a machine and toggled the switch the results were 0.0.0.0 however if i turn off AdGuard Protection switch the filter turns off.

I have added filters in Blocked Services and custom filtering rules.

## Steps to reproduce

perform nslookup on a record that is filtered, toggle the AdGuard Filtering switch and see if it resolves or not.

## Proposed changes

Not sure if this is a bug?

**Comment by frenck** [comment]
This is not related to the add-on but the  integration in Home Assistant. Thus this issue is in the wrong issue tracker
