### ISSUE TITLE
Have a issues with Tuya Platform

### ISSUE THREAD

**Issue by anhtuanng98** [hassio-addons/addon-adguard-home#25]
When I turn on Adguard Home, Tuya component cannot send request.
<img width="1128" alt="2019-07-01" src="https://user-images.githubusercontent.com/48097920/60510257-3581ce80-9cf9-11e9-870b-ecd6bf8634c9.png">
I tried to turn off all filters but it still have error.
Only when I turn off Adguard, Tuya component comeback

**Comment by frenck** [comment]
You missed or did not execute step 1 of the installation manual of the AdGuard add-on correctly.
This happens if you don't follow the installation guide.
