### ISSUE TITLE
AdGuard and Dnsmasq need the same UDP 53

### ISSUE THREAD

**Issue by Axydas** [hassio-addons/addon-adguard-home#250]
# Problem/Motivation

> I installed both AdGuard and Dnsmasq but they are using the same DNS UDP 53. I can use only one add on at a time. If i dissable the Adguard the Dnsmasq is working perfectly and the opposite. I tried to set the AdGuard in another port 5353 but i get the error:
couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp x.x.0.x:5353: bind: address already in use

## Expected behavior

I am looking for a way to use both addons

## Actual behavior

If i use any random UDP for AdGuard, the addon start normally but obvious is not actually working. It does nothing

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> stalled both AdGuard and Dnsmasq but they are using the same DNS UDP 53. I can use only one add on at a time.

Yes, that is how ports work.

> couldn't start forwarding DNS server: couldn't listen to UDP socket, cause: listen udp x.x.0.x:5353: bind: address already in use

Seems like 5353 is also in use already.


I cannot solve this for you, you are the only one that can solve that. I cannot fix port collision that are caused by your own use case.

Sorry!

../Frenck
