### ISSUE TITLE
Connection refused on HTTPS port

### ISSUE THREAD

**Issue by notherealmarco** [hassio-addons/addon-adguard-home#257]
# Problem/Motivation

(I'm not sure if this should be reported here or on AdguardTeam/AdGuardHome)

> After configuring TLS and HTTPS ports, TLS port is working fine and I can successfully use the DoT protocol.
HTTPS port instead, keeps giving me a connection refused error.

With the configuration shown in the screenshot below, I can't resolve DNS queries with the `https://dns.marcorealacci.me:444/dns-query` DoH server and I can't access the web interface on `https://dns.marcorealacci.me:444`. Seems like the server is not listening on the HTTPS port. (Port is correctly mapped on the router)

DoT on `tls://dns.marcorealacci.me:853` works fine instead

![image](https://user-images.githubusercontent.com/15275377/135250434-77b89956-a951-4cc4-8fec-aa5c43228c09.png)
![image](https://user-images.githubusercontent.com/15275377/135250732-7d9159df-a638-49f6-b723-fb8fbd19ea78.png)

## Expected behavior

> Being able to resolve queries using the DoH server

## Actual behavior

> Server not listening on the given port

## Steps to reproduce

> See attached screenshots

**Comment by sinclairpaul** [comment]
From what I recall the DoH server shares the binding with the admin interface (which is on listening on localhost).

We added a mapping for Nginx to proxy the requests, if you configure a port in the config for the admin interface and SSL you should be able to access.  You will need to be wary of port conflicts.

**Comment by notherealmarco** [comment]
That fixed it. Thanks!
