### ISSUE TITLE
Adguard addon has stopped accepting Android client connections - believed to be due to expired DST root cert

### ISSUE THREAD

**Issue by stevehop** [hassio-addons/addon-adguard-home#258]
# Problem/Motivation

> I've been using the addon's DoT server for my 3 Android devices with no problems for more than a year, 2 days ago it randomly stopped accepting connections, this occurred at the same time that my VPN server, which is also secured using Let's Encrypt certs started misbehaving.

I can connect externally to my DoT server using a Windows DNS client and my Android devices can connect to Adguard's officially hosted DoT server so my network access is ok and Android's private DNS functionality is still working.

I believe that this is related to https://github.com/AdguardTeam/AdGuardHome/issues/3696

I have forced the renewal of my Nginx certs using this command `certbot --preferred-chain "ISRG Root X1" --force-renewal` but the problem remains

## Expected behavior

> Ability to setup the DoT server and access using an Android client's private DNS feature

## Actual behavior

> Android private DNS functionality reports that it "couldn't connect"

## Steps to reproduce

> Attempt to connect to a DoT server secured using Nginx and Let's Encrypt certs from an Android device's private DNS feature

**Comment by shimuldn** [comment]
Hi,
What you're missing is port 853. `TLS` work on port 853 so it doesn't matter if you're using Nginx or something else.
To work with DOH proper Nginx config is needed!
Just tested my dns server with Nginx and TLS.

Stopped Nginx. Android private dns working as expected after the `--preferred-chain "ISRG Root X1".`
Port open on my system 53, 80, 443, 853.
Removing 853 from allow list result `Couldn't connect`.

So please check your firewall, open port 853. 



<img width="1170" alt="Screen Shot 2021-10-03 at 7 23 03 pm" src="https://user-images.githubusercontent.com/12117121/135756677-2dca0ed9-932b-4cb6-a9b6-1474f1645744.png">

**Comment by stevehop** [comment]
Port 853 is definitely open and forwarded to my HA server which is confirmed by successfully using DoT on a windows client with a mobile hotspot

**Comment by stevehop** [comment]
Certificates aren't my area of expertise but having renewed my cert by `certbot --preferred-chain "ISRG Root X1" --force-renewal` I'm surprised to see this when checking my site on www.ssllabs.com:

![image](https://user-images.githubusercontent.com/52283434/135760608-e5edde5c-3563-40be-b3db-fa4d3b79875a.png)

**Comment by shirou93** [comment]
For several days my android devices get same issue. Error when try connect as private DNS. Looks like google stopped accept certificate.
