### ISSUE TITLE
Getting warning in home assistant logs related to backup vs snapshots

### ISSUE THREAD

**Issue by ahmadyusuf** [hassio-addons/addon-adguard-home#262]
# Problem/Motivation

Getting the below warning in HA system logs
21-10-11 11:34:46 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home

HA core version: 2021.10.2
AdGuare Home version:  4.1.9

## Expected behavior

There should be no warnings, and the plugin should start using backup instead of snapshot

## Actual behavior

Warnings are coming in the logs

## Steps to reproduce

Updated HA to 2021.10.2

**Comment by brainfrz82** [comment]
The release scheduled for next wednesday (2021.11.0) will remove the "snapshot" service. 

https://rc.home-assistant.io/blog/2021/10/27/release-202111/

"Old services and service data that contained “snapshot” has now been removed, you need to update your configuration if you use any of these to continue to use it."

I'm not sure if that will mean adguard won't work at all, or if you can't make backups anymore. But would be nice to see a update matching the upcoming HA release.

**Comment by frenck** [comment]
> The release scheduled for next wednesday (2021.11.0) will remove the "snapshot" service.

From Core, not the Supervisor, you are mixing things up. Please don't cause panic.

**Comment by brainfrz82** [comment]
> > The release scheduled for next wednesday (2021.11.0) will remove the "snapshot" service.
> 
> From Core, not the Supervisor, you are mixing things up. Please don't cause panic.

Thank you for clearing things up, it wasn’t my intention to cause panic.

**Comment by metbril** [comment]
What is the ETA for a fix?

**Comment by frenck** [comment]
Warning mitigated with the V4.2.0 release
