### ISSUE TITLE
Hosts sections not supporting ipaddress:port

### ISSUE THREAD

**Issue by purebenwoo** [hassio-addons/addon-adguard-home#27]
# Problem/Motivation

> I have a number of services running off my server, and I'd like to define DNS entries such as server.example.org:8123 as simply homeassistant.example.org. 

## Expected behavior

> I would expect that defining this in the hosts section of the config would work.

## Actual behavior

> Will not allow me to save the config file.

## Steps to reproduce

> Add the following to the hosts section of the config:
`    {
      "name": "Desktop",
      "ip": "192.168.1.5:8123"
    },`

## Proposed changes

> Please support various ports in the hosts/ip section. Thank you.

**Comment by frenck** [comment]
This is just for visual purposes, not for resolving. Please see the add-on manual for that.
If you want to resolve custom hostnames, you can do that in AdGuard itself, see the filters section for more information.
