### ISSUE TITLE
Adguard addon disk usage growing

### ISSUE THREAD

**Issue by Automan69** [hassio-addons/addon-adguard-home#276]
Describe the issue you are experiencing
Hi Team,
I noticed the size of my automated backups becoming bigger and bigger (>1.5gb). It made me look into what was causing the backup files to be so big. I noticed that the Adguard addon in particular was growing by 20mb per day and was over 700mb. The other biggest contributors to my backup size were Frigate @ 400MB and Unifi @ 300MB.
I'm running HA on a NUC on Proxmox 7. I tried deleting the Adguard addon and reinstalling. This did work but the new addon is again growing.
I use the unifi software to ensure all DNS requests on my network are directed through Adguard with all other DNS requests dropped.

I assume others have also seen this behaviour?

Keep up the good work. HA is awesome!

Cheers

What type of installation are you running?
Home Assistant OS

Which operating system are you running on?
Home Assistant Operating System

Which add-on are you reporting an issue with?
AdGuard Home

What is the version of the add-on?
AdGuard Home version: 4.2.0

Steps to reproduce the issue
The only way I know to see the size an addon occupies is via "Home Assistant Google Drive Backup".

I've attached my Adguard config fyi.
[Adguard upload.zip](https://github.com/hassio-addons/addon-adguard-home/files/7576199/Adguard.upload.zip)

**Comment by Minims** [comment]
Hello, i have the same issue, many GB of logs in my host message, syslog 
```
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 127.0.0.1:50882 - 41065 "PTR IN 95.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 0.014276732s
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 172.30.32.1:54997 - 41065 "PTR IN 95.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 1.092530127s
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 127.0.0.1:45951 - 51155 "PTR IN 32.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 0.008296909s
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 172.30.32.1:56540 - 51155 "PTR IN 32.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 1.094880268s
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 127.0.0.1:53147 - 10454 "PTR IN 94.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 0.009199806s
Dec 17 16:36:41 home 61340c61adf7[640]: [INFO] 127.0.0.1:50882 - 39458 "PTR IN 98.1.168.192.in-addr.arpa. udp 54 true 2048" NXDOMAIN qr,rd,ra 43 0.008096281s
```

i have set log to warning, but it does not change anything
