### ISSUE TITLE
Add Configuration Setting to add additional interfaces to AdGuardHome.yaml

### ISSUE THREAD

**Issue by yonz2** [hassio-addons/addon-adguard-home#278]
# Problem/Motivation
After switching to AdGuard on my Home Assistant installation
(RPI 4,  core-2021.11.3, os_version | 5.10.17-v8, host_os | Home Assistant OS 6.6, ZeroTier One (0.12.1), , AdGuard Home (4.2.0))
I'm not able to use AdGuard as DNS server for my Zerotier Overlay network. 

The problem is similar to the one reported here: https://github.com/hassio-addons/addon-adguard-home/pull/253 , i.e. AdGuard is not listening on the ZeroTier Interface 10.147.x.y/24 (if: ztklhquq5s), created by the ZeroTier Addon 

However, I think it would be "to much" to use the propsed patch. I'd much rather have a simple configuration option, where I can add the interface as part of the Addon configuration .

## Expected behavior
AdGuard DNS should listen to the standard interfaces, as well as the ones defined in the Addon Configurtion section

## Actual behavior

DNS Server is not listenting on ZeroTier interface, created by the ZeroTier-One Addon

## Steps to reproduce

1) Install AdGuard AddOn
2) Install ZeroTier-One Addon (configure with Network Identifier) --> REsults in Network Interface with IP: 10.147.42.42
3) From a ZT Client on the network issue the follwoing: nslookup google.com 10.147.42.42
--> Results: ;; connection timed out; no servers could be reached

## Proposed changes

Add a configuration parameter to the AdGuard addon to define additional network interfaces  --or--
Add a configuration parameter to the AdGuard addon to detect ZeroTier-One Interface, ...
Then add this new interface (IP4 and IP6 )addressess) to the "bind_hosts" list in "AdGuardHome.yaml

**Comment by Cycor** [comment]
I'm a having a similar since the last update, I am running on LXC, so unsupported, but I need hardware acceleration so I can't switch to a vpc.
But that means that the new ip collection code doesn't work, i get
`Got unexpected response from the API: Interface vlan_lan does not exist`

So I would love to have an option to set the ip instead of changing the script with portainer every update.

**Comment by frenck** [comment]
@Cycor Your system is unsupported, so that won't be happening for that reason. Please use a supported system instead, or, consider a different installation method for Home Assistant.

**Comment by frenck** [comment]
As for the request in this issue, that won't be implemented.
The current version has been adjusted to listening on all interfaces that the Supervisor is managing / aware of.

Nevertheless, thanks for the suggestion.

**Comment by yonz2** [comment]
Ok... tht begs the question which interfaces is ithe Supervisor aware of? Does it mean that the Supervisor is not picking up "virtual" interfaces created by other addons? (Zerotier, Wireguard, etc.)?

**Comment by frenck** [comment]
> Does it mean that the Supervisor is not picking up "virtual" interfaces created by other addons?

Those are not managed by the supervisor and thus she will not be aware
