### ISSUE TITLE
enable entity_category: config for adguard setting entities

### ISSUE THREAD

**Issue by raidnet-ms** [hassio-addons/addon-adguard-home#282]
# Problem/Motivation

> By default there are too many undesired settings entities in google home, and lovelace

## Expected behavior

> Hide most of unecessary default switches as recently outlined as best practice for entities

## Actual behavior

> all settings switch appear on google home dashboard and lovelace dashboard

## Steps to reproduce

> add adguard integration

## Proposed changes

> [just stick with the plan](https://developers.home-assistant.io/blog/2021/10/26/config-entity/)

**Comment by frenck** [comment]
This is the add-on, not the integration. You are mixing up things.

**Comment by raidnet-ms** [comment]
Yup I am. Sorry

**Comment by frenck** [comment]
Don't worry! ❤️

**Comment by raidnet-ms** [comment]
I suppose I should add it here:
https://github.com/AdguardTeam/AdGuardHome/issues/3965

**Comment by frenck** [comment]
No, it is the Home Assistant integration. Home Assistant has a feature request second on their community forum.

**Comment by raidnet-ms** [comment]
> No, it is the Home Assistant integration. Home Assistant has a feature request section on their community forum.

aha that's why I couldn't find anything here on github...
