### ISSUE TITLE
Addon stays in sidebar after uninstall

### ISSUE THREAD

**Issue by StealthChesnut** [hassio-addons/addon-adguard-home#29]
# Problem/Motivation

I uninstalled the addon after adding it to my sidebar. The entry in my sidebar stayed but wasn't functional. I couldn't remove it by logging out / logging in.

## Expected behavior

When the uninstall button was clicked I expected the addon to be removed from the sidebar as part of the uninstall process.

## Actual behavior

The addon wasn't removed, and then could not be removed until the addon was reinstalled, the toggle changed for showing in the sidebar, then uninstalled again.

## Steps to reproduce

Install addon, toggle the option to show in the sidebar, uninstall the addon. You can see in the attached screenshot that the sidebar entry is present, but the addon is not installed (icon is black, not green)
![Capture](https://user-images.githubusercontent.com/46853524/62000130-e779a400-b0c7-11e9-896f-2c7fe6f5ba1c.PNG)

**Comment by sinclairpaul** [comment]
Does a force reload of the page help?, if not this will be an upstream issues in HomeAssistant, not an addon issue.  It would need to be logged there.

**Comment by StealthChesnut** [comment]
No, reloading the page, logging out/in didn't work. I shall reopen upstream, thank you.

**Comment by sinclairpaul** [comment]
Thanks, just to add I would assume you could re-install the addon, uncheck, the uninstall to resolve the immediate issue.

**Comment by frenck** [comment]
You need to restart Home Assistant.
