### ISSUE TITLE
AdGuard Encryption settings Errors

### ISSUE THREAD

**Issue by Himola** [hassio-addons/addon-adguard-home#294]
# Problem/Motivation

Issues with Cloudflare certificates used

## Expected behavior

No errors

## Actual behavior

Getting errors

## Steps to reproduce

Use Cloudflare origin.pem and privkey.pem

## Proposed changes

After adding my Cloudflare certificates in Encryption settings with certificate path /ssl/cloudflare.pem I get this:

Status:
**Certificate chain is invalid**
Subject: CN=CloudFlare Origin Certificate,OU=CloudFlare Origin CA,O=CloudFlare\, Inc.
Issuer: OU=CloudFlare Origin SSL Certificate Authority,O=CloudFlare\, Inc.,L=San Francisco,ST=California,C=US
Expires: 2037-01-10 13:25:00
Hostnames: *.example.com, example.com

and for the private key path /ssl/private.pem I get his:

Status:
This is a valid RSA private key
**Your certificate does not verify: x509: certificate signed by unknown authority**

Any idea how can I fix this?

**Comment by sinclairpaul** [comment]
The Cloudflare Origin cert is designed to be used for protection between Cloudflare and the destination server, it's essentially self-signed.

This isn't a valid use case for that, I would suggest looking at letsencrypt certificates.
