### ISSUE TITLE
Permanent TCP i/o timeout error messages in log

### ISSUE THREAD

**Issue by iHaveAstream** [hassio-addons/addon-adguard-home#295]
# Problem/Motivation
The AGH log throws endlessly (and approx. every 30 sec) an error message like:

2022/01/20 13:04:58.824082 [error] handling tcp: reading msg: reading len: read tcp 10.10.30.3:58853->109.43.115.80:5419: i/o timeout

AGH addon: v4.4.2

## Expected behavior

AGH shall not do these queries. What's the reason for it?

## Actual behavior

first IP is AGHs internal and the port is my defined port for DoT. In my security appliance I do a NAT forward from port 853 (ext.) to that 58853 (int.).
second IP is in that case a mobile device (LTE) that has DoT enabled in its OS settings (Android 12) because this mobile device should use the AGH DoT resolver to block ads.

I cannot identify the root cause for this issue, but AGH seems to work as it should. DNS resolving works as expected. Other services from the addon are not used, just DNS.
I do not understand why AGH DoT resolver tries to query the external IP of a device that queries the resolver, because normally the queries are inbound to the resolver.
Once I disable the DoT setting in my mobile device so that there are no more queries from the mobile to AGH DoT, also those log entries immediately stop.

## Steps to reproduce

no clue if it's reproducible in another environment.

## Proposed changes

no idea at the moment.

**Comment by sinclairpaul** [comment]
Please see upstream https://github.com/AdguardTeam/AdGuardHome/issues/4128
