### ISSUE TITLE
[fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 

### ISSUE THREAD

**Issue by ned786** [hassio-addons/addon-adguard-home#298]
After installing the update adguard no longer loads. i get [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 

is anyone else getting this or is it just my setup?

Thank you!

**Comment by frenck** [comment]
Could you provide some data that actually could help?

For example: Full logs, system information, or information on the add-on version you are running. These things can be quite helpful when reporting something that doesn't work.

**Comment by tannertechnology** [comment]
I just updated to Home Assistant 2022.2.3 running under Home Assistant OS 7.3. I'm running Adguard 4.4.4 and here is the full log:

`2022/02/08 06:32:41.294105 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:41.294143 [info] Creating the UDP server socket
2022/02/08 06:32:41.311199 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:41] INFO: Starting AdGuard Home server...
2022/02/08 06:32:41.575766 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:41.854583 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:41.855272 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:41.855562 [info] Initialize web module
2022/02/08 06:32:42.129866 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:42.129942 [info] Go to http://127.0.0.1:45158
2022/02/08 06:32:44.172218 [info] Starting the DNS proxy server
2022/02/08 06:32:44.172464 [info] The server is configured to refuse ANY requests
2022/02/08 06:32:44.172572 [info] DNS cache is enabled
2022/02/08 06:32:44.172715 [info] Creating the UDP server socket
2022/02/08 06:32:44.173720 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:44.173776 [info] Creating the UDP server socket
2022/02/08 06:32:44.316467 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:44] INFO: Starting AdGuard Home server...
2022/02/08 06:32:44.599759 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:44.682341 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:44.684301 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:44.684660 [info] Initialize web module
2022/02/08 06:32:44.964326 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:44.964396 [info] Go to http://127.0.0.1:45158
2022/02/08 06:32:47.065872 [info] Starting the DNS proxy server
2022/02/08 06:32:47.065946 [info] The server is configured to refuse ANY requests
2022/02/08 06:32:47.065971 [info] DNS cache is enabled
2022/02/08 06:32:47.066041 [info] Creating the UDP server socket
2022/02/08 06:32:47.066599 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:47.066675 [info] Creating the UDP server socket
2022/02/08 06:32:47.149563 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:47] INFO: Starting AdGuard Home server...
2022/02/08 06:32:47.395613 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:47.465695 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:47.466585 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:47.466702 [info] Initialize web module
2022/02/08 06:32:47.771757 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:47.771839 [info] Go to http://127.0.0.1:45158
2022/02/08 06:32:49.904287 [info] Starting the DNS proxy server
2022/02/08 06:32:49.904362 [info] The server is configured to refuse ANY requests
2022/02/08 06:32:49.904388 [info] DNS cache is enabled
2022/02/08 06:32:49.904452 [info] Creating the UDP server socket
2022/02/08 06:32:49.904785 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:49.904830 [info] Creating the UDP server socket
2022/02/08 06:32:51.957121 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:52] INFO: Starting AdGuard Home server...
2022/02/08 06:32:52.196860 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:52.252917 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:52.254748 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:52.255044 [info] Initialize web module
2022/02/08 06:32:52.531756 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:52.534086 [info] Go to http://127.0.0.1:45158
2022/02/08 06:32:54.590326 [info] Starting the DNS proxy server
2022/02/08 06:32:54.590716 [info] The server is configured to refuse ANY requests
2022/02/08 06:32:54.591128 [info] DNS cache is enabled
2022/02/08 06:32:54.591421 [info] Creating the UDP server socket
2022/02/08 06:32:54.594512 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:54.594974 [info] Creating the UDP server socket
2022/02/08 06:32:54.609544 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:54] INFO: Starting AdGuard Home server...
2022/02/08 06:32:54.812890 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:54.859729 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:54.860459 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:54.860647 [info] Initialize web module
2022/02/08 06:32:55.132313 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:55.132394 [info] Go to http://127.0.0.1:45158
2022/02/08 06:32:57.256867 [info] Starting the DNS proxy server
2022/02/08 06:32:57.257121 [info] The server is configured to refuse ANY requests
2022/02/08 06:32:57.257338 [info] DNS cache is enabled
2022/02/08 06:32:57.257696 [info] Creating the UDP server socket
2022/02/08 06:32:57.260843 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:32:57.261173 [info] Creating the UDP server socket
2022/02/08 06:32:57.299168 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:32:57] INFO: Starting AdGuard Home server...
2022/02/08 06:32:57.493635 [info] AdGuard Home, version v0.107.3
2022/02/08 06:32:57.537570 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:32:57.538021 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:32:57.538110 [info] Initialize web module
2022/02/08 06:32:57.815527 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:32:57.815603 [info] Go to http://127.0.0.1:45158
2022/02/08 06:33:00.028018 [info] Starting the DNS proxy server
2022/02/08 06:33:00.028285 [info] The server is configured to refuse ANY requests
2022/02/08 06:33:00.028708 [info] DNS cache is enabled
2022/02/08 06:33:00.028970 [info] Creating the UDP server socket
2022/02/08 06:33:00.029544 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:33:00.030992 [info] Creating the UDP server socket
2022/02/08 06:33:00.133987 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
[06:33:00] INFO: Starting AdGuard Home server...
2022/02/08 06:33:00.418117 [info] AdGuard Home, version v0.107.3
2022/02/08 06:33:00.494255 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/02/08 06:33:00.495226 [info] auth: initialized.  users:0  sessions:0
2022/02/08 06:33:00.495527 [info] Initialize web module
2022/02/08 06:33:00.779215 [info] AdGuard Home is available at the following addresses:
2022/02/08 06:33:00.779549 [info] Go to http://127.0.0.1:45158
2022/02/08 06:33:02.830926 [info] Starting the DNS proxy server
2022/02/08 06:33:02.830993 [info] The server is configured to refuse ANY requests
2022/02/08 06:33:02.831022 [info] DNS cache is enabled
2022/02/08 06:33:02.831095 [info] Creating the UDP server socket
2022/02/08 06:33:02.831433 [info] Listening to udp://10.0.0.13:53
2022/02/08 06:33:02.831468 [info] Creating the UDP server socket`

**Comment by tannertechnology** [comment]
I did a lot more testing. Adguard addon version 4.2.0 works on HassOS 7.4, Home Assistant 2022.2.9. If it helps I'm running on a Raspberry Pi 3B+. Updating the Adguard addon to 4.3.0 or any version after results in the errors above.

**Comment by Saars1337** [comment]
I have been having this issue for ages so have been unable to run Adguard. How do I downgrade the addon in hassio?

**Comment by tannertechnology** [comment]
@Saars1337 My understanding is the only supported way to get an older version is to restore from a backup. People have claimed you can take a partial backup of the addon, change the versions inside the partial backup, and restore that to select a custom version but that is not supported and may not work.

**Comment by rishabmehta7** [comment]
Same issue

**Comment by tannertechnology** [comment]
Still doesn't work. 
Environment:

- Raspberry Pi 3B+
- HassOS 7.6
- Supervisor 2022.03.5
- Home Assistant 2022.3.8

With Adguard home addon version 4.5.0 adguard never serves requests and I'm unable to access it's UI. Here is the relevant section of the logs (loops forever smashing CPU):

```
[19:58:41] INFO: Starting AdGuard Home server...
2022/04/04 19:58:41.595333 [info] AdGuard Home, version v0.107.5
2022/04/04 19:58:41.644669 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/04/04 19:58:41.645117 [info] auth: initialized.  users:0  sessions:0
2022/04/04 19:58:41.645210 [info] Initialize web module
2022/04/04 19:58:41.944383 [info] AdGuard Home is available at the following addresses:
2022/04/04 19:58:41.944501 [info] Go to http://127.0.0.1:45158
2022/04/04 19:58:44.158496 [info] Starting the DNS proxy server
2022/04/04 19:58:44.158567 [info] The server is configured to refuse ANY requests
2022/04/04 19:58:44.158595 [info] DNS cache is enabled
2022/04/04 19:58:44.158760 [info] Creating the UDP server socket
2022/04/04 19:58:44.162167 [info] Listening to udp://10.0.0.13:53
2022/04/04 19:58:44.162313 [info] Creating the UDP server socket
2022/04/04 19:58:44.173515 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 10.0.0.13:53: bind: address already in use
```



With Adguard home addon version 4.2.0 it works as expected. I'm unable to test 4.3.0 and 4.4.0 as I have no backup of those versions.

**Comment by harrywesterman** [comment]
Wow, that explains all my network issues, Adguard has been broken all that time? Most of the time I configured a secondary, so I didn't notice at first... Same error here.

**Comment by tannertechnology** [comment]
I've moved mine to a separate VM running the docker image and it works great. V 4.2.0 also still works. It definitely isn't an upstream issue but the 3-4 layers of abstraction Hassio and this with it's base image etc cause I can't effectively troubleshoot.

**Comment by jurekmff** [comment]
Also having the same issue. Is there a solution to this without downgrading to an older AdGuard version? Unfortunately I don't have a snapshot with an older version.
`[16:32:25] INFO: Starting AdGuard Home server...
2022/04/14 16:32:25.732071 [info] AdGuard Home, version v0.107.5
2022/04/14 16:32:25.749529 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/04/14 16:32:25.756173 [info] auth: initialized.  users:0  sessions:0
2022/04/14 16:32:25.756592 [info] Initialize web module
2022/04/14 16:32:26.140267 [info] AdGuard Home is available at the following addresses:
2022/04/14 16:32:26.140451 [info] Go to http://127.0.0.1:45158`

**Comment by solid-pixel** [comment]
the problem is still there.
AdGuard runs the first time after you install it, then as soon as you restart the addon or the host once, it will throw this error every time: 

`2022/05/18 21:38:15.700241 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 192.168.0.144:53: bind: address already in use`

I've tried changing the port in the config, and it keeps throwing the same error, just on the new port I set.

**Comment by tannertechnology** [comment]
Confirming this is still an issue for me as well. 

Raspberry Pi 3B+
HassOS 8.0
Supervisor 2022.05.2
Home Assistant 2022.5.5

**Comment by tannertechnology** [comment]
Updated Hassos, core, and the addon today and it appears to be all working now. Not sure what the cause was still.

Raspberry Pi 3B+
HassOS 8.2
Supervisor 2022.05.3
Home Assistant 2022.6.7
Adguard Home addon version 4.6.0
