### ISSUE TITLE
Can't setup localhost

### ISSUE THREAD

**Issue by ohhmyladygaga** [hassio-addons/addon-adguard-home#30]
# Problem/Motivation

> can't setup localhost

## Expected behavior

> I hope it could resolve my ha host address locally, like 192.168.1.130

## Actual behavior

> However, after I set it up and restart the addon, adguard dns still responds with public ip address.

## Steps to reproduce

> do exactly what I did

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Not exactly sure on the issue here, perhaps you could add some more details and logs?

Unfortunately we will not be able to reproduce ```do exactly what I did``` 😄
