### ISSUE TITLE
Unable to Update to 4.4.5

### ISSUE THREAD

**Issue by boardwalk44** [hassio-addons/addon-adguard-home#303]
# Problem/Motivation

> Unsure if this is a HomeAssistant issue or an issue with the latest release of AdGuard. When attempting to upgrade from 4.4.4 to 4.4.5, I get thrown an error code.

## Expected behavior

> I expect for the addon to update as normal.

## Actual behavior

> Receive error 'a0d7b954_adguard'. Log entry included below.

22-03-01 21:32:18 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_adguard'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 265, in update
    store = self.store[slug]
KeyError: 'a0d7b954_adguard'

## Steps to reproduce

> Try to upgrade from 4.4.4 to 4.4.5 on Core 2022.2.9 / Supervisor 2022.01.1 / Host OS 7.4

![Screenshot 2022-03-01 214133](https://user-images.githubusercontent.com/87936927/156284602-3792eb27-e84f-403f-9d4c-ac985df7c9e9.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by GameGamer43** [comment]
@boardwalk44 do you have an upstream ticket for this? Asking as I'm seeing similar with the latest adguard release of 4.5.0 and would like to follow along.
