### ISSUE TITLE
Missing IP binding in AdGuard configuration

### ISSUE THREAD

**Issue by OldShaterhan** [hassio-addons/addon-adguard-home#309]
# Problem/Motivation

> It seems that AdGuard Home addon doesn't show on configuration screen any option to bind IP address:
![image](https://user-images.githubusercontent.com/1622866/158481113-560ecaeb-1087-4ddf-89bc-4e24ca57967a.png)
This causes it to listen only on 127.0.0.1:
![image](https://user-images.githubusercontent.com/1622866/158481233-c08ed173-8724-4c56-b36f-698cc7fc9d7d.png)
and issues like here: https://www.reddit.com/r/Adguard/comments/nifob8/adguard_listening_on_127001_instead_of_the_hassio/gz50xve/?utm_source=reddit&utm_medium=web2x&context=3 and https://community.home-assistant.io/t/adguard-listening-on-127-0-0-1-instead-of-the-hassio-ip/310137/6

## Expected behavior

> AdGuard addon should allow to have set binded IP address relating to: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

## Actual behavior

> No possibility to set IP address and because of that it doesn't work properly.

## Steps to reproduce

> Just install AdGuard.

## Proposed changes

> Extend configuration screen by adding option to set IP address or make AdGuard in HomeAssistant reading IP of the instance and set it automatically for binding.

**Comment by frenck** [comment]
It binds to the available interface automatically, as that information is managed and provided by the Home Assistant Supervisor.
