### ISSUE TITLE
Add dhcp leases database to hassio snapshots

### ISSUE THREAD

**Issue by tefinger** [hassio-addons/addon-adguard-home#31]
# Problem/Motivation

The static dhcp leases are currently not persisted in hassio snapshots.

## Expected behavior

The leases.db file which is located in `/opt/AdGuard/` should stored in `/data/adguard/` so that is will be included in snapshots.

The name of the db files is currently hardcoded into AdGuard Home.
See: https://github.com/AdguardTeam/AdGuardHome/blob/9389b087be6300a1a301c2eeb2ef1024675e4d9f/dhcpd/db.go#L17

<blockquote><img src="https://avatars1.githubusercontent.com/u/8361145?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/AdguardTeam/AdGuardHome">AdguardTeam/AdGuardHome</a></strong></div><div>Network-wide ads & trackers blocking DNS server. Contribute to AdguardTeam/AdGuardHome development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
Opened up an issue upstream: <https://github.com/AdguardTeam/AdGuardHome/issues/935>

**Comment by frenck** [comment]
The upstream issue has been fixed, will be part of AdGuard Home 0.98
