### ISSUE TITLE
AdGuard only working on a single device

### ISSUE THREAD

**Issue by Consille1** [hassio-addons/addon-adguard-home#318]
# Problem/Motivation

Adguard does not work on my laptop, but on my phone

## Expected behavior

It should work on every device

Setting my Win11 device to my RaspPi does not make a difference. But it states the correct DNS Address on ipconfig:
![DNSWin](https://user-images.githubusercontent.com/105976670/169652035-8b725b02-0e4a-4422-91aa-f5afb25c9bf3.png)

And these are the routers setting on my Phone, which is somehow working: 
![Pixel5](https://user-images.githubusercontent.com/105976670/169652038-bc8e1847-52e0-42e6-b87e-b71d9fa4a850.png)
I've tried an older LG V30 Android device and it does not work on this one. So no concistency os-wise.

This is my ipconfig file in Home Assistant:
![HAipconfig](https://user-images.githubusercontent.com/105976670/169652037-7be73c16-16b4-4420-a131-5c07402140cc.png)

For the sake of completeness my Router settings which are directing to my local Raspi DNS:
![Routerconfig](https://user-images.githubusercontent.com/105976670/169652039-245f9f54-f0f7-4d44-bde7-34f7e20716e1.png)

And lastly the log files of Adguard:

``
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.5.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.5.5
 Home Assistant Supervisor: 2022.05.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[12:35:04] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:35:08] INFO: Starting AdGuard Home server...
2022/05/21 12:35:09.170810 [info] AdGuard Home, version v0.107.6
2022/05/21 12:35:09.222370 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/05/21 12:35:09.225100 [info] auth: initialized.  users:0  sessions:0
2022/05/21 12:35:09.225231 [info] Initialize web module
2022/05/21 12:35:09.503476 [info] AdGuard Home is available at the following addresses:
2022/05/21 12:35:09.503585 [info] Go to http://127.0.0.1:45158
[12:35:09] INFO: Starting NGinx...
2022/05/21 12:35:12.108578 [info] Starting the DNS proxy server
2022/05/21 12:35:12.108639 [info] Ratelimit is enabled and set to 25 rps
2022/05/21 12:35:12.108651 [info] The server is configured to refuse ANY requests
2022/05/21 12:35:12.108664 [info] DNS cache is enabled
2022/05/21 12:35:12.108683 [info] MaxGoroutines is set to 300
2022/05/21 12:35:12.108721 [info] Creating the UDP server socket
2022/05/21 12:35:12.108930 [info] Listening to udp://192.168.0.3:53
2022/05/21 12:35:12.108953 [info] Creating the UDP server socket
2022/05/21 12:35:12.109048 [info] Listening to udp://172.30.32.1:53
2022/05/21 12:35:12.109065 [info] Creating a TCP server socket
2022/05/21 12:35:12.109178 [info] Listening to tcp://192.168.0.3:53
2022/05/21 12:35:12.109197 [info] Creating a TCP server socket
2022/05/21 12:35:12.109356 [info] Listening to tcp://172.30.32.1:53
2022/05/21 12:35:12.110288 [info] Entering the tcp listener loop on 172.30.32.1:53
2022/05/21 12:35:12.110837 [info] Entering the UDP listener loop on 192.168.0.3:53
2022/05/21 12:35:12.111468 [info] Entering the UDP listener loop on 172.30.32.1:53
2022/05/21 12:35:12.111929 [info] Entering the tcp listener loop on 192.168.0.3:53
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/ssl/fullchain.pem"
2022/05/21 12:57:40.431970 [error] handling tcp: unpacking msg: dns: overflow unpacking uint16
2022/05/21 12:58:51.596126 [error] responding udp request: writing message: write udp 192.168.0.3:53->172.30.32.3:40316: sendmsg: network is unreachable
2022/05/21 12:58:51.597549 [error] responding udp request: writing message: write udp 192.168.0.3:53->172.30.32.3:50558: sendmsg: network is unreachable
2022/05/21 12:58:51.598275 [error] responding udp request: writing message: write udp 192.168.0.3:53->172.30.32.3:55078: sendmsg: network is unreachable
2022/05/21 12:58:51.599129 [error] responding udp request: writing message: write udp 192.168.0.3:53->172.30.32.3:44234: sendmsg: network is unreachable
2022/05/21 12:58:51.601300 [error] responding udp request: writing message: write udp 192.168.0.3:53->172.30.32.3:40617: sendmsg: network is unreachable
2022/05/21 12:58:51.601885 [error] handling tcp: handling tcp request: talking to dns upstream: requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=gPoBIAABAAAAAAABB3ZlcnNpb24OaG9tZS1hc3Npc3RhbnQCaW8AABwAAQAAKQgAAACAAAAA": all dialers failed: 4 errors: "dial tcp 9.9.9.10:443: connect: network is unreachable", "dial tcp 149.112.112.10:443: connect: network is unreachable", "dial tcp [2620:fe::10]:443: connect: network is unreachable", "dial tcp [2620:fe::fe:10]:443: connect: network is unreachable"
2022/05/21 12:58:51.602376 [error] handling tcp: handling tcp request: talking to dns upstream: requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=WjABIAABAAAAAAABB3ZlcnNpb24OaG9tZS1hc3Npc3RhbnQCaW8AAAEAAQAAKQgAAACAAAAA": all dialers failed: 4 errors: "dial tcp 9.9.9.10:443: connect: network is unreachable", "dial tcp 149.112.112.10:443: connect: network is unreachable", "dial tcp [2620:fe::10]:443: connect: network is unreachable", "dial tcp [2620:fe::fe:10]:443: connect: network is unreachable"
2022/05/21 13:00:09.455442 [error] handling tcp: handling tcp request: talking to dns upstream: requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=p1sBIAABAAAAAAABB3ZlcnNpb24OaG9tZS1hc3Npc3RhbnQCaW8AABwAAQAAKQgAAACAAAAA": all dialers failed: 4 errors: "dial tcp 9.9.9.10:443: connect: no route to host", "dial tcp 149.112.112.10:443: i/o timeout", "dial tcp [2620:fe::10]:443: i/o timeout", "dial tcp [2620:fe::fe:10]:443: i/o timeout"
2022/05/21 13:00:12.457166 [error] handling tcp: handling tcp request: talking to dns upstream: failed to check host "time.cloudflare.com": safe browsing: requesting https://dns-family.adguard.com:443/dns-query: Get "https://dns-family.adguard.com:443/dns-query?dns=-LoBAAABAAAAAAAABDQ0NmUEMDY3YQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2022/05/21 13:03:21.633835 [error] unpacking udp packet: dns: buffer size too small
2022/05/21 13:03:24.540646 [error] unpacking udp packet: dns: buffer size too small``

I have roamed the internet for any clue, without a single answer, so any help would be greatly appreciated!

**Comment by sinclairpaul** [comment]
A couple of things:

Don't have the Home Assistant instance use itself for DNS, you will have issues, you need to use something else (which is likely the issues in the log).

Your Windows client has a secondary DNS server, it will be queried when Adguard responds with a "not known" message.

**Comment by Consille1** [comment]
Thanks man! Your help is appreciated. I have changed the dns settings on home assistant and the error logs got significantly shorter. But this part stuck:
`nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/ssl/fullchain.pem"
2022/05/21 17:33:59.444723 [error] handling tcp: handling tcp request: talking to dns upstream: failed to check host "time.cloudflare.com": safe browsing: requesting https://dns-family.adguard.com:443/dns-query: Get "https://dns-family.adguard.com:443/dns-query?dns=xZsBAAABAAAAAAAABDQ0NmUEMDY3YQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2022/05/21 17:34:21.937634 [error] handling tcp: handling tcp request: talking to dns upstream: failed to check host "version.home-assistant.io": safe browsing: requesting https://dns-family.adguard.com:443/dns-query: Get "https://dns-family.adguard.com:443/dns-query?dns=-GwBAAABAAAAAAAABGUyY2IEMTZlOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2022/05/21 18:16:30.926644 [info] Entering the UDP listener loop on 172.30.32.1:53
2022/05/21 18:16:30.927196 [info] Entering the tcp listener loop on 192.168.0.3:53
2022/05/21 18:16:30.927629 [info] Entering the tcp listener loop on 172.30.32.1:53
2022/05/21 18:16:30.927963 [info] Entering the UDP listener loop on 192.168.0.3:53`

Looks like it has to do something with my DNS settings in AdGuard. But changing them just gets different error results. Changing the windows dns settings back to automatic did not get any different results. And most sadly there is still no sign of live on my devices.

**Comment by sinclairpaul** [comment]
From looking at the logs again, it also appears you may have network configuration issues within HA.  I would suggest that you use a wired connection, and ensure only one interface has an address assigned.

**Comment by Consille1** [comment]
ok, thx. After spending so much time figuring out what is wrong I figuered that I just wipe clean my raspi and start anew with a backup. So whereever the error might have been, this solved it XD
Nevertheless thank you very much for your time! Really appreciated

**Comment by Consille1** [comment]
After struggeling to find the error I figured the less time consuming option at this point is to start anew with the most important data as a backup. So now it is working as it should be. So where ever the problem has been, deleting everything does seem to have deleted the problem as well XD
Nevertheless, thank you for your time. Really appreciated!
