### ISSUE TITLE
Restarting the addon deletes all dhcp leases 

### ISSUE THREAD

**Issue by tefinger** [hassio-addons/addon-adguard-home#33]
## Actual behavior

After restarting the addon all configured static and dynamic dhcp leases are gone.

## Expected behavior

Restarting the addon should not cause that dhcp leases get deleted.

## Steps to reproduce

- Add static dhcp leases
- Restart the addon
- Check dhcp leases again -> the list is empty

**Comment by tefinger** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/956

**Comment by allanpersson** [comment]
I have same issue, let me know if you need me to provide anything to solve the problem :)
