### ISSUE TITLE
4.7.0 update prevents addon to display running status !

### ISSUE THREAD

**Issue by vincegre** [hassio-addons/addon-adguard-home#331]
# Problem/Motivation

Using since a long time Adguard extension in HA. Worked fine till yesterday. After upgrade at 4.7.0 it's still running as it distributes IP in DHCP, but It appears as off in HA and can't start it, and if I want to acess GUI it says me addon is not started ! Logs of addon shows it's working !

## Expected behavior

Display proper running status and let me access GUI !

## Actual behavior

Can't start the addon in HA, nothing happens when I click start ! GUI not avalaible stating Adguard is not running, but DHCP feature still working as I can see in logs of addon !

## Steps to reproduce

Update to 4.7.0

Thanks

Vincèn

**Comment by frenck** [comment]
Unfortunately, this is an issue with the Home Assistant Supervisor or the Home Assistant Frontend, not an add-on issue.

Please report your issue with the Home Assistant project. From the add-on site of things, there is nothing I can do to fix this.

../Frenck

**Comment by vincegre** [comment]
> Unfortunately, this is an issue with the Home Assistant Supervisor or the Home Assistant Frontend, not an add-on issue.
> 
> Please report your issue with the Home Assistant project. From the add-on site of things, there is nothing I can do to fix this.

Thaks for your answer but it would affect only Adguard as all my others add-ons are working fine ??

**Comment by vincegre** [comment]
Additional details: I was previously running beta cthannel for HA but switched back at release channel, got the 2022.8.0 upgrade but problem still exactly the same :( So I think it's really a bug in the add-on !

**Comment by frenck** [comment]
> Thaks for your answer but it would affect only Adguard as all my others add-ons are working fine ??

It is outside of the add-on scope. From an add-on perspective, there is nothing I can do. Please report upstream as instructed. Thanks 👍

**Comment by gieljnssns** [comment]
I'm sorry to comment in this closed topic.
But I have the same problem, and when I restore a backup from 4.6.1 the add-on is working as expected
system:
## System Information

version | core-2022.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.55
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.26.2
Stage | running
Available Repositories | 1155
Downloaded Repositories | 36

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | beta
supervisor_version | supervisor-2022.08.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 457.7 GB
disk_used | 116.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), AdGuard Home (4.6.1), AppDaemon (0.9.2), Caddy (1.6), Check Home Assistant configuration (3.11.0), Duck DNS (1.15.0), ESPHome (2022.6.2), Mosquitto broker (6.1.2), Studio Code Server (5.2.0), WireGuard (0.7.0), MariaDB (2.5.1), SSH & Web Terminal (11.0.2), Glances (0.16.0), phpMyAdmin (0.8.1), Mealie (1.0.0.1-2), Arpspoof (1.0.0), Caddy 2 (1.2.2), RTSPtoWeb - WebRTC (1.2.2), EMHASS (0.2.19), Frigate NVR (Full Access) (3.1), Home Assistant Google Drive Backup (0.108.2), Syncthing (1.14.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 18
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 juli 2022 15:14
-- | --
current_recorder_run | 3 augustus 2022 18:04
estimated_db_size | 3864.05 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | -16
rooftop_site_count | 2
polling_hours | 6 -> 22 and once at midnight

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by frenck** [comment]
See above messages.

**Comment by vincegre** [comment]
@frenck no offense but I was already not convinced by your explanation and close of ticket but it confirms my feeling that problem was well in Adguard addon and not in supervisor ! What a surprise, the update in 4.7.1 of Adguard today has solved the issue.....

**Comment by frenck** [comment]
@vincegre No offense either, but I know the exact cause of the issue, and it's not an add-on issue. Even without upgrading, in your current instance, it may happen again (e.g., after a reboot of your system or when restarting the add-on).

**Comment by vincegre** [comment]
@frenck Thanks for the details but is there a way to do something on user side if problem occurs again ? as it's quite annoying or have to wait patiently that supervisor issue be fixed ? :/

**Comment by frenck** [comment]
> but is there a way to do something on user side if problem occurs again ? 

No, it is a bug upstream in the Home Assistant Supervisor, if you run into such an issue, please report it upstream as suggested above.
