### ISSUE TITLE
Adguard home fails to start, but not seeing any errors.

### ISSUE THREAD

**Issue by codex70** [hassio-addons/addon-adguard-home#334]
# Problem/Motivation

Adguard home fails to start

I am unable to get NAT Loopback working with my router. The DuckDNS address works from a remote location, but not locally.

## Expected behavior

Starts without problem

## Actual behavior

During startup, there are no errors in the logs, but the add on does not show as started and seems to hang when configuring nginx

The last entries in the logs are:
```
[06:49:22] INFO: Starting NGinx...
2022/08/15 06:49:22.824053 [info] saving filter 1 contents to: /data/adguard/data/filters/1.txt
2022/08/15 06:49:22.824354 [info] updated filter 1: 911832 bytes, 47055 rules
2022/08/15 06:49:22.824381 [info] Updated filter #1.  Rules: 0 -> 47055
```

There is nothing else showing in the homassistant.log file.

## Steps to reproduce

Raspberry PI running Home Assistant 2022.8.4, DuckDNS configuration.

IPV4 configuration static configuration set and port forwarding from my router 8123 to Home Assistant.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by codex70** [comment]
Output of `ha info`

```
arch: aarch64
channel: stable
docker: 20.10.14
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
- resolved
hassos: "8.4"
homeassistant: 2022.8.4
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 8.4
state: running
supervisor: 2022.08.3
supported: true
supported_arch:
- aarch64
- armv7
- armhf

```

**Comment by Toodrunkforthis** [comment]
I am having a similar problem. I can't start adguard and if I want to start it again it tells me it's already running.

**Comment by frenck** [comment]
Issue has been resolved in the latest version of the add-on
