### ISSUE TITLE
Unable to Access Webserver

### ISSUE THREAD

**Issue by theChef613** [hassio-addons/addon-adguard-home#337]
Hello,
I'm unable to access the adguard webUI after installation.
I am also using duckdns and am able to get to my configuration via my duckdns.org domain. 
the log repeats the same lines
`[22:18:00] INFO: Starting AdGuard Home server...
2022/08/17 22:18:00.382348 [info] AdGuard Home, version v0.107.10
2022/08/17 22:18:00.383281 [info] home.upgradeSchema0to1(): called
2022/08/17 22:18:00.383317 [info] deleting /data/adguard/dnsfilter.txt as we don't need it anymore
2022/08/17 22:18:00.383480 [info] home.upgradeSchema1to2(): called
2022/08/17 22:18:00.383497 [info] deleting /data/adguard/Corefile as we don't need it anymore
2022/08/17 22:18:00.383921 [info] home.upgradeSchema2to3(): called
2022/08/17 22:18:00.383955 [fatal] dns configuration is not a map`

I've also forwarded port 3000 on my router... I'm unsure what I'm doing wrong here... any help would be appreciated!
Thank you!

**Comment by stdevel** [comment]
Most likely referred to #336.

**Comment by frenck** [comment]
Issue has been resolved in the latest version of the add-on
