### ISSUE TITLE
Mobile filter

### ISSUE THREAD

**Issue by kevvar** [hassio-addons/addon-adguard-home#352]
Hi.

I'm been using the addon recently, I've noticed although my pc blocks every popup and others adds, on my mobile devices (android using different browsers) some times I see popups and adds. I have setup adguard on my router through dhcp/dns, all things are working well, I can see metrics on the dashboard, but as I said my mobile devices doesn't block 100% of the ads and popups. Any advice?

**Comment by frenck** [comment]
> Any advice?

Not really. If you have questions about AdGuard itself, it is probably better to look for answers in the resources the AdGuard Home team provides.

../Frenck

**Comment by kevvar** [comment]
Thanks @frenck think I fixed, I had custom secure DNS activated on chrome setup, when I turned off, adguard worked

**Comment by frenck** [comment]
Good to hear 👍 

../Frenck
