### ISSUE TITLE
AdGuard Home DNS server 127.0.0.1 only available 

### ISSUE THREAD

**Issue by tomi19921702** [hassio-addons/addon-adguard-home#355]
# Problem/Motivation

> Couldn't set DNS server to 127.0.0.1 that was the only Ip shown in the setup guide also tried the HA IP.

## Expected behavior

>

## Actual behavior

> Couldn't connect to DNS

## Steps to reproduce

> I Just freshly installed AdGuard on HA.

## Proposed changes

> Found on Reddit the info to add the bind_hosts:
  - 192.0.0.0 
  Function and added to the yaml manually.
And it worked afterwards.

**Comment by frenck** [comment]
I'm  not sure what to do with this issue, could you provide logs? Screenshots or something else?

The proposed change is not entirely clear to me, as there is no YAML involved in this process.

**Comment by avlemos** [comment]
trying to understand this bit of cryptic issue report, first time I installed AH as well, I had to specify to what IP address I wanted it to bind, as it was only biding to 127.0.0.1 by default (this is from memory, I haven't had this issue since).

**Comment by frenck** [comment]
> I had to specify to what IP address I wanted it to bind, as it was only biding to 127.0.0.1 by default 

That is not correct. The add-on binds to all public-facing addresses managed by the Supervisor. The add-on requests the Supervisor for those.

**Comment by avlemos** [comment]
well, fact of the matter is, when I did the first install, I did had to specify it. thinking this is what this person experienced as well, judging by the bind_hosts configuration parameter.

(I don't have this issue anymore, just thought I'd weigh in)

**Comment by frenck** [comment]
>  I did had to specify it. 

No. You should not. The fact you did it is working around it? There is no user configuration option for it. It asks the supervisor for the available interfaces it manages and binds to it.

**Comment by avlemos** [comment]
what can I tell you? maybe something failed with the supervisor, because it definitely wasn't working, so I resorted to the manual Yaml configuration route thingy.

I'm happy, no beef here. Just trying to get ahead on what @tomi19921702 meant.

**Comment by frenck** [comment]
< so I resorted to the manual Yaml configuration route thingy

That is up to you, that is not how it should have been solved or how it should have been done. Those files are managed, poking around in those manually isn't supported.

Closing the issue on this end, as this is going nowhere.

../Frenck
