### ISSUE TITLE
Cannot start the addon

### ISSUE THREAD

**Issue by PolestarWx** [hassio-addons/addon-adguard-home#362]
# Problem/Motivation

`500 Server Error for http+docker://localhost/v1.41/containers/addon_a0d7b954_adguard/json: Internal Server Error ("stat /mnt/data/docker/overlay2/fef5d9cfe7ce77cc74663269ad4427fef49d4a454e82ad2427575b4642054428: no such file or directory")`

## Expected behavior

Start

## Actual behavior

Cannot start due to error

## Steps to reproduce

I have installed this addon long time ago, reinstalled it and nothing changed

**Comment by frenck** [comment]
This is not an add-on issue (as the add-on didn't start even at this point). Please report your issue with the Home Assistant Supervisor project instead.

Thanks 👍 

../Frenck
