### ISSUE TITLE
Blocked Services - not working for Whatsapp/Facebook/Youtube etc. apps

### ISSUE THREAD

**Issue by almostserious** [hassio-addons/addon-adguard-home#37]
# Problem/Motivation

When i block the services of Facebook, Whatsapp, Instagram, Youtube the apps on Android Phone still work fine.
The Websites are blocked, but the apps somehow circumvent this.
## Expected behavior

If i block Netflix, the Netflix App does not work anymore. I would expect the same also for the other apps. Is there a way to make this work? Do i need to enable a specific setting for them?

**Comment by sinclairpaul** [comment]
As this is specific to the application you would need to log this at the Adguard Home repo.

https://github.com/AdguardTeam/AdGuardHome
