### ISSUE TITLE
parental, safebrowsing and safesearch not working

### ISSUE THREAD

**Issue by derwotograf** [hassio-addons/addon-adguard-home#370]
# Problem/Motivation

I'm having issues for parental, safebrowsing and safesearch.

from the log
```
/control/parental/enable: only content-type application/json is allowed
control/safebrowsing/enable: empty body with content-type "application/octet-stream" not allowed
/control/parental/enable: empty body with content-type "application/octet-stream" not allowed
/control/safesearch/enable: empty body with content-type "application/octet-stream" not allowed
```

## Actual behavior

message which appears in the frontend when trying to set functions to on:
`Error: control/safebrowsing/enable | empty body with content-type "application/octet-stream" not allowed | 415`

I'm running AdGuard as Add-on in Home Assistant.

Filtering is turned on and working. For testing I'm afraid to turn it of because it might not let me turn it back on again.

_Originally posted by @derwotograf in https://github.com/AdguardTeam/AdGuardHome/issues/5210#issuecomment-1336171401_

**Comment by GoetzGoerisch** [comment]
Upstream was fixed with 0.107.15 https://github.com/AdguardTeam/AdGuardHome/issues/4970 
Not shure why it is still showing up.

@AlecRust  can we get a new release with upstream 0.107.19 please?

**Comment by AlecRust** [comment]
I don't make releases of this add-on, I just provide some version bump PRs here and there.

**Comment by frenck** [comment]
Closing as a duplicate
