### ISSUE TITLE
HA shows average_processing_speed in seconds

### ISSUE THREAD

**Issue by kreisklasse** [hassio-addons/addon-adguard-home#38]
# Problem/Motivation

>
Since update to HA 0.101.0 and Ad-Guard-Addon from 2.1 to 2.2.3
HomeAssistant shows the _"sensor.adguard_average_processing_speed"_ now in seconds,
not millisesconds anymore.
Adguard-addon displays it still in "msec".

Don't know if the add-on transfers a wrong value to HA or HA recalculates it to seconds by its own,
so i post the report here first. 

## Expected behavior

> show _"sensor.adguard_average_processing_speed"_ in milliseconds again

## Actual behavior

> _"sensor.adguard_average_processing_speed"_ shows value in seconds

## Steps to reproduce

> RaspberryPi 2
HAssIO Supervisor : 192
HassOS : 2.12
Home-Assistant : 0.101.0 and 0.101.1
AdGuard-Addon : 2.2.3

## Screenshots
Graph shows values prior update and afterwards.
According to AdGuard-addon processing speed is between 30 and 40 msec.

![Screenshot_2019-11-01 Home Assistant](https://user-images.githubusercontent.com/25295915/68032917-ece61c00-fcbe-11e9-877b-9bd9fb695633.png)
![Screenshot_2019-11-01 Home Assistant(1)](https://user-images.githubusercontent.com/25295915/68032922-efe10c80-fcbe-11e9-9f5d-710b635478c1.png)

**Comment by frenck** [comment]
This is the add-on repository, please open up an issue @ https://github.com/home-assistant/home-assistant

Thanks! 👍

**Comment by kreisklasse** [comment]
Yeah, what should i say ... closed here, closed there ...
https://github.com/home-assistant/home-assistant/issues/28437#issuecomment-548828807
