### ISSUE TITLE
update not working Version: v0.107.17

### ISSUE THREAD

**Issue by Liftboy222** [hassio-addons/addon-adguard-home#380]
# Problem/Motivation

>Since version: v0.107.17 there are no more updates from the plugin Adguard under homeassistent.
Plugin adguard version is: 4.7.5

## Expected behavior

> updates ;)

## Actual behavior

> automatic updates ist selected in the plugin settings

## Steps to reproduce

> 

## Proposed changes

I had read somewhere that there are problems with the Since version: v0.107.17 update. Would a solution for beginners be to make a complete backup of homeassisten, uninstall the plugin adguard and install the current version? Then restore the backup of homeassistent and all settings are back?

**Comment by frenck** [comment]
The latest version of the add-on is v4.7.6:

https://github.com/hassio-addons/addon-adguard-home/releases/tag/v4.7.6

Which version are you running?

../Frenck

**Comment by Liftboy222** [comment]
Current version: 4.7.5

**Comment by AlecRust** [comment]
https://github.com/hassio-addons/addon-adguard-home/discussions/379#discussioncomment-4503092

**Comment by frenck** [comment]
Good call @AlecRust 👍 

I've re-deployed v4.7.6

../Frenck
