### ISSUE TITLE
Adguard hassio add-on does not start due to port 53 bind failing

### ISSUE THREAD

**Issue by JanMR21** [hassio-addons/addon-adguard-home#381]
# Problem/Motivation

Adguard hassio add-on does not start due to port 53 bind failing

## Expected behavior

as i have no other service running using that port the add on should start

## Actual behavior

2022/12/29 01:13:53.245416 [info] dnsproxy: cache: enabled, size 4194304 b
2022/12/29 01:13:53.245453 [info] MaxGoroutines is set to 300
2022/12/29 01:13:53.245493 [info] Creating the UDP server socket
2022/12/29 01:13:53.245741 [info] Listening to udp://192.168.68.122:53
2022/12/29 01:13:53.245777 [info] Creating the UDP server socket
2022/12/29 01:13:53.254223 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 192.168.68.122:53: bind: address already in use

## Steps to reproduce

This happens to me after installing version:
AdGuard Home
Current version: 4.7.6 
of the add on home assistant running on latest version of hassio os
Home Assistant 2022.12.8 Supervisor 2022.12.1 
Operating System 9.4 Frontend 20221213.1 - latest 

while:

![image](https://user-images.githubusercontent.com/103334956/209887783-9f29ea75-4e70-4b1d-a0ae-2666f84151fc.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> 2022/12/29 01:13:53.254223 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 192.168.68.122:53: bind: address already in use

There is not much I can do from an add-on perspective. It means you are already running something that takes up that port. Free up the port if you'd like to use AdGuard Home instead.

../Frenck

**Comment by JanMR21** [comment]
Hei,

Point is that the port was actually not in use as the screenshot suggests…

Eventually hassio freed it after a couple of times rebooting… but i have no other service or addon using it. I m pretty sure of that…

So i think there maybe is an issue on the hassio level blocking the port… which then affects adguard..

Jan

On 2 Jan 2023, at 13:43, Franck Nijhof ***@***.***> wrote:

﻿

Closed #381<https://github.com/hassio-addons/addon-adguard-home/issues/381> as not planned.

**Comment by frenck** [comment]
@JanMR21 That makes no sense, as you scan TCP use of port 53, which is not used by DNS.

**Comment by tannertechnology** [comment]
This has been an ongoing issue for months, if the issue isn't with this addon it is with HassOS so I suppose we should open an issue there. See issue #298
