### ISSUE TITLE
request login password when I access adguard with my domain name

### ISSUE THREAD

**Issue by thetux07** [hassio-addons/addon-adguard-home#386]
hello
with the last version of addon,request login password when I access adguard with my domain name, when I access it locally (http://ip:8123)... it's ok
do you have an idea ?
thank you

**Comment by frenck** [comment]
When accessing the AdGuard Home interface directly (bypassing the Home Assistant Ingress feature), you need to login in with your Home Assistant credentials.

![CleanShot 2023-01-23 at 12 51 01](https://user-images.githubusercontent.com/195327/214032902-6848fe34-4010-41b7-b01e-eb8ba5fa8aa1.png)

**Comment by thetux07** [comment]
Ok but when i login with ingress with my domain name it don’t work to 
But with my local ip it’s ok

**Comment by thetux07** [comment]
When i look in My config file the param user is 
User: [] 
It’s ok that ?
Thank tou
