### ISSUE TITLE
Add extra switches to hass for blocking services. 

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/addon-adguard-home#39]
# Problem/Motivation
Is it possible to add these switches to hass so I can use them in an automation. 
![61A9B5EA-66FE-41B2-A8C3-BB5C77C3DE40](https://user-images.githubusercontent.com/17234951/68222625-9264fc80-ffeb-11e9-880d-800dbdf346ac.png)

**Comment by frenck** [comment]
This repository is for the add-on, not for Home Assistant or the integration.

If you have feature requests for Home Assistant, please open one up on the Home Assistant Community Forum.

Thanks! 👍
