### ISSUE TITLE
Add-on not using the latest filter list

### ISSUE THREAD

**Issue by Intecpsp** [hassio-addons/addon-adguard-home#392]
# Problem/Motivation

> I've been following https://github.com/AdguardTeam/HostlistsRegistry and have seen movement on the supplied filter list for the application. After doing some research I see that "[Starting with AdGuard Home 0.107.17, AdGuard Home will use the Hostlists Registry as the source of its filtering rule lists.](https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-1287199690)". The current version inside this add-on is [v0.107.22](https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/Dockerfile#L24), so it should be using this list, correct? I ask because Energized Spark was [removed](https://github.com/AdguardTeam/HostlistsRegistry/pull/141), but I still see it as an option in the UI. 
![Screenshot 2023-02-20 at 8 20 36 AM](https://user-images.githubusercontent.com/1164012/220120016-da285799-6da2-4b8f-be34-c577f6dd2cb1.jpg)
Other things have been added as well, but this one has been gone for a bit, so I chose it to be the example.

> This may be an issue on the add-on side or the official app side. But I'd assume that running just the official app is working as intended and the filters are pulling correctly. So I wanted to start with this specific implementation, then if it's deemed not an issue that can be corrected here, to go to the [AdGuardHome](https://github.com/AdguardTeam/AdGuardHome) side.

## Expected behavior

> The list in the UI stays in sync with https://adguardteam.github.io/HostlistsRegistry/assets/filters.json

## Actual behavior

> The list is not staying in sync with the official list

## Steps to reproduce

> Running the app and going to Filters > DNS blocklists > Add blocklist > Choose from the list

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on doesn't set or do anything with block lists. Nothing in this issue report is related to the add-on itself.

../Frenck

**Comment by frenck** [comment]
I answered that above.
