### ISSUE TITLE
Link-local addresses not bound

### ISSUE THREAD

**Issue by jherby2k** [hassio-addons/addon-adguard-home#394]
# Problem/Motivation

Not binding to link-local addresses

## Expected behavior

Should be able to do a DNS query against home assistant's link-local IPv6 address (fe80::/10).

## Actual behavior

DNS query fails.

## Steps to reproduce

nslookup <ha's link-local IPv6 address> google.com

## Proposed changes

I'm not sure why this code is present in https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/rootfs/etc/s6-overlay/s6-rc.d/init-adguard/run. Why can't we do DNS queries to the local link-local address?

```
      # fe80::/10 according to RFC 4193 -> Local link. Skip it
      if (( (fd == 254) && ( (a2 & 192) == 128) )); then
        continue
      fi
    else
      # IPv4
      part="${host%%.*}"

      # 169.254.0.0/16 according to RFC 3927 -> Local link. Skip it
      if (( part == 169 )); then
        continue
      fi
    fi
```

## Rationale

My HA has both a prefix-delegated global IPv6 address and a link-local address. Unfortunately, sometimes my ISP changes our prefix without warning, causing my SLAAC and DHCPv6-assigned addresses to change. HA of course is statically configured as per the Adguard guide. This means our DNS server becomes unreachable, breaking all sorts of stuff. If Adguard was running on the link-local address as well, we'd still be able to do lookups from the router and/or local network.

**Comment by punkidow** [comment]
Still facing this issue.
Trying to bind to the link-local IPv6 address fails and calls it an invalid argument.
