### ISSUE TITLE
switch.adguard_home_parental_control toggle does not turn back on

### ISSUE THREAD

**Issue by h3llrais3r** [hassio-addons/addon-adguard-home#396]
# Problem/Motivation

switch.adguard_home_parental_control only toggles off.
Toggle on does not work, and remains on.
Only when going inside adguard dashboard I can turn back the parental control on via the settings.

## Expected behavior

Toggle switches parental control on and off.

## Actual behavior

Toggle only works for turning it off.
When toggling it again to on, it switches back to off, as the value is not updated.

## Steps to reproduce

Put switch on home screen.
Toggle it off.
Toggle it back on.
It automatically turns back off.

![image](https://user-images.githubusercontent.com/1945295/222803210-bce24a4e-64cd-4d07-a8a2-d0eaa3396526.png)

PS: other toggles work fine

**Comment by frenck** [comment]
That looks like the Home Assistant integration, however, this is the add-on. Those are not the same things.

../Frenck

**Comment by h3llrais3r** [comment]
Oh, you are right... I forgot I added the integration as well in order to get these switches.
Will raise issue in integration. Thx!
