### ISSUE TITLE
[2.2.3] Wrong value shown by sensor.adguard_average_processing_speed

### ISSUE THREAD

**Issue by dhzl84** [hassio-addons/addon-adguard-home#40]
# Problem/Motivation
Wrong value shown by sensor.adguard_average_processing_speed.

## Expected behavior
sensor.adguard_average_processing_speed shows the same value as "Average processing time" in the AdGuard UI.

## Actual behavior
sensor.adguard_average_processing_speed constantly shows 0.01 ms.
The AdGuard UI shows 8 ms for "Average processing time".

### Update
sensor.adguard_average_processing_speed seems to show seconds instead of milliseconds.
sensor.adguard_average_processing_speed now shows 0.03 ms while the AdGuard UI shows 30 ms.

## Steps to reproduce
Probably compare 2.1.0 against 2.2.x since this is when the misbehavior started for me.

## Proposed changes
Change scaling or unit of sensor.adguard_average_processing_speed 

## Additional information
Hass.IO 0.101.3 in Docker in Ubuntu on NUC8I3.
Neither restarting the AddOn nor Hass.IO fixes the issue.

**Comment by frenck** [comment]
This is the repository for the add-on, not the integration.

For the upstream issue see: <https://github.com/home-assistant/home-assistant/issues/28437>
