### ISSUE TITLE
adguard not start

### ISSUE THREAD

**Issue by brunokelo** [hassio-addons/addon-adguard-home#408]
Hello, I have a problem with my adguard, it just doesn't start, here's the error log.

Has anyone had this error?

Thanks,

 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.8.3
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-adguard: starting
[21:37:02] DEBUG: Requested API resource: http://supervisor/network/info
[21:37:02] DEBUG: Request method: GET
[21:37:02] DEBUG: Request data: {}
[21:37:02] DEBUG: API HTTP Response code: 200
[21:37:02] DEBUG: API Response: {"result": "ok", "data": {"interfaces": [{"interface": "ens192", "type": "ethernet", "enabled": true, "connected": true, "primary": true, "ipv4": {"method": "static", "address": ["192.168.0.30/24"], "nameservers": ["8.8.8.8"], "gateway": "192.168.0.1", "ready": true}, "ipv6": {"method": "disabled", "address": [], "nameservers": [], "gateway": null, "ready": true}, "wifi": null, "vlan": null}], "docker": {"interface": "hassio", "address": "172.30.32.0/23", "gateway": "172.30.32.1", "dns": "172.30.32.3"}, "host_internet": null, "supervisor_internet": true}}
s6-rc: info: service init-nginx successfully started
[21:37:02] DEBUG: Requested API resource: http://supervisor/network/interface/ens192/info
[21:37:02] DEBUG: Request method: GET
[21:37:02] DEBUG: Request data: {}
[21:37:02] DEBUG: API HTTP Response code: 200
[21:37:02] DEBUG: API Response: {"result": "ok", "data": {"interface": "ens192", "type": "ethernet", "enabled": true, "connected": true, "primary": true, "ipv4": {"method": "static", "address": ["192.168.0.30/24"], "nameservers": ["8.8.8.8"], "gateway": "192.168.0.1", "ready": true}, "ipv6": {"method": "disabled", "address": [], "nameservers": [], "gateway": null, "ready": true}, "wifi": null, "vlan": null}}
s6-rc: info: service init-adguard successfully started
s6-rc: info: service adguard: starting
[21:37:02] INFO: Starting AdGuard Home server...
2023/04/02 21:37:03.005061 [info] AdGuard Home, version v0.107.26
2023/04/02 21:37:03.005116 [info] AdGuard Home updates are disabled
2023/04/02 21:37:03.007090 [info] tls: using default ciphers
s6-rc: info: service adguard successfully started
2023/04/02 21:37:03.069608 [info] Initializing auth module: /data/adguard/data/sessions.db
2023/04/02 21:37:03.069922 [info] auth: initialized.  users:0  sessions:0
2023/04/02 21:37:03.069943 [info] web: initializing
s6-rc: info: service discovery: starting
s6-rc: info: service nginx: starting
2023/04/02 21:37:03.089843 [info] dnsproxy: cache: enabled, size 4096 b
2023/04/02 21:37:03.089860 [info] MaxGoroutines is set to 300
2023/04/02 21:37:03.090122 [info] AdGuard Home is available at the following addresses:
2023/04/02 21:37:03.090141 [info] go to http://127.0.0.1:45158
[21:37:03] INFO: Starting NGinx...
s6-rc: info: service nginx successfully started
[21:37:03] DEBUG: Requested API resource: http://supervisor/discovery
[21:37:03] DEBUG: Request method: POST
[21:37:03] DEBUG: Request data: {"service":"adguard","config":{"host":"127.0.0.1","port":45158}}
[21:37:03] DEBUG: API HTTP Response code: 200
[21:37:03] DEBUG: API Response: {"result": "ok", "data": {"uuid": "a5ac7f333d594645832b98499304cac0"}}
[21:37:03] DEBUG: Filtering response using: .uuid
[21:37:03] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
2023/04/02 21:37:03.596675 [info] Starting the DNS proxy server
2023/04/02 21:37:03.596753 [info] Ratelimit is enabled and set to 20 rps
2023/04/02 21:37:03.596757 [info] The server is configured to refuse ANY requests
2023/04/02 21:37:03.596761 [info] dnsproxy: cache: enabled, size 4194304 b
2023/04/02 21:37:03.596768 [info] MaxGoroutines is set to 300
2023/04/02 21:37:03.596790 [info] Creating the UDP server socket
2023/04/02 21:37:03.596877 [info] Listening to udp://192.168.0.30:53
2023/04/02 21:37:03.596887 [info] Creating the UDP server socket
2023/04/02 21:37:03.661327 [info] Listening to udp://172.30.32.1:53
2023/04/02 21:37:03.661346 [info] Creating the UDP server socket
2023/04/02 21:37:03.661367 [info] Listening to udp://127.0.0.1:53
2023/04/02 21:37:03.661370 [info] Creating the UDP server socket
2023/04/02 21:37:03.729407 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [::1]:53: bind: cannot assign requested address
s6-rc: info: service legacy-services successfully started
[21:37:03] INFO: Service Adguard Home exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service discovery: stopping
s6-rc: info: service nginx: stopping
s6-rc: info: service discovery successfully stopped
[21:37:04] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service adguard: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service adguard successfully stopped
s6-rc: info: service init-adguard: stopping
s6-rc: info: service init-adguard successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by sinclairpaul** [comment]
```2023/04/02 21:37:03.729407 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [::1]:53: bind: cannot assign requested address```

Make sure your OS "System: Debian GNU/Linux 11 (bullseye) (amd64 / qemux86-64)" isn't listening on the same port.

**Comment by brunokelo** [comment]
Hello, I tested using another port and still the same error,
it tries to list something with ipv6, even with ipv6 disabled,

2023/04/02 22:17:28.576600 [info] Listening to udp://192.168.0.30:55
2023/04/02 22:17:28.576606 [info] Creating the UDP server socket
2023/04/02 22:17:28.576705 [info] Listening to udp://172.30.32.1:55
2023/04/02 22:17:28.576711 [info] Creating the UDP server socket
2023/04/02 22:17:28.576763 [info] Listening to udp://127.0.0.1:55
2023/04/02 22:17:28.576769 [info] Creating the UDP server socket
2023/04/02 22:17:28.606925 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [::1]:55: bind: cannot assign requested address
[22:17:28] DEBUG: Requested API resource: http://supervisor/discovery
[22:17:28] DEBUG: Request method: POST
[22:17:28] DEBUG: Request data: {"service":"adguard","config":{"host":"127.0.0.1","port":45158}}
[22:17:28] DEBUG: API HTTP Response code: 200
[22:17:28] DEBUG: API Response: {"result": "ok", "data": {"uuid": "a5ac7f333d594645832b98499304cac0"}}
[22:17:28] INFO: Service Adguard Home exited with code 1 (by signal 0)
[22:17:28] DEBUG: Filtering response using: .uuid
[22:17:28] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service discovery: stopping
s6-rc: info: service nginx: stopping
s6-rc: info: service discovery successfully stopped
[22:17:29] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service adguard: stopping
s6-rc: info: service adguard successfully stopped
s6-rc: info: service init-adguard: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service init-adguard successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by brunokelo** [comment]
root@hass:/home/bruno# netstat -tulpn | grep LISTEN 
tcp        0      0 0.0.0.0:5050            0.0.0.0:*               LISTEN      6527/docker-proxy   
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      9038/python3        
tcp        0      0 0.0.0.0:1627            0.0.0.0:*               LISTEN      6282/docker-proxy   
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      4283/docker-proxy   
tcp        0      0 0.0.0.0:3005            0.0.0.0:*               LISTEN      5108/docker-proxy   
tcp        0      0 192.168.0.30:445        0.0.0.0:*               LISTEN      4896/smbd           
tcp        0      0 0.0.0.0:3551            0.0.0.0:*               LISTEN      713/apcupsd         
tcp        0      0 192.168.0.30:40000      0.0.0.0:*               LISTEN      9038/python3        
tcp        0      0 0.0.0.0:8324            0.0.0.0:*               LISTEN      5083/docker-proxy   
tcp        0      0 0.0.0.0:6789            0.0.0.0:*               LISTEN      4334/docker-proxy   
tcp        0      0 0.0.0.0:4357            0.0.0.0:*               LISTEN      1495/docker-proxy   
tcp        0      0 127.0.0.1:47079         0.0.0.0:*               LISTEN      9038/python3        
tcp        0      0 192.168.0.30:45897      0.0.0.0:*               LISTEN      9038/python3        
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      3403/docker-proxy   
tcp        0      0 192.168.0.30:139        0.0.0.0:*               LISTEN      4896/smbd           
tcp        0      0 0.0.0.0:8843            0.0.0.0:*               LISTEN      4263/docker-proxy   
tcp        0      0 0.0.0.0:32400           0.0.0.0:*               LISTEN      5058/docker-proxy   
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      4309/docker-proxy   
tcp        0      0 0.0.0.0:8880            0.0.0.0:*               LISTEN      4238/docker-proxy   
tcp        0      0 192.168.0.30:51828      0.0.0.0:*               LISTEN      9038/python3        
tcp        0      0 0.0.0.0:32469           0.0.0.0:*               LISTEN      4944/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      648/sshd: /usr/sbin
