### ISSUE TITLE
Parental Control can't be switched on again, if turned of via Home Assistant

### ISSUE THREAD

**Issue by outrun0506** [hassio-addons/addon-adguard-home#413]
# Problem/Motivation
If Parental Control is turned off via Home Assistant Switch, it can't be turned on again, via the Switch. Enable the Service in AD-Guard Dashboard works fine.

## Steps to reproduce
Switch of switch.adguard_parental_control and then try to turn it on again.

This is written in Log if I try to turn on the service again:
2023/04/13 11:49:17.882674 [error] POST 127.0.0.1:45158 /control/parental/enable: only content-type application/json is allowed.

**Comment by frenck** [comment]
This is not an add-on issue, but an integration issue. You are in the wrong place.

../Frenck
