### ISSUE TITLE
AdGuard filters Docker Network

### ISSUE THREAD

**Issue by kenhoppla** [hassio-addons/addon-adguard-home#424]
I'm hosting AdGuard in my HomeAssistantOS and just noticed that AdGuard is filtering the IP 172.30.32.3 which I think is my internal Docker-Network. All the traffic in HAOS is filtered right now. How can I turn it off?

**Comment by sinclairpaul** [comment]
Not sure of the issue here, that's a host not a network.

Maybe you could note which issue you are facing?  Adguard is a DNS server, so responds to the queries it receives from the configured hosts.

**Comment by kenhoppla** [comment]
Sorry for the confusion. AdGuard started scanning the Host 172.30.32.3 which ist HomeAssistant with all Docker-Containers. I just don't understand why. Why should it scan the own host and create thousands of unnecessary logs? Is it a new feature and can I turn it off?

**Comment by sinclairpaul** [comment]
Adguard is a DNS server, it doesn't scan, but responds to the clients configured to use it.  If you are seeing the Docker Network hosts referencing it, I would suggest looking at the DNS settings controlled by the Supervisor (and configured in the HA UI).

**Comment by frenck** [comment]
Sounds like you've skipped the very first step of the installation documentation:

<https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/DOCS.md#installation>

../Frenck

**Comment by kenhoppla** [comment]
Thanks for your help guys!

Just checked my Network-Settings. HomeAssistant is set to static with the DNS 1.1.1.1. Still AdGuard filters the traffic of my Docker-Containers.

**Comment by frenck** [comment]
Then I'm afraid we can't help you 🤷 

Something is routing it through it, we don't control that.

../Frenck

**Comment by kenhoppla** [comment]
Do you possibly have any idea what it could be due to? Last things I installed were Glances and Portainer. Didn't change any settings in them.

**Comment by frenck** [comment]
> Do you possibly have any idea what it could be due to?

Sorry, I wish I had a better suggestion for you.

../Frenck
