### ISSUE TITLE
DNS broken after upgrade to 4.8.9

### ISSUE THREAD

**Issue by Nbr1Sniper** [hassio-addons/addon-adguard-home#427]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Similar to issue #425 my dns keeps dropping on 4.8.9 which is the latest update. Please help!

**Comment by sysofwan** [comment]
Same here, DNS super unstable after update. I suspect it's related to this: https://github.com/AdguardTeam/AdGuardHome/issues/5878

**Comment by Nbr1Sniper** [comment]
I installed adguard on my unraid server. No issues. It actually cleared up another network issue I had (even though I used the exact same settings)

**Comment by LeandroIssa** [comment]
Same here, 4.8.9 didn't solve the problem.

**Comment by LeandroIssa** [comment]
Still having the same problem even with version 4.8.10

**Comment by peter1960** [comment]
Same here, I had to turn it off as so unreliable

**Comment by dm82m** [comment]
same problem with 4.8.10 and stopped using it

**Comment by joskfg** [comment]
Same problem here

**Comment by dnedeltchev** [comment]
same problem. I went back to 4.8.7 and it's stable

**Comment by dm82m** [comment]
Anyone tested with 4.8.11?

**Comment by dnedeltchev** [comment]
> Anyone tested with 4.8.11?

I just upgraded but it usually takes a couple of days for me to experience the broken DNS issue. I was also getting high memory utilisation after I upgraded from 4.8.7. I have a memory monitor and was getting constant alerts from hitting the threshold. 4.8.7 had no such issues. The memory issues was very quick to manifest itself usually after a few hours. I will report whatever happens.

**Comment by dm82m** [comment]
thank you @dnedeltchev for beeing the tester for it! :)

**Comment by dnedeltchev** [comment]
I upgraded yesterday and so far no issues. Also my high memory utilisation issue has not appeared.

**Comment by dm82m** [comment]
> I upgraded yesterday and so far no issues. Also my high memory utilisation issue has not appeared.

Works for me aswell since 2 or 3 days with 4.8.11

**Comment by dnedeltchev** [comment]
I didn't see anything specific in the release notes about this issue. Unless upgrading those components did the trick...

**Comment by dnedeltchev** [comment]
I'm afraid I went back to 4.8.7. Although it didn't stop working, the memory utilisation has been atrocious. It was not as bad as 4.8.10 where it was hovering around 900mb but 720mb is not normal. Now on 4.8.7 it sitting at 120mb. I'm not sure what's going on so for now it's going to be 4.8.7.

**Comment by dm82m** [comment]
never had the issue with memory or at least didnt recognize it, I am on 182M with 4.8.11 and all is good since couple of days now...

**Comment by dnedeltchev** [comment]
Ha, guess what just happened. DNS stopped working with errors about not being able to write to the lease table db. I'm now back on 4.8.11. I've no idea what's going on anymore!

**Comment by Nbr1Sniper** [comment]
> Ha, guess what just happened. DNS stopped working with errors about not being able to write to the lease table db. I'm now back on 4.8.11. I've no idea what's going on anymore!

I’ve moved to running it on Unraid and haven’t had any issues. The HA version is not reliable enough for me.

**Comment by dnedeltchev** [comment]
I need to also consider other options...

**Comment by tommarparen** [comment]
Problem still exist in 4.8.12.
