### ISSUE TITLE
127.0.0.1:53: bind: address already in use

### ISSUE THREAD

**Issue by axute** [hassio-addons/addon-adguard-home#432]
https://github.com/hassio-addons/addon-adguard-home/blob/74d58b1a3f4829622ffc281432c73dd3a6b5d89e/adguard/rootfs/etc/s6-overlay/s6-rc.d/init-adguard/run#LL60C1-L62C1

This doesn't work with the latest image.

`2023/06/19 12:01:21.885054 [fatal] couldn't start forwarding DNS server: starting listeners: listening on udp addr 127.0.0.1:53: listening to udp socket: listen udp 127.0.0.1:53: bind: address already in use`

This is the local ip address of the container...

**Comment by frenck** [comment]
You can change the port in the add-on settings if you like; or free up the port.

These are both end-user choices, and not issues.

../Frenck

**Comment by axute** [comment]
How can I free up the port? It's from the docker image.
Why are the lines added when all the interfaces are appended?

**Comment by frenck** [comment]
> How can I free up the port? 

It is your system. I cannot answer that.

>  It's from the docker image.

Add-on you mean? You should not be using this directly in Docker.

> Why are the lines added when all the interfaces are appended?

I'm not following that question.

../Frenck

**Comment by axute** [comment]
okay thanks, found the container that is blocking the port.
Sorry, I thought that's the container itself, I didn't see that it was tied to the host network.

**Comment by axute** [comment]
Just for history reasons: https://github.com/lfarkas/addon-netbird/issues/14
