### ISSUE TITLE
Reopen #385

### ISSUE THREAD

**Issue by surak** [hassio-addons/addon-adguard-home#434]
Issue #385 is still around, it should be reopened and fixed

**Comment by frenck** [comment]
It was closed stale. Nobody confirmed it still being there. 

../Frenck

**Comment by surak** [comment]
Well, I can confirm!

**Comment by KruseLuds** [comment]
Surak, [this](https://github.com/hassio-addons/addon-adguard-home/issues/385#issuecomment-1440825645) resolved the issue for me. Please recheck those instructions very carefully, they were worth their weight in gold for me as they resolved the issue - and I believe it wil resolve it for you as well. Did you try it?
