### ISSUE TITLE
Encryption settings not working

### ISSUE THREAD

**Issue by mdegat01** [hassio-addons/addon-adguard-home#44]
# Problem/Motivation

I wanted to set up adguard to be my dns resolver anywhere, not just my local instance.  In order to do that I need to set up the encryption options in adguard so that I can communicate it with it using dns-over-https.  I am not comfortable communicating with my adguard instance from outside my network unencrypted.

## Expected behavior

In the adguard add-ons settings, there's an option for "encryption settings".  It's pretty straightforward, it asks you to provide a port, a domain name and a certificate to use.  I filled those out and it saved.  I then expected to be able to test it via curl and do dns resolutions via the dns-over-https syntax.

## Actual behavior

Nothing happened.  The port did not respond at all, nothing was listening.  I tried enabling the web UI port to see if maybe enabling this option required using it in non-ingress mode but that didn't change anything.  I could not make dns-over-https calls to the adguard instance

## Steps to reproduce

See above.  Just fill out the info on the encryption settings.  You should then be able to test it by simply hitting the URL 'https://{HA base URL}:{port you choose}/dns-query?name=example.com&type=AAAA' and get a response similar to what you see [here in cloudflare's docs](https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/)

## Proposed changes

I would like this settings panel to basically do what it says it does.  When the encryption options are filled out and a port is provided for DoH then it starts a DNS-over-HTTPS server to listen for those types of DNS queries.  It should also probably start a DoT server if the port is provided for that option as well since that is what it says it does.

**Comment by sinclairpaul** [comment]
The challenge will likely be the port isn't exposed via docker.  Will need to test and validate some more on how to enable this.

**Comment by mdegat01** [comment]
Wanted to check in on this.  Any luck @sinclairpaul ?

**Comment by sinclairpaul** [comment]
I haven't had any time to look at it, from what I see we could expose the ports (they would need to be fixed), however this looks like it would also expose the Admin interface, meaning it would be accessible with no authentication.

We also would need to address if  the redirect option is set, which would break the addon.

Will look at it if I have some time.

**Comment by frenck** [comment]
This has been added in the latest release.

**Comment by sinclairpaul** [comment]
I just want to add on this, I don't believe Adguard supports the JSON format, but you can use Cloudflared to validate using wireformat.
