### ISSUE TITLE
AdGuard container gets stuck in faulted state after running ~8 hours

### ISSUE THREAD

**Issue by NizZ8** [hassio-addons/addon-adguard-home#45]
# Problem/Motivation
AdGuard container gets stuck in faulted state after running ~8 hours.  Currently have to restart the container approx 1-2 times a day to get it working again.

## Expected behavior
AdGuard runs w/o manual intervention

## Actual behavior
After running for approx ~8 hours, the container faults and gets stuck into a loop.

## Steps to reproduce
Install AdGuard Home Add-On using default Config/Network options and let run for a day

## Proposed changes
Don't know

## Log
2020/03/09 03:52:30 [info] AdGuard Home, version v0.100.9, channel release

2020/03/09 03:52:30 [info] Upstream 0: https://dns.quad9.net:443/dns-query
2020/03/09 03:52:30 [info] Go to http://127.0.0.1:45158
2020/03/09 03:52:30 [info] Starting the DNS proxy server
2020/03/09 03:52:30 [info] Ratelimit is enabled and set to 20 rps
2020/03/09 03:52:30 [info] The server is configured to refuse ANY requests
2020/03/09 03:52:30 [info] DNS cache is enabled
2020/03/09 03:52:30 [info] Creating the UDP server socket
2020/03/09 03:52:30 [info] Listening to udp://[::]:53
2020/03/09 03:52:30 [info] Creating the TCP server socket
2020/03/09 03:52:30 [info] Listening to tcp://[::]:53
2020/03/09 03:52:30 [info] Entering the tcp listener loop on [::]:53
2020/03/09 03:52:30 [info] Entering the UDP listener loop on [::]:53
2020/03/09 05:29:48 [info] Filter 2 has been updated: 442270 bytes, 15611 rules
2020/03/09 05:29:50 [info] Saving filter 2 contents to: /data/adguard/data/filters/2.txt
2020/03/09 05:29:50 [info] Updated filter #2.  Rules: 15613 -> 15611
2020/03/09 13:00:11 [info] Stopping AdGuard Home
2020/03/09 13:00:11 [info] Stopping the DNS proxy server
2020/03/09 13:00:11 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2020/03/09 13:00:11 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2020/03/09 13:00:11 [info] Stopped the DNS proxy server
2020/03/09 13:00:11 [info] Stopped
2020/03/09 13:02:11 [info] AdGuard Home, version v0.100.9, channel release

2020/03/09 13:02:11 [error] Couldn't parse config file: yaml: unmarshal errors:
  line 9: cannot unmarshal !!str `` into int
2020/03/09 13:02:12 [info] AdGuard Home, version v0.100.9, channel release

2020/03/09 13:02:12 [error] Couldn't parse config file: yaml: unmarshal errors:
  line 9: cannot unmarshal !!str `` into int
2020/03/09 13:02:13 [info] AdGuard Home, version v0.100.9, channel release

2020/03/09 13:02:13 [error] Couldn't parse config file: yaml: unmarshal errors:
  line 9: cannot unmarshal !!str `` into int
2020/03/09 13:02:14 [info] AdGuard Home, version v0.100.9, channel release

2020/03/09 13:02:14 [error] Couldn't parse config file: yaml: unmarshal errors:
  line 9: cannot unmarshal !!str `` into int
2020/03/09 13:02:15 [info] AdGuard Home, version v0.100.9, channel release

....

The Below is after restarting the container

2020/03/11 18:47:59 [info] AdGuard Home, version v0.100.9, channel release

2020/03/11 18:47:59 [info] Upstream 0: https://dns.quad9.net:443/dns-query
2020/03/11 18:47:59 [info] Go to http://127.0.0.1:45158
2020/03/11 18:47:59 [info] Starting the DNS proxy server
2020/03/11 18:47:59 [info] Ratelimit is enabled and set to 20 rps
2020/03/11 18:47:59 [info] The server is configured to refuse ANY requests
2020/03/11 18:47:59 [info] DNS cache is enabled
2020/03/11 18:47:59 [info] Creating the UDP server socket
2020/03/11 18:47:59 [info] Listening to udp://[::]:53
2020/03/11 18:47:59 [info] Creating the TCP server socket
2020/03/11 18:47:59 [info] Listening to tcp://[::]:53
2020/03/11 18:47:59 [info] Entering the UDP listener loop on [::]:53
2020/03/11 18:47:59 [info] Entering the tcp listener loop on [::]:53
2020/03/11 18:47:59 [info] Filter 1 has been updated: 566963 bytes, 29677 rules
2020/03/11 18:48:01 [info] Saving filter 1 contents to: /data/adguard/data/filters/1.txt
2020/03/11 18:48:01 [info] Updated filter #1.  Rules: 29647 -> 29677

**Comment by sinclairpaul** [comment]
This really sounds likely to be hardware related issues, what platform do you use.  As it stands it is impossible to duplicate.

**Comment by NizZ8** [comment]
Running on a Synology NAS Device

**Comment by sinclairpaul** [comment]
I would suggest seeking help at the community forums, as this device is really community supported.  I will add from the logs you shared it does seem specific to particular times.
