### ISSUE TITLE
My router switches to the backup DNS after a day or so

### ISSUE THREAD

**Issue by Sprachbuch** [hassio-addons/addon-adguard-home#452]
Certainly, here's the corrected version:

# Problem/Motivation

> As the title suggests, my router switches to the backup DNS after a day or so. When I restart AdGuard, everything works as expected for a while. Also, just removing the backup DNS does not help since the router isn't able to resolve DNS addresses over AdGuard until I restart the addon.

## Expected behavior

> AdGuard should only block ads and work continuously.

## Actual behavior

> The addon stops working after a somewhat random time.

## Steps to reproduce

> I really don't know.

## Proposed changes

> (If you have a proposed change, workaround, or fix, describe the rationale behind it)

**Comment by sidler** [comment]
+1
