### ISSUE TITLE
Custom filtering rules

### ISSUE THREAD

**Issue by Claton** [hassio-addons/addon-adguard-home#47]
When HA reboots, Adguards "Custom filtering rules" need to be reapplied.  It appears the Custom filtering rules and not being read on boot.

**Comment by frenck** [comment]
HA restarts are not affected by add-ons.

If there is an issue with reading/applying settings on add-on start, this should be reported with the AdGuard team. The add-on wraps existing software and cannot change that behavior or address those types of bugs.

Thanks! 👍
