### ISSUE TITLE
Abnormal use of disk

### ISSUE THREAD

**Issue by riddik14** [hassio-addons/addon-adguard-home#471]
after the last update I found the used disk with +30Gb of data. I found out it was the addon's fault. I removed it and immediately recovered the space. why does the latest version use so much space?

**Comment by frenck** [comment]
> I removed it and immediately recovered the space.

Removed what?

**Comment by riddik14** [comment]
I uninstalled the addon and recovered the space. I think the logs. I noticed anomalous traffic of DNS requests. I will do the necessary checks.

**Comment by frenck** [comment]
Hmm interesting. Would be nice to understand which file (or files) specifically. I haven't noticed any weirdness like this

**Comment by riddik14** [comment]
Maybe it's my fault that I activated log saving, but to make 50 GB of logs means that someone is making a lot of DNS requests

**Comment by riddik14** [comment]
Resolved. I was using the DMZ to the Hassos server and was receiving DNS requests from WAN. there were immense requests, so much so that the addon log was loaded too much. it can be closed.

**Comment by riddik14** [comment]
700 request for minutes.🤣🤣🤦🤦🤦
