### ISSUE TITLE
Problem with Block Ads while domains are on Blocklist and Custom Filtering Rules

### ISSUE THREAD

**Issue by FancyNerd92** [hassio-addons/addon-adguard-home#472]
# Problem/Motivation

> Problem with Block Ads while domains are on Blocklist and Custom Filtering Rules

## Expected behavior

> To be blocked. For example these links ||xhamster.com/stripchat^$important ||xhamsterlive.com^$important are on my custom rules and on my dns blocklists, i check the filtering and says they are blocked but still i can see their ads (banners, popups, skip ad on video)

## Actual behavior

> They are not blocked

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

>After an big update xhamster.com one of the biggest adult site make something and their ads can't blocked by AdGuard Home as did before... Please fix it.

**Comment by tjorim** [comment]
We just made adguard home in an add-on, there's nothing we can do. Check with the upstream project on how to proceed. I assume they use some other domain names now.
