### ISSUE TITLE
Support for /etc/hosts mapping

### ISSUE THREAD

**Issue by Sebazzz** [hassio-addons/addon-adguard-home#48]
# Problem/Motivation
I'm currently attempting to migrate from the pi.hole add-on for Home Assistant. In the pi.hole add-on it was possible to create a hosts mapping in the config, using the `hosts` dictionary.

According to [this PR](https://github.com/AdguardTeam/AdGuardHome/commit/63923fa882205aca26b668e4a65ae5d341e73327) it is possible to use the `/etc/hosts` file to add mappings for LAN devices.

## Proposed changes

Ability map LAN devices to `/etc/hosts` by allowing a `hosts` configuration just like the pi.hole add-on YAML.

**Comment by frenck** [comment]
You don't need to, as the web interface provides the option to add DNS overrides or alternatively a filter to do that can be used as well.

So that is already 2 methods to do that. Adding a third method seems a bit overkill to me.

**Comment by Sebazzz** [comment]
Awesome. I wasn't aware!
