### ISSUE TITLE
Access from Wireguard Vpn

### ISSUE THREAD

**Issue by sotoje** [hassio-addons/addon-adguard-home#49]
I am Hassio user, I used Pi Hole and i starting use Ad Guard, but when i try to use it when i connected through to Wireguard VPN, ad guard service does not work, i have not any DNS resolution.

I think the problem is because ad guard is not listening in the correct network interface. When i used Pi Hole, i could choose where service was waiting petitions.

Is this capability available in Ad Guard?

**Comment by frenck** [comment]
Please see the wireguard add-on documentation, as this is documented.

**Comment by sotoje** [comment]
Solved, sorry
