### ISSUE TITLE
continuous errors in the plugin

### ISSUE THREAD

**Issue by cop98** [hassio-addons/addon-adguard-home#490]
Often the plugin crashes and it is impossible to surf the Internet. It is necessary to restart the add-on and everything starts working again.

This happens at least twice a day, below are the logs

thanks

2024/01/24 10:34:34.511631 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.00261401s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:39942->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.728627 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001338616s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56440->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.734577 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001365171s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:34407->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.741058 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002147034s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:36600->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.766784 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001958332s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40602->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.795557 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002519585s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:59928->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.811406 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001242265s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:46612->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.833976 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.003294578s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:55362->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.836636 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001974368s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:57931->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.849331 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002105089s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41898->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.853624 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002451957s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41440->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.862223 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002731158s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41189->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.882946 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002339884s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41614->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.884966 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002311217s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:39200->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.887745 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001588391s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40875->172.30.32.3:53: i/o timeout
2024/01/24 10:34:34.890382 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001948739s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:34748->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.424406 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001949649s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:48729->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.433830 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.002793325s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:38490->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.436882 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001179916s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:43148->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.438376 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.00151832s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:55773->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.513238 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001968112s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:45326->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.729839 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00235446s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:37862->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.735793 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001327786s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40135->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.742025 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001557598s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:42354->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.773790 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00135273s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56704->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.804985 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001480155s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:34389->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.812208 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001052863s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:52656->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.833719 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001408137s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:35215->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.841548 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.0029029s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:60912->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.850935 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001349453s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:39520->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.854523 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001805466s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:59782->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.862371 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.000922753s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:47037->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.883925 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001858299s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:42167->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.885097 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001829059s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56348->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.887706 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001270898s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:45217->172.30.32.3:53: i/o timeout
2024/01/24 10:34:35.892487 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001647598s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:39836->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.430773 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.004072132s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:44946->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.436990 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.003954151s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:35667->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.439675 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.002435832s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:36360->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.439675 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.000874737s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:43674->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.516221 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.002855533s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:38815->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.730977 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001984394s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:51298->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.738778 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002043078s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:37463->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.744406 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.000980867s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:38194->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.774860 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001983579s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:55438->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.812510 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001877784s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:32826->172.30.32.3:53: i/o timeout
2024/01/24 10:34:36.815766 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001652249s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:52926->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.219962 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00221993s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:58648->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.222078 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001241681s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:55580->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.222090 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002629834s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:50305->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.223897 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001660324s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:46276->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.226181 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001446586s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:47132->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.226389 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001786342s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:58751->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.228595 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001833767s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:42472->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.228669 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.0026725s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:51153->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.229422 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00140092s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:48107->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.430586 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.003081552s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:53469->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.434901 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001024258s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:34449->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.440640 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001698454s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:57878->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.440981 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.000610076s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:60980->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.516396 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.00112609s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:35794->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.735296 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001570771s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:36495->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.740696 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00183601s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:51522->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.747116 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.003084942s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56614->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.789252 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002553837s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:59444->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.814132 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001863769s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:53750->172.30.32.3:53: i/o timeout
2024/01/24 10:34:37.816143 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001499457s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:35956->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.223700 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002519653s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40463->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.227519 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002392672s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:59542->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.228038 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002192805s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:49212->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.228168 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.0044688s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:49893->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.229677 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002428488s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:51810->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.229677 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001252869s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:42569->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.230042 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.000680116s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:46624->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.232371 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002020084s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:51692->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.234067 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002647967s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56550->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.432306 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001942085s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:38765->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.438572 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.003221758s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:33630->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.441584 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001185537s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:57448->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.445245 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.002758448s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:52470->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.520133 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001280592s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56789->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.737160 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001943439s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40304->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.746960 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002780375s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:54314->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.760624 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002874929s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41232->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.790412 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002259028s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:42940->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.820675 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002010012s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:49945->172.30.32.3:53: i/o timeout
2024/01/24 10:34:38.824282 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00172907s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40875->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.228558 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.0022509s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:33449->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.235382 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.00152687s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:48068->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.239185 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001310447s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:49338->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.242522 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002053661s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:60649->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.246301 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.002145068s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:37284->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.246622 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.000722396s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:39994->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.250292 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001230706s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:44985->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.255810 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001794664s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:41175->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.260531 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;47.110.30.10.in-addr.arpa.	IN	 PTR in 2.001995939s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:35208->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.433392 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001765998s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:34248->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.438501 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001227818s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:52380->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.442418 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.001922478s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:40753->172.30.32.3:53: i/o timeout
2024/01/24 10:34:39.446176 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;6.19.147.10.in-addr.arpa.	IN	 PTR in 2.003177929s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:58569->172.30.32.3:53: i/o timeou

**Comment by woempiej** [comment]
Hi,

A plugin crash can be fixed by turn ON the "Watchdog" function?!

Have you tried the below DNS setting? Fill in the local IP adres of your HA server

![afbeelding](https://github.com/hassio-addons/addon-adguard-home/assets/62903344/ba71e340-e713-4ecb-be1b-bfeb03bffc19)
