### ISSUE TITLE
Broken since home assitant os 12

### ISSUE THREAD

**Issue by Silther** [hassio-addons/addon-adguard-home#496]
# Problem/Motivation

> I used adguard home to rewrite my dns request if I am in my local wifi, to keep the latency down, but since the update to HA OS 12 I only get a blank screen when opening the addon

## Expected behavior

> adguard home should start

## Actual behavior

> the screen keeps blank

## Steps to reproduce

> update to HA OS 12 or maybe simply restart

## Logs

<details>
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 5.0.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.2.5
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-adguard: starting
s6-rc: info: service init-nginx successfully started
s6-rc: info: service init-adguard successfully started
s6-rc: info: service adguard: starting
s6-rc: info: service adguard successfully started
s6-rc: info: service discovery: starting
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
[14:48:03] INFO: Starting AdGuard Home server...
2024/02/29 14:48:03.313754 [info] AdGuard Home, version v0.107.44
2024/02/29 14:48:03.317243 [info] tls: using default ciphers
2024/02/29 14:48:03.324132 [info] safesearch default: reset 253 rules
2024/02/29 14:48:03.330687 [info] Initializing auth module: /data/adguard/data/sessions.db
2024/02/29 14:48:03.330958 [info] auth: initialized.  users:0  sessions:0
2024/02/29 14:48:03.331118 [info] AdGuard Home updates are disabled
2024/02/29 14:48:03.331168 [info] web: initializing
2024/02/29 14:48:03.385219 [info] dnsproxy: cache: enabled, size 4096 b
2024/02/29 14:48:03.385280 [info] dnsproxy: max goroutines is set to 300
2024/02/29 14:48:03.385389 [info] dnsproxy: cache: disabled
2024/02/29 14:48:03.385698 [info] AdGuard Home is available at the following addresses:
2024/02/29 14:48:03.385749 [info] go to http://127.0.0.1:45158
2024/02/29 14:48:03.385971 [info] clients: processing addresses
[14:48:03] INFO: Starting NGinx...
[14:48:03] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
2024/02/29 14:48:03.946356 [info] dnsproxy: starting dns proxy server
2024/02/29 14:48:03.946564 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
2024/02/29 14:48:03.946727 [info] The server is configured to refuse ANY requests
2024/02/29 14:48:03.946822 [info] dnsproxy: cache: enabled, size 4194304 b
2024/02/29 14:48:03.946912 [info] dnsproxy: max goroutines is set to 300
2024/02/29 14:48:03.947110 [info] dnsproxy: creating udp server socket 192.168.178.42:53
2024/02/29 14:48:03.947400 [info] dnsproxy: listening to udp://192.168.178.42:53
2024/02/29 14:48:03.947920 [info] dnsproxy: creating udp server socket [2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.948229 [info] dnsproxy: listening to udp://[2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.948456 [info] dnsproxy: creating udp server socket 172.30.32.1:53
2024/02/29 14:48:03.948686 [info] dnsproxy: listening to udp://172.30.32.1:53
2024/02/29 14:48:03.948903 [info] dnsproxy: creating udp server socket 127.0.0.1:53
2024/02/29 14:48:03.949173 [info] dnsproxy: listening to udp://127.0.0.1:53
2024/02/29 14:48:03.949437 [info] dnsproxy: creating udp server socket [::1]:53
2024/02/29 14:48:03.949790 [info] dnsproxy: listening to udp://[::1]:53
2024/02/29 14:48:03.949905 [info] dnsproxy: creating tcp server socket 192.168.178.42:53
2024/02/29 14:48:03.950103 [info] dnsproxy: listening to tcp://192.168.178.42:53
2024/02/29 14:48:03.950165 [info] dnsproxy: creating tcp server socket [2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.950275 [info] dnsproxy: listening to tcp://[2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.950332 [info] dnsproxy: creating tcp server socket 172.30.32.1:53
2024/02/29 14:48:03.950447 [info] dnsproxy: listening to tcp://172.30.32.1:53
2024/02/29 14:48:03.950502 [info] dnsproxy: creating tcp server socket 127.0.0.1:53
2024/02/29 14:48:03.950610 [info] dnsproxy: listening to tcp://127.0.0.1:53
2024/02/29 14:48:03.950668 [info] dnsproxy: creating tcp server socket [::1]:53
2024/02/29 14:48:03.950778 [info] dnsproxy: listening to tcp://[::1]:53
2024/02/29 14:48:03.951005 [info] dnsproxy: entering udp listener loop on 192.168.178.42:53
2024/02/29 14:48:03.951168 [info] dnsproxy: entering udp listener loop on [::1]:53
2024/02/29 14:48:03.951306 [info] dnsproxy: entering udp listener loop on [2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.951428 [info] dnsproxy: entering udp listener loop on 172.30.32.1:53
2024/02/29 14:48:03.951548 [info] dnsproxy: entering udp listener loop on 127.0.0.1:53
2024/02/29 14:48:03.951693 [info] dnsproxy: entering tcp listener loop on [2a02:810d:b5c0:1ed4:646d:bae5:c32a:a1cb]:53
2024/02/29 14:48:03.951781 [info] dnsproxy: entering tcp listener loop on 192.168.178.42:53
2024/02/29 14:48:03.951829 [info] dnsproxy: entering tcp listener loop on 127.0.0.1:53
2024/02/29 14:48:03.951867 [info] dnsproxy: entering tcp listener loop on 172.30.32.1:53
2024/02/29 14:48:03.951909 [info] dnsproxy: entering tcp listener loop on [::1]:53
s6-rc: info: service legacy-services successfully started

</details>

**Comment by ZainAjam** [comment]
Same problem yes

**Comment by bthamburg** [comment]
> I'm able to access adguard on boot but my dns server redirects stopped working after a recent home assistant core os update

For me too DNS rewrite do not work

**Comment by ZainAjam** [comment]
Latest update has fixed it for me

**Comment by ZainAjam** [comment]
Seems to be broken again. Not sure what is happening

**Comment by arjenbos** [comment]
I'm experiencing the same issue.  I see a lot of these errors in my logs:

```
2024/03/14 09:24:50.492160 [error] dnsproxy: 172.30.32.3:53: response received over udp: "exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56983->172.30.32.3:53: i/o timeout"
2024/03/14 09:24:50.492251 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;88.1.168.192.in-addr.arpa.	IN	 PTR in 2.002213886s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56983->172.30.32.3:53: i/o timeout
```

**Comment by erdnaxela02** [comment]
> I see a lot of these errors in my logs:
> 
> ```
> 2024/03/14 09:24:50.492160 [error] dnsproxy: 172.30.32.3:53: response received over udp: "exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56983->172.30.32.3:53: i/o timeout"
> 2024/03/14 09:24:50.492251 [error] dnsproxy: upstream 172.30.32.3:53 failed to exchange ;88.1.168.192.in-addr.arpa.	IN	 PTR in 2.002213886s: exchanging with 172.30.32.3:53 over udp: read udp 172.30.32.1:56983->172.30.32.3:53: i/o timeout
> ```
Me too. I have same log loop :/
