### ISSUE TITLE
AdGuard can't run due to used port 53 by Hassio-dns

### ISSUE THREAD

**Issue by OGKevin** [hassio-addons/addon-adguard-home#50]
# Problem/Motivation

It is impossible to run AdGuard on the same machine as home-assistant due to Hassio-dns using port 53.

## Expected behavior

Hassio-dns being disabled for AdGuard to run.

## Actual behavior

AdGuard can't boot due to used port 53
It seems to be difficult to disable Hassio-dns https://community.home-assistant.io/t/how-disable-hassio-dns-coredns/138465 

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/8/0/80d3f33958a234aab5cb9364b998048064d12b9d.png" width="48" align="right"><div><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/f/4/f42b82971fce994297fbc2b269efa248beef897b_2_32x32.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/how-disable-hassio-dns-coredns/138465">How disable hassio_dns / coredns</a></strong></div><div>Hi, I’ve recently updated hassio, noticing these problems:   new addonds/container, called hassio_dns (I already have a dns server, pihole) this container contains a process, coredns, which spawn in different processes and eat all cpu *quad core) seems that now hassio is not good to connect to external api, like netatmo and ikea tradfri (maybe related to dns)  How can I disable this hassio_dns, using instead previous approach? I’ve also tried to disable/uninstall container, without success (afte...</div></blockquote>

**Comment by sinclairpaul** [comment]
If this were the case then nobody would be able to run the addon, as a user myself I can tell you this is not the case.

Perhaps you could post the log, and your OS.  I would guess that you are running on an Ubuntu install?

**Comment by OGKevin** [comment]
>If this were the case then nobody would be able to run the addon, as a user myself I can tell you this is not the case.

fair enough, I also thought about that but seeing that there was just no way to get Hassio_dns to turn of it just seems impossible. Could not find any doc on how to edit hassio_supervisor to forget about Hassio_dns so unless the only way is that I have to get in there and edit supervisor manually which seems to not be user friendly of course. 

```
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 2.3.3
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Ubuntu 18.04.4 LTS  (aarch64 / qemuarm-64)
 Home Assistant Core: 0.108.5
 Home Assistant Supervisor: 217
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing...
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing...
[08:20:21] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing...
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:20:22] INFO: Starting AdGuard Home server...
2020/04/17 08:20:23 [info] AdGuard Home, version v0.101.0, channel release
, arch linux arm64 v6%!(EXTRA string=6)
2020/04/17 08:20:23 [info] Upstream 0: https://dns10.quad9.net:443/dns-query
2020/04/17 08:20:23 [info] Go to http://127.0.0.1:45158
[08:20:23] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2020/04/17 08:20:24 [info] Starting the DNS proxy server
2020/04/17 08:20:24 [info] Ratelimit is enabled and set to 20 rps
2020/04/17 08:20:24 [info] The server is configured to refuse ANY requests
2020/04/17 08:20:24 [info] DNS cache is enabled
2020/04/17 08:20:24 [info] Creating the UDP server socket
2020/04/17 08:20:24 [fatal] Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: address already in use
```

**Comment by frenck** [comment]
It is not the Home Assistant DNS server that causes this. It is your Ubuntu Bionic host system that claims the port with its `systemd-resolved`.

**Comment by OGKevin** [comment]
@frenck i'm embarrassed, totally forgot about this. thx.
