### ISSUE TITLE
No DNS rewrite anymore

### ISSUE THREAD

**Issue by Gp2mv3** [hassio-addons/addon-adguard-home#502]
# Problem/Motivation

For some days, I don't have any DNS rewritten by AGH. It resolves DNS normally but doesn't rewrite and block requests. It seems I'm not the only one with this issue: https://github.com/AdguardTeam/AdGuardHome/issues/6701

## Expected behavior

Should work correctly and rewrite my DNS queries as before.

## Actual behavior

DNS is resolved normally, no rewrite, no blocking is done.
![Screenshot from 2024-03-16 11-08-13](https://github.com/hassio-addons/addon-adguard-home/assets/1221806/84764971-cec2-4575-af3a-a347cdb7c627)

Here is an example of request that should be rewritten:
```
nslookup -debug -type=a 'ads.google.com' '192.168.1.10'

Server:		192.168.1.10
Address:	192.168.1.10#53

------------
    QUESTIONS:
	ads.google.com, type = A, class = IN
    ANSWERS:
    ->  ads.google.com
	internet address = 142.250.186.78
	ttl = 300
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	ads.google.com
Address: 142.250.186.78
```

## Steps to reproduce

Unfortunately, I don't know when it started.

**Comment by SergeyPomelov** [comment]
No, not stale, I have an alike issue.
