### ISSUE TITLE
Processing Speed Climbing since March 12th

### ISSUE THREAD

**Issue by themorgantown** [hassio-addons/addon-adguard-home#503]
# Problem/Motivation

Previously, the processing speed of dns requests was around 12ms. It has climbed every day up to around 80ms as of today, March 18th. 

I have changed nothing on my instance since then. Hardware is a raspberry pi4. CPU and RAM are very low on this device in general and for the Adguard process. I've restarted since then and cleared the DNS cache. 

<img width="1100" alt="Screenshot 2024-03-18 at 11 44 24 AM" src="https://github.com/hassio-addons/addon-adguard-home/assets/50146/e2e8f25a-4ce1-4a2f-96c6-495b9c4ab072">

**Comment by kirilldem** [comment]
i have the same issue, so following :)

**Comment by themorgantown** [comment]
Now that value is going down after cache clear + upgrade.  @kirilldem can you check again? 

<img width="930" alt="Screenshot 2024-05-01 at 8 54 56 PM" src="https://github.com/hassio-addons/addon-adguard-home/assets/50146/8a27a0ee-67c9-4fd9-9583-83a6cf0e2435">
