### ISSUE TITLE
Addional switches 

### ISSUE THREAD

**Issue by jonny190** [hassio-addons/addon-adguard-home#507]
# Problem/Motivation

Enable more automation possibilities, like timed setting changes, or setting changes based on presence 

## Expected behaviour

Can we get switches to enable/disable service blocking 

## Actual behaviour

no switches 

## Steps to reproduce

n/a

**Comment by frenck** [comment]
I think you are confusing the add-on with the Home Assistant integration. Add-ons and integration are not the same things.

This is the repository and issue tracker of the add-on.

../Frenck
