### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by megawubs** [hassio-addons/addon-adguard-home#51]
# Problem/Motivation
I previously used the PiHole add-on. With the recent deprecation of PiHole I've been trying to setup the AdGuard add-on, but this is without success. Whenever I switch PiHole off and AdGuard on, there is no internet connection on my network. I've set the pi up with a static ip using nmcli. This was already needed for PiHole to work. 
> When I start AdGuard my internet stops working. 

## Expected behavior

> A working internet connection with ads being blocked

## Actual behavior

> No internet connection at all

## Steps to reproduce

> 
1. Turn off the PiHole add-on
2. Start AdGuard

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Can you post the addon startup logs, as well as the supervisor log?

Can you validate DNS works using nslookup?

**Comment by frenck** [comment]
No response from issue creator. Closing.
