### ISSUE TITLE
After installing Adguard in HA OS it doesn't work

### ISSUE THREAD

**Issue by raforo** [hassio-addons/addon-adguard-home#519]
# Problem/Motivation
After installing Adguard in HA OS it doesn't work

## Expected behavior

I hope it works properly
## Actual behavior
Adguard does'nt work 
If you try to update lists, or test initial DNS or any other internet access, it generates an error, it seems that the addon does'nt have internet access and the log shows these errors:

----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 5.0.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.5.4
 Home Assistant Supervisor: 2024.05.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-adguard: starting
s6-rc: info: service init-nginx successfully started
s6-rc: info: service init-adguard successfully started
s6-rc: info: service adguard: starting
s6-rc: info: service adguard successfully started
s6-rc: info: service discovery: starting
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
[20:18:03] INFO: Starting AdGuard Home server...
2024/05/18 20:18:03.961616 [info] AdGuard Home, version v0.107.48
2024/05/18 20:18:03.969943 [info] tls: using default ciphers
2024/05/18 20:18:03.987265 [info] safesearch default: reset 253 rules
2024/05/18 20:18:04.013074 [info] Initializing auth module: /data/adguard/data/sessions.db
2024/05/18 20:18:04.014426 [info] auth: initialized.  users:0  sessions:0
2024/05/18 20:18:04.014483 [info] AdGuard Home updates are disabled
2024/05/18 20:18:04.014493 [info] web: initializing
2024/05/18 20:18:04.024718 [info] dnsproxy: cache: enabled, size 4096 b
2024/05/18 20:18:04.024770 [info] dnsproxy: max goroutines is set to 300
2024/05/18 20:18:04.024927 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
2024/05/18 20:18:04.024997 [info] dnsproxy: server will refuse requests of type ANY
2024/05/18 20:18:04.025009 [info] dnsproxy: cache: enabled, size 4194304 b
2024/05/18 20:18:04.025084 [info] dnsproxy: max goroutines is set to 300
2024/05/18 20:18:04.025653 [info] AdGuard Home is available at the following addresses:
2024/05/18 20:18:04.025702 [info] go to http://127.0.0.1:45158
2024/05/18 20:18:04.027220 [info] clients: processing addresses
2024/05/18 20:18:04.047588 [info] dnsproxy: starting dns proxy server
2024/05/18 20:18:04.047839 [info] dnsproxy: creating udp server socket 192.168.1.68:53
2024/05/18 20:18:04.048073 [info] dnsproxy: listening to udp://192.168.1.68:53
2024/05/18 20:18:04.048099 [info] dnsproxy: creating udp server socket [fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.048205 [info] dnsproxy: listening to udp://[fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.048219 [info] dnsproxy: creating udp server socket 172.30.32.1:53
2024/05/18 20:18:04.048301 [info] dnsproxy: listening to udp://172.30.32.1:53
2024/05/18 20:18:04.048314 [info] dnsproxy: creating udp server socket 127.0.0.1:53
2024/05/18 20:18:04.048383 [info] dnsproxy: listening to udp://127.0.0.1:53
2024/05/18 20:18:04.048396 [info] dnsproxy: creating udp server socket [::1]:53
2024/05/18 20:18:04.048467 [info] dnsproxy: listening to udp://[::1]:53
2024/05/18 20:18:04.048491 [info] dnsproxy: creating tcp server socket 192.168.1.68:53
2024/05/18 20:18:04.048582 [info] dnsproxy: listening to tcp://192.168.1.68:53
2024/05/18 20:18:04.048596 [info] dnsproxy: creating tcp server socket [fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.048670 [info] dnsproxy: listening to tcp://[fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.048682 [info] dnsproxy: creating tcp server socket 172.30.32.1:53
2024/05/18 20:18:04.048741 [info] dnsproxy: listening to tcp://172.30.32.1:53
2024/05/18 20:18:04.048753 [info] dnsproxy: creating tcp server socket 127.0.0.1:53
2024/05/18 20:18:04.048816 [info] dnsproxy: listening to tcp://127.0.0.1:53
2024/05/18 20:18:04.048840 [info] dnsproxy: creating tcp server socket [::1]:53
2024/05/18 20:18:04.049006 [info] dnsproxy: listening to tcp://[::1]:53
2024/05/18 20:18:04.050094 [info] dnsproxy: entering udp listener loop on 192.168.1.68:53
2024/05/18 20:18:04.050882 [info] dnsproxy: entering udp listener loop on [fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.051197 [info] dnsproxy: entering udp listener loop on 172.30.32.1:53
2024/05/18 20:18:04.051387 [info] dnsproxy: entering udp listener loop on 127.0.0.1:53
2024/05/18 20:18:04.051554 [info] dnsproxy: entering udp listener loop on [::1]:53
2024/05/18 20:18:04.051823 [info] dnsproxy: entering tcp listener loop on 192.168.1.68:53
2024/05/18 20:18:04.051946 [info] dnsproxy: entering tcp listener loop on [fd93:861a:68d2:9ec:2161:152b:9586:a0d5]:53
2024/05/18 20:18:04.052008 [info] dnsproxy: entering tcp listener loop on 172.30.32.1:53
2024/05/18 20:18:04.052050 [info] dnsproxy: entering tcp listener loop on 127.0.0.1:53
2024/05/18 20:18:04.052096 [info] dnsproxy: entering tcp listener loop on [::1]:53
[20:18:04] INFO: Starting NGinx...
[20:18:04] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024/05/18 20:18:29.059241 [error] dnsproxy: 1.1.1.1:53: response received over udp: "exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:33595->1.1.1.1:53: i/o timeout"
2024/05/18 20:18:29.063117 [error] dnsproxy: 1.1.1.1:53: response received over udp: "exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:45481->1.1.1.1:53: i/o timeout"
2024/05/18 20:18:29.063360 [error] dnsproxy: upstream https://dns10.quad9.net:443/dns-query failed to exchange ;adguardteam.github.io.	IN	 AAAA in 20.009022772s: failed to init http client: initializing http transport: bootstrapping https://dns10.quad9.net:443/dns-query: dialing "dns10.quad9.net:443": resolving hostname: exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:33595->1.1.1.1:53: i/o timeout
exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:45481->1.1.1.1:53: i/o timeout
2024/05/18 20:18:29.063487 [error] dnsproxy: upstream https://dns10.quad9.net:443/dns-query failed to exchange ;adguardteam.github.io.	IN	 A in 20.008398346s: failed to init http client: timeout exceeded: 20.008387735s
2024/05/18 20:18:29.064106 [error] filtering: os.Chtimes(): chtimes /data/adguard/data/filters/1.txt: no such file or directory
2024/05/18 20:18:29.064174 [error] filtering: updating filter from url "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt": reading from url: Get "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt": resolving "adguardteam.github.io": failed to init http client: initializing http transport: bootstrapping https://dns10.quad9.net:443/dns-query: dialing "dns10.quad9.net:443": resolving hostname: exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:33595->1.1.1.1:53: i/o timeout
exchanging with 1.1.1.1:53 over udp: read udp 192.168.1.68:45481->1.1.1.1:53: i/o timeout
failed to init http client: timeout exceeded: 20.008387735s

## Steps to reproduce

I've rebooted and reinstalled the Addon several times, testing SSL on and off, I've also rebooted the Raspbery Pi 4 and the HA OS several times. All other systems and HA have internet access and work fine, and as far as I know, port 53 is not used by another service.

HA has the DuckDNS Addon installed but does'nt have it installed nginx addon
## Proposed changes

Please help.
 There is probably some error, but I can't find any more instructions, just plug and play

**Comment by raforo** [comment]
![Captura de pantalla 2024-05-18 210622](https://github.com/hassio-addons/addon-adguard-home/assets/91435639/91d6c4d9-da4e-4878-b1c5-6a834fb1b8d7)

**Comment by tjorim** [comment]
Just double checking: did you already set the DNS server to your adguard/Home Assistant server somewhere?

**Comment by raforo** [comment]
> Just double checking: did you already set the DNS to your adguard/Home Assistant server somewhere? Did you set a fixed IP address and DNS server on the raspberry pi itself?

Thanks, I've always had a fixed IP in HA and it appears in the LOG as 192.168.1.68 and when I put that IP as DNS on my Windows computer, I lose internet, of course.

Thanks again

**Comment by raforo** [comment]
I've stopped almost all the addons I have, especially DuckDNS which uses port 443 and Grafana which uses port 3000, I've closed all the router ports, I've even stopped the firewall and antivirus temporarily and I've reinstalled Adguard and the behavior is the same, somewhat prevents it internet access.
