### ISSUE TITLE
Curl command to AGH addon

### ISSUE THREAD

**Issue by TeHashX** [hassio-addons/addon-adguard-home#524]
Hi, trying to send a curl command to AdGuard Home addon but I get "405: Method Not Allowed"
I open the issue here because in Discussions "almost" never get a response.
Which should be the right way or right address?

`curl -X POST -H "content-Type:application/json" -s -u 'username:password' '192.168.1.123:8123/a0d7b954_adguard/ingress/control/clients/update' -d '{"name": "samsung","data":{"name":"samsung","ids": ["192.168.5.125"],"tags": ["device_pc"],"upstreams": [],"filtering_enabled": true,"use_global_blocked_services": true,"use_global_settings": true}}'`
Or
`curl -X POST -H "content-Type:application/json" -s -u 'username:password' 'https://mydomain.com:8123/a0d7b954_adguard/ingress/control/clients/update' -d '{"name": "samsung","data":{"name":"samsung","ids": ["192.168.5.125"],"tags": ["device_pc"],"upstreams": [],"filtering_enabled": true,"use_global_blocked_services": true,"use_global_settings": true}}'`

**Comment by frenck** [comment]
You are communicating with Home Assistant in those commands, not AdGuard Home.

../Frenck

**Comment by TeHashX** [comment]
Then how to communicate with addon?

**Comment by TeHashX** [comment]
I just want to block my kid accessing youtube app on tv like in this thread https://community.home-assistant.io/t/adguard-home-integration-any-way-to-toggle-client-settings/615121/22
