### ISSUE TITLE
Add additional configuration options to AdGuardHome.yaml (enhancement)

### ISSUE THREAD

**Issue by dtx3k** [hassio-addons/addon-adguard-home#526]
# Problem/Motivation
Adguard provides additional functionality using its config yaml file
these additional options are not provided from its web interface

for example (and for me the most important ;) ) setting DHCP options is not possible via UI
see: https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#the-dhcpdhcpv4options-array-field
and: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
 
 now it is not possible to add additional parameters to the AdGuardHome.yaml

## Expected behavior
To be able to add additional parameters (especially the DHCP options for PXE ) to the adguard config
> (What you expected to happen)

## Actual behavior
Now its impossible to edit the configuration via the yaml file, only using the UI is possible
> (What actually happened)

## Steps to reproduce
-
> (How can someone else make/see it happen)

## Proposed changes

It would be nice to provide the possibility to add custom configuration (or just the DHCP Options)
or expose the AdGuardHome.yaml entirely as an advanced option

**Comment by frenck** [comment]
I would suggest to raise a feature request with AdGuard Home to add controls to their web interface instead.

../Frenck
