### ISSUE TITLE
Addon stopped working, now I can't install.

### ISSUE THREAD

**Issue by Fentoment** [hassio-addons/addon-adguard-home#536]
# Problem/Motivation

I unblocked a service and a link earlier and blocked them again, after X minutes I didn't have internet anymore.

## Expected behavior

 Block the sites/service again and just keep working.

## Actual behavior

The addon stopped responding and when I wanted check them in the app it said that it hadn't started yet, when I press "restart app" it threw out an error. (forgot which one)

I then deleted the app and now it says: Can't install ghcr.io/hassio-addons/adguard/aarch64:5.1.1: 500 Server Error for http+docker://localhost/v1.45/images/ghcr.io/hassio-addons/adguard/aarch64:5.1.1/json: Internal Server Error ("layer does not exist")
when I try to install it but I can't find anything about it online?

## Steps to reproduce

I just try to install it again and gives me that error.

## Proposed changes

 No idea, first time encountering stuff on something that normally just works, If you need anything more just ask.
 System:  Raspberry Pi 3

**Comment by frenck** [comment]
> I then deleted the app and now it says: Can't install ghcr.io/hassio-addons/adguard/aarch64:5.1.1: 500 Server Error for http+docker://localhost/v1.45/images/ghcr.io/hassio-addons/adguard/aarch64:5.1.1/json: Internal Server Error ("layer does not exist")
when I try to install it but I can't find anything about it online?

This is, unfortunately, not an add-on issue; but an issue with Home Assistant Supervisor or your system.

You can try running `ha supervisor repair` in a web terminal, that should aid with this issue. 

From an add-on perspective, there is nothing I can do about this. If the issue persists, please report it with the HA Supervisor project.

../Frenck

**Comment by Fentoment** [comment]
I think I did it with the webUI=

➜  ~ ha supervisor repair
Processing... Done.

Keep getting that same error, after doing the command and restarting the system, I'll ask somewhere else, thanks.

**Comment by frenck** [comment]
No problem I hope you figure it out 🙏 

../Frenck
