### ISSUE TITLE
[Feature Request] Option to not keep statistics

### ISSUE THREAD

**Issue by rbamos** [hassio-addons/addon-adguard-home#54]
Thanks for making this addon, it's super helpful. I'm wondering if it would be possible to add an option to not keep statistics, for privacy reasons? I'd prefer not to record what DNS requests my roommates are making.

**Comment by frenck** [comment]
![Uploading image.png…]()

**Comment by rbamos** [comment]
Will that stop the stats from being collected? The stats settings are separated from the logs settings

**Comment by rbamos** [comment]
Ah, I see, I didn’t understand the settings. Sorry to waste your time

**Comment by frenck** [comment]
I will stop individual requests from being collected. Not generic query statistics in total counters (which are not individually traceable).

**Comment by rbamos** [comment]
Okay, great, thank you very much!
