### ISSUE TITLE
Make AdGuardHome.yaml file accessible via home assistant file editor

### ISSUE THREAD

**Issue by Martin-Dolan** [hassio-addons/addon-adguard-home#541]
# Problem/Motivation

> The AdGuardHome.yaml file is very hard to edit as it is in a separate docker container. I have worked out how to edit it but its taken days and lots of tears.
All I needed to do was add the option 6 line to the dhcpv4 section, so that I can specify the secondary IP for a backup/synced version of AdGuardHome  That way when home assistant goes down or offline, every device on your network does not fail due to there being no reachable DNS server

## Expected behaviour

> almost all of the other installs of adguard home are on a filesystem where you can just browse to the /data/AdGuardHome.yaml file and make edits.

## Proposed changes

> make a link to the AdGuardHome.yaml file appear in the home assistant config folder.
for example: /homeassistant/addons_config/AdGuardHome/AdGuardHome.yaml

> There are already a few other addons that use this same foprmat for their config files:
/homeassistant/addons_config/<AddonName>/<AddonName>.yaml

**Comment by frenck** [comment]
> The AdGuardHome.yaml file is very hard to edit as it is in a separate docker container.

It is not meant to be edited. Please use the web-interface provided by the add-on instead.

../Frenck

**Comment by Martin-Dolan** [comment]
> > The AdGuardHome.yaml file is very hard to edit as it is in a separate docker container.
> 
> It is not meant to be edited. Please use the web-interface provided by the add-on instead.
> 
> > All I needed to do was add the option 6 line to the dhcpv4 section, so that I can specify the secondary IP for a backup/synced version of AdGuardHome That way when home assistant goes down or offline, every device on your network does not fail due to there being no reachable DNS server
> 
> If this cannot be done through the UI, I suggest to make a feature request at the AdGuard Home project upstream instead.
> 
> ../Frenck

It has been asked many times to make adding a secondary DNS server editable through the UI, and the reply is always edit it in the AdGuardHome.yaml file, that is why there is an option in there for the very purpose.

It seems strange to me that they have a whole list of instructions and options on how to edit a file that according to you is "not meant to be edited"

[https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP](url)

and applications like "AdGuardHome Symc" require you to edit this file.

Can you please reconsider making this file editable on the Home Assistant version of Adguard so it is on par with the other versions?

**Comment by frenck** [comment]
> Can you please reconsider making this file editable on the Home Assistant version of Adguard so it is on par with the other versions?

I have no intention to do that.

../Frenck

**Comment by AeliusSaionji** [comment]
Could you elaborate on the reason for this? It's quite unconventional.

**Comment by frenck** [comment]
I did above. You don't have to agree. Feel free to start up and maintain your own version of the add-on if you like to take a different approach 👍 

../Frenck
