### ISSUE TITLE
Parental controls do not block websites

### ISSUE THREAD

**Issue by luizfeliperc** [hassio-addons/addon-adguard-home#543]
# Problem/Motivation

I recently installed Adguard, configured everything as stated and after some tests, even though the query log tells me that the request was blocked, the given website continues to be shown in all browsers (edge, firefox, Brave, Chrome).

![image](https://github.com/user-attachments/assets/3ec8482e-3f57-42b9-832b-60e1e3a02f7d)
![image](https://github.com/user-attachments/assets/eca5a6fa-073a-4917-8d9b-e09e2ce988bf)
![image](https://github.com/user-attachments/assets/aa69b9be-aefd-437b-b2d7-191d0354574a)
![image](https://github.com/user-attachments/assets/22601bd1-3cd0-48c3-9c7c-d4cc0a10b2bf)

## Expected behavior
Block, preventing the page from being displayed
> (What you expected to happen)

## Actual behavior
The page can be displayed without restriction

**Comment by sinclairpaul** [comment]
Do you have a secondary DNS on your clients?

**Comment by luizfeliperc** [comment]
> Do you have a secondary DNS on your clients?
I configured the primary to my HA address, and the secondary to 1.1.1.1 directly on my router

![image](https://github.com/user-attachments/assets/f99624d7-7a15-4bee-9353-c017ec5946b1)
![image](https://github.com/user-attachments/assets/f6d20872-07e8-4367-b34e-34419f48fda7)

**Comment by sinclairpaul** [comment]
Then the secondary will likely be resolving the addresses

**Comment by luizfeliperc** [comment]
> Then the secondary will likely be resolving the addresses

I removed the secondary one and left only the primary one and it apparently worked in Firefox, but in Chrome it continues to be displayed on the page.
Does it have some propagation time for it to work on everything?
![image](https://github.com/user-attachments/assets/2b91a9cc-017d-4aff-933b-6b579dce93ee)

**Comment by sinclairpaul** [comment]
It is likely that Brave has it's own DNS settings built in (unfortunately I'm not that familiar with it), as this is really out of scope for the addon, I will close this out.
