### ISSUE TITLE
Installed Hass.io in docker on Ubuntu LTS 20.04 and adguard cannot find eth0

### ISSUE THREAD

**Issue by mkotek** [hassio-addons/addon-adguard-home#55]
# Problem/Motivation
AdGuard does not start due to different if name: enp1s0 instead of eth0

## Expected behavior

AdGuard add-on should start and serve requests via main Ethernet I/f.

## Actual behavior

In Ubuntu 20.04 LTS, the interfaces naming is different and the Ethernet if is names enp1s0. It seems, AdGuard is having eth0 hardcoded and is looking for it.

## Steps to reproduce

1. Deploy hass.io (Home Assistant as a docker) on Ubuntu LTS 20.04.
2. Start AdGuard and it will fail:

[16:14:47] INFO: Starting AdGuard Home server...
2020/05/03 16:14:47 [info] AdGuard Home, version v0.101.0, channel release
, arch linux amd64%!(EXTRA string=)
2020/05/03 16:14:47 [info] Available network interfaces: "lo", "enp1s0", "docker0", "hassio", "vethd58e6de", "vethd426a69", "veth6939fd9", "vethb718215", "vethfb1a84b", "veth5523162", "vethbbf54cd", "veth85b6671", "vethbff20fe", "veth1db6c63", "veth72bde02", "vethe2aec86", "vethd26aeb3", "vethf17be3b", "vethaf5c051", "vethd936c4e", 
2020/05/03 16:14:47 [info] Couldn't find interface by name eth0, cause: route ip+net: no such network interface
2020/05/03 16:14:47 [error] DHCP: Couldn't find interface by name eth0, cause: route ip+net: no such network interface
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x975ccf]

**Comment by frenck** [comment]
Ubuntu 20.04 is not supported yet by Home Assistant, please use 18.04 until that happens.

**Comment by mkotek** [comment]
The issue has actually been caused by configuration inside the add-on. I have restored the config backed up on RPi4 and imported on Ubuntu, hence the issue. The solution was to modify the config inside the backup snapshot and restore it. Worked fine.
