### ISSUE TITLE
Adguard and hassio_dns conflict

### ISSUE THREAD

**Issue by nicolasvila** [hassio-addons/addon-adguard-home#56]
# Problem/Motivation

I have Hassio running on an Odroid board (ArchLinuxARM) 
I used the standard install process for generic linux with Docker.
Problem is Adguard can not be started on port 53 (already in use by hassio_dns

## Expected behavior

Adguard should be running on default port 53, so that it can be used by all machines on network
For example:
LAN                         >>>  Adguard (53)  >>>  forward to trusted DNS or local Unbound DNS
Hassio containers    >>>  Internal Hassio DNS (for addons IP resolution) or Aguard as default

## Actual behavior

Default 53 port is already in use by hassio-dns, which by the way forward queries to 8.8.8.8 or 1.1.1.1... That's exactly what I want to avoid. I have my own Unbound DNS server for all my network but wanted to add Adguard in front of it to filter what's going through

## Steps to reproduce

Start Hassio
Start Adguard

## Proposed changes

I tried to mess around with hassio_dns configuration files without success:
- corefile
- hosts

**Comment by sinclairpaul** [comment]
If this were true then nobody would be able to use the addon...

I would suggest that something on your OS is listening on 53

**Comment by nicolasvila** [comment]
Indeed, I disabled my Unbound server (TCP port 53) but there was still something listening on the UDP port 53... I figured out what's going on using that lead:

https://eviltyrant.com/wordpress/2019/07/adding-adguard-to-home-assistant-on-hassio-on-ubuntu-18-04/
I stopped and disabled systemd-resolved and this fixed the problem. ArchLinux and Ubuntu are concerned so far (and maybe all systemd-based Linux flavours)

The issue should be closed but maybe you should add a few words on the README regarding the **systemd-resolved** service

FYI, here is what I obtained when I tried to start Adguard (endless loop)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 2.3.3
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Arch Linux ARM  (armv7 / odroid-xu)
 Home Assistant Core: 0.109.6
 Home Assistant Supervisor: 222
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[15:31:57] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:31:59] INFO: Starting AdGuard Home server...
2020/05/12 15:31:59 [info] AdGuard Home, version v0.101.0, channel release
, arch linux arm v6%!(EXTRA string=6)
2020/05/12 15:31:59 [info] Upstream 0: https://dns10.quad9.net:443/dns-query
2020/05/12 15:31:59 [info] Go to http://127.0.0.1:45158
[15:31:59] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2020/05/12 15:32:00 [info] Starting the DNS proxy server
2020/05/12 15:32:00 [info] Ratelimit is enabled and set to 20 rps
2020/05/12 15:32:00 [info] The server is configured to refuse ANY requests
2020/05/12 15:32:00 [info] DNS cache is enabled
2020/05/12 15:32:00 [info] Creating the UDP server socket
**2020/05/12 15:32:00 [fatal] Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: address already in use**
[15:32:01] INFO: Starting AdGuard Home server...
[...]
```

**Comment by sinclairpaul** [comment]
Choosing to run a supervised install means being responsible for the OS.  We couldn't possibly cover all variants.
