### ISSUE TITLE
Upgrade to `5.2.1` breaks Web UI page

### ISSUE THREAD

**Issue by dkorunic** [hassio-addons/addon-adguard-home#564]
# Problem/Motivation

Upgrade to `5.2.1` breaks Web UI page and displays HTTP request errors in the right bottom corner:

```
Error: control/clients/find?ip0=192.168.1.74&ip1=192.168.1.11&ip2=192.168.1.105&ip3=192.168.1.101&ip4=192.168.1.107&ip5=192.168.1.68&ip6=192.168.1.146&ip7=192.168.1.18&ip8=192.168.1.13&ip9=192.168.1.51&ip10=192.168.1.66&ip11=192.168.1.94&ip12=192.168.1.63&ip13=192.168.1.4&ip14=192.168.1.24&ip15=192.168.1.10&ip16=192.168.1.29&ip17=192.168.1.23&ip18=192.168.1.22&ip19=192.168.1.67&ip20=192.168.1.60&ip21=192.168.1.62&ip22=192.168.1.61&ip23=192.168.1.69&ip24=192.168.1.143&ip25=192.168.1.65&ip26=192.168.1.28 | Network Error
```

Other signs of breakage are that all counters on Web UI stay empty, while DNS server really works.

## Expected behavior

Web UI to work after the upgrade.

## Actual behavior

Web UI is broken, all counters are at zero, all graphs remain at zero. Opening main Web UI page shows the red network error in the right bottom corner.

![Screenshot 2024-12-12 at 13 49 01](https://github.com/user-attachments/assets/0bddd947-4292-4289-87b2-965220d3b4ea)
![Screenshot 2024-12-12 at 13 49 08](https://github.com/user-attachments/assets/e6ba6ecd-9178-460d-87e9-c2b622b7d988)

## Steps to reproduce

Upgrade to `5.2.1`. Revert to `5.2.0` resolves the issue.

**Comment by mislav** [comment]
Update: completely disabling uBlock Origin Lite did fix the issue. Previously, I had tried to use uBlock Origin Lite's own settings to avoid blocking anything on the domain where I host Home Assistant, but for some reason that did not work. My AdGuard Home web UI works again after disabling the browser extension completely.

**Comment by dkorunic** [comment]
I can confirm on my end that uBlock Origin Lite is indeed the culprit here and whitelisting `homeassistant.local` is enough to get things going. Closing the ticket.
