### ISSUE TITLE
adguard.disable_url not working as intended

### ISSUE THREAD

**Issue by jamesgreeley** [hassio-addons/addon-adguard-home#57]
# Problem/Motivation

I am trying to automate the enabling/disabling of certain blocklists. Currently the adguard.disable_url service is not functioning as expected.

## Expected behavior

Calling adguard.disable_url should disable the url. Leaving the name and URL intact

`    - service: adguard.disable_url
      data:
        url: https://example.example/filter.txt`

## Actual behavior

The item is left in a ghost state. With no name, URL. Any attempt to delete/edit this entry is met with an error. You also cannot use adguard.enable_url to recover the entry.

![image](https://user-images.githubusercontent.com/3008387/81790440-b0b13500-9505-11ea-8af1-416f27e0127f.png)

## Steps to reproduce

Using the latest version 2.3.3
Add your own blocklist (have not verified on the default lists)
Attempt to disable a block list using adguard.disable_url

## Proposed changes

Have the adguard.disable_url just disable the blocklist, in the same manner, click the 'Enabled' checkbox in the GUI would.

**Comment by frenck** [comment]
The issues reported is about using the Home Assistant integration, not the add-on or adguard itself. Please report it @ Home Assistant.

Thanks 👍
