### ISSUE TITLE
Update Adguard Home to latest v0.102.0

### ISSUE THREAD

**Issue by thavini** [hassio-addons/addon-adguard-home#59]
# Problem/Motivation

> Found out on tweakers.net that there is an update available for Adguard home

## Expected behavior

> Behavior is good already.

## Actual behavior

> Official update was released

## Steps to reproduce

> Check the Adguard website or GitHub repo 😉https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.102.0

## Proposed changes

> Update the system

## Additional questions
> Is it possible to add extra environment settings for more configuration in Adguard Home?

<blockquote><img src="https://avatars1.githubusercontent.com/u/8361145?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AdguardTeam/AdGuardHome">AdguardTeam/AdGuardHome</a></strong></div><div>Network-wide ads & trackers blocking DNS server. Contribute to AdguardTeam/AdGuardHome development by creating an account on GitHub.</div></blockquote>

**Comment by pattyland** [comment]
At the least the PR was already merged: https://github.com/hassio-addons/addon-adguard-home/pull/58

**Comment by frenck** [comment]
This is not an issue. Updated will follow soon.
