### ISSUE TITLE
Reply from a different IP address.

### ISSUE THREAD

**Issue by bakkerl** [hassio-addons/addon-adguard-home#60]
# Problem/Motivation
When Hassio has multiple IP addresses, AdGuard Home give a response from a different IP than the incoming IP address

## Expected behavior
Reply from the right IP address

## Actual behavior
Reply from a different IP.
`[bakkerl@moros ~]$ nslookup google.com 192.168.75.9`
`;; reply from unexpected source: 192.168.75.17#53, expected 192.168.75.9#53`
`;; reply from unexpected source: 192.168.75.17#53, expected 192.168.75.9#53`
`;; reply from unexpected source: 192.168.75.17#53, expected 192.168.75.9#53`
`;; connection timed out; no servers could be reached`

## Steps to reproduce
- Default installation of Hassio (On Raspbarry)
- Add IP address on the same network. 
- Install AdGuard Home addon
- Do DNS request to the added IP address.

Configure devices in the addon says:
`Configure your devices`
`To start using AdGuard Home, you need to configure your devices to use it.`
`AdGuard Home DNS server is listening on the following addresses:`
`127.0.0.1`
`192.168.75.17`
`192.168.78.18`
`192.168.75.18`
`192.168.75.9`
`172.30.32.1`
`172.17.0.1`

**Comment by frenck** [comment]
Home Assistant does not support handling multiple IP addresses.

**Comment by bakkerl** [comment]
Your previous PiHole addon did handle all very well. Why the change in here?

**Comment by frenck** [comment]
There is no change here. This is a different piece of software.
