### ISSUE TITLE
DNS resolution on Hassio broken after Adguard installation

### ISSUE THREAD

**Issue by jbakar** [hassio-addons/addon-adguard-home#63]
# Problem/Motivation

> DNS resolution on Hassio broken after Adguard installation. 

## Expected behavior

> DNS resolution should be faster after the installation

## Actual behavior

> DNS resolution become slower and it just stop working after a while. The MET weather information will stop working, installation via Supervisor and Integrations also stopped working. Pointing out to DNS issue

## Steps to reproduce

- Fresh install of Hassio on RPI2 supervised mode. 
- Install Adguard add-ons and point router DNS to Adguard. At the beginning DNS resolution works but after 2 hours you will start getting network problem. 
- I have even added Google DNS(8.8.8.8 and 8.8.4.4) into the upstream DNS. That can resolve the resolution of other devices when querying to Hassio, but not DNS resolution on the Hassio itself. 
- The attempt to get version info from Reload in Supervisor > System failed
- I cant install anything from Integrations
- Have rebooted twice 
- Even after removing the Adguard and reboot the host, DNS is still problematic
- I have rerun this same process like 3 times, the past 2 days to confirm there's some issue with Adguard and decided to dump Adguard altogether

## Proposed changes

> N/A

**Comment by frenck** [comment]
Sounds like you have disabled systemd-resolved on your host system?
Or you have missed the first step of the installation guide.
