### ISSUE TITLE
dns over tls & https

### ISSUE THREAD

**Issue by stvnmbr1** [hassio-addons/addon-adguard-home#64]
is there a way to change the available ports to forward in the addon?
HTTPS 443 and 853 should be configurable.

I enabled dns over tls which causes the admin page to switch to the https port and actually has shut me out.

**Comment by sinclairpaul** [comment]
I think its likely you selected this:

![image](https://user-images.githubusercontent.com/24625998/83206696-5e842c80-a11f-11ea-9e04-220dc47eda35.png)

Unfortunately that's a challenge (which we should probably look at), not knowing your OS/setup it would be difficult to help.

Only suggestion would be to uninstall and reinstall.

**Comment by stvnmbr1** [comment]
haha yes i did indeed ..
thought this meant it redirects http requests from clients to https to internet nd such like the safesearch. so kinda screwed now unless i can edit the config manually from inside the container? this way i don't need to setup my filters nd such again.

i'm talking about the config tab / network in supervisor config addon where you can expose your ports from the container.
I would expose 443 and 853 to other not common use ports for outside access.

i just tried duplicating with exposed ports in portainer but doesn't want me to do it :(

any help on this would be greatly appreciated !

**Comment by sinclairpaul** [comment]
Edit /usr/share/hassio/addons/data/a0d7b954_adguard/adguard/AdGuardHome.yaml and set force_https key to false.

**Comment by stvnmbr1** [comment]
ok that got me back in the admin console ;) 
Thanks !

is there a way to add 443 and 853 to the exposed ports or are the exposed by default as the container uses host network in docker? don't know how the supervisor addons are setup, so kinda new to me

**Comment by sinclairpaul** [comment]
Will look at how we deal with SSL, as there is nginx in the way, which will do the SSL for you.  What's likely is that we just force remove the option, and leave the SSL down to ingress or the addon config.

It's likely we need to add 853 to the config as well.  Are we good to close this for now?

**Comment by stvnmbr1** [comment]
i don't mind the admin console not running https, as this won't be exposed and uses ingress in hassio.
Only access to the addon i need is through hassio.

dns over tls would be great as it only needs an extra port exposed in the config and is blocking me from going further.
 
I don't know if I can add this myself somewhere in the code or if this is a quick fix thing to add an extra port? 
didn't see anything port-ish in dockerfile and duplicating the container wouldn't let me expose the ports

**Comment by sinclairpaul** [comment]
Fixed via #67
