### ISSUE TITLE
Can't use AdGuard Home configurations

### ISSUE THREAD

**Issue by guice** [hassio-addons/addon-adguard-home#68]
# Problem/Motivation

AdGuard Home addon, by default, binds to all addresses on the system. If you're multi-homed, it's going to bind to *every single* address, `[::]:53`. When using vlans, this starts causing oddities in DNS responses.

**From a 192.168.1.x host to 192.168.2.10 AdGuard Home** 
```
➜  ~ nslookup google.com 192.168.2.10    
;; reply from unexpected source: 192.168.1.10#53, expected 192.168.2.10#53
```

**From a 192.168.2.x host to 192.168.1.10 AdGuard Home** 
```
~ $ nslookup google.com 192.168.1.10
;; reply from unexpected source: 192.168.2.10#53, expected 192.168.1.10#53
```

I want the ability to pass [AdGuard Home configurations](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) to the docker container so I can use `dns.bind_host` and control what interface(s) for AdGuard Home to listen on.

## Expected behavior

When I add `dns.bind_host` to the configuration, I expect AdGuard home to bind to only that host:

**Add On Config**
```
ssl: true
certfile: me.com.cert
keyfile: me.com.key
dns:
  bind_host: 192.168.1.10
```

## Actual behavior

AdGuard Home still continues to bind on all hosts:
```
2020/05/29 18:44:54 [info] Creating the UDP server socket
2020/05/29 18:44:54 [info] Listening to udp://[::]:53
2020/05/29 18:44:54 [info] Creating the TCP server socket
2020/05/29 18:44:54 [info] Listening to tcp://[::]:53
2020/05/29 18:44:54 [info] Entering the UDP listener loop on [::]:53
2020/05/29 18:44:54 [info] Entering the tcp listener loop on [::]:53
```

## Steps to reproduce

Requires you to run AdGuard Home as the addon on a multi-homed (I'm using VLAN'd) host.

## Proposed changes

Bindly pass-through the configuration as yaml to AdGuard Home on start: `./AdGuardHome -c configuration.yaml` 

In theory AdGuard Home should ignore any YAML values it doesn't understand.

**Comment by frenck** [comment]
Home Assistant doesn't support multiple interfaces. If you are in need for that, you need to look into Home Assistant Container or Home Assistant Core, as those allow you to set up those custom configurations in any way you like.

**Comment by guice** [comment]
> Home Assistant doesn't support multiple interfaces.

? I don't know how that's related to this issue. It's HA that's allowing the add-on to connect to multiple interfaces. I'm actually trying to do the opposite: **stop** AdGuard Home Addon from binding to all interfaces.

> as those allow you to set up those custom configurations in any way you like.

@frenck, Where in HA Core can I do this?

I'm running HA Container/Core, using the new AdGuard Home addon. I cannot pass-through configurations from HA -> Supervisor -> AdGuard Home -> Configuration into AdGuard Home.

<img width="1107" alt="Screen Shot 2020-05-30 at 7 43 14 AM" src="https://user-images.githubusercontent.com/205378/83329933-5b855b00-a249-11ea-90c0-e4be752cebaa.png">

My HA is running on an NUC, in an containerized environment. Aren't I running HA Core? 
```
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
bdc92d6c23cb        hassioaddons/adguard-amd64:2.3.3                    "/init"                  13 hours ago        Up 13 hours                                                                              addon_a0d7b954_adguard
70988b4016e4        hassioaddons/node-red-amd64:6.2.0                   "/init"                  14 hours ago        Up 14 hours                                                                              addon_a0d7b954_nodered
f9ee573e7d76        hassioaddons/appdaemon-amd64:0.2.5                  "/init"                  14 hours ago        Up 14 hours         0.0.0.0:5050->5050/tcp                                               addon_a0d7b954_appdaemon
9d37cf1256b8        sabeechen/hassio-google-drive-backup-amd64:0.98.3   "python3 -m backup"      14 hours ago        Up 14 hours         0.0.0.0:1627->1627/tcp, 8099/tcp                                     addon_cebe7a76_hassio_google_drive_backup
f6b5194a2d38        homeassistant/amd64-addon-samba:9.0                 "/run.sh"                14 hours ago        Up 14 hours                                                                              addon_core_samba
c892fb85f369        apipa169/amd64-hassio-assistant_relay:0.7.4         "docker-entrypoint.s…"   14 hours ago        Up 14 hours         0.0.0.0:3000->3000/tcp                                               addon_6a3d001f_assistant_relay
7eddcb625a9b        homeassistant/amd64-addon-mosquitto:5.1             "/run.sh"                14 hours ago        Up 14 hours         0.0.0.0:1883-1884->1883-1884/tcp, 0.0.0.0:8883-8884->8883-8884/tcp   addon_core_mosquitto
6bebcb60e193        homeassistant/amd64-hassio-cli:25                   "/init /bin/bash -c …"   14 hours ago        Up 14 hours                                                                              hassio_cli
6f66a61615ec        homeassistant/amd64-hassio-audio:14                 "/init"                  14 hours ago        Up 14 hours                                                                              hassio_audio
34139c324b6c        homeassistant/amd64-hassio-dns:9                    "/init coredns -conf…"   14 hours ago        Up 14 hours                                                                              hassio_dns
a56d664a2a80        homeassistant/amd64-hassio-multicast:2              "/init"                  14 hours ago        Up 14 hours                                                                              hassio_multicast
5a4edba298a9        homeassistant/amd64-hassio-supervisor               "/init"                  26 hours ago        Up 14 hours                                                                              hassio_supervisor
d67813fffe74        homeassistant/qemux86-64-homeassistant:0.110.3      "/init"                  3 days ago          Up 14 hours                                                                              homeassistant
```

**Comment by frenck** [comment]
It is related, because Home Assistant Supervised does not support multiple network interfaces. If you are running manual setups like yours (Home Assistant Supervised, aka Hassio on a Generic Linux), these things become your issue. When running the system as it was meant to be, it won't happen.

Home Assistant does not support multiple network interfaces.

**Comment by guice** [comment]
Sure. That does make sense, but it's not actually relevant to the bug itself. That was only a symptom. 

Very well, I'll add another ticket for the actual issue: not passing configurations to AdGuard Home, completely removing the mention of multi-home "bug" - but would be the example, since it can be seen in the logs easily.
