### ISSUE TITLE
Pass HA Configuration into AdGuard Home

### ISSUE THREAD

**Issue by guice** [hassio-addons/addon-adguard-home#69]
# Problem/Motivation

AdGuard Home has a set of [configuration settings](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) of its own. HA does not appear to be sending any add-on configuration settings through to AdGuard Home.

<img width="1107" alt="Screen Shot 2020-05-30 at 7 43 14 AM" src="https://user-images.githubusercontent.com/205378/83338525-893ac600-a282-11ea-94bd-f9bd61b2d737.png">

## Expected behavior

When I attempt to pass in [configuration settings](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration), I expect them to configure AdGuard Home. For example:

```
dns:
  bind_host: 192.168.1.10
```

## Actual behavior

AdGuard Home does not appear to be getting the configuration, it does not bind to a specific host:
```
2020/05/29 18:44:54 [info] Creating the UDP server socket
2020/05/29 18:44:54 [info] Listening to udp://[::]:53
2020/05/29 18:44:54 [info] Creating the TCP server socket
2020/05/29 18:44:54 [info] Listening to tcp://[::]:53
2020/05/29 18:44:54 [info] Entering the UDP listener loop on [::]:53
2020/05/29 18:44:54 [info] Entering the tcp listener loop on [::]:53
```

## Steps to reproduce

Try to add configuration values for AdGuard Home, AdGuard Home should configure itself based on configuration values:

```
dns:
  bind_host: 192.168.1.10
```

## Proposed changes

Bindly pass-through the configuration as yaml to AdGuard Home on start: `./AdGuardHome -c configuration.yaml` 

It's assumed AdGuard Home would ignore any YAML settings it doesn't understand.

**Comment by frenck** [comment]
You can't pass that to AdGuard, it is the add-on configuration, not AdGuard Home itself.

If you need this level of customization, I suggest running AdGuard Home directly.
