### ISSUE TITLE
Latest update breaks if HTTPS port is not configured

### ISSUE THREAD

**Issue by hastarin** [hassio-addons/addon-adguard-home#70]
# Problem/Motivation

> The latest changes need some defensive coding changes.

## Expected behavior

> To be able to update to a new version without worrying about the container refusing to start.

## Actual behavior

> NGinx crashes on startup and takes the container down with it.
> [11:39:22] INFO: Starting NGinx...
> nginx: [emerg] invalid port in upstream "127.0.0.1:0" in /etc/nginx/includes/upstream.conf:2

> See https://github.com/hassio-addons/addon-adguard-home/commit/edd538a6e1c90150c99fac9c308c95f557fc95e1#r39556479

## Steps to reproduce

> Enable Encryption and clear the HTTPS port.  Restart the addon.

## Proposed changes

> Check if the port in the configuration is 0 and if so don't update upstream.conf?

**Comment by frenck** [comment]
> To be able to update to a new version without worrying about the container refusing to start.

I've been able to do that on multiple systems... 

Nevertheless, added additional checks in 795c827

Thanks for reporting 👍

**Comment by almostserious** [comment]
That just happend to me when updating to  2.4.0
