### ISSUE TITLE
Not starting anymore

### ISSUE THREAD

**Issue by Razer0123** [hassio-addons/addon-adguard-home#71]
# Problem/Motivation

Not starting anymore after 2.4.1 update

## Expected behavior

It starts

## Actual behavior

Does not start, no log in supervisor

## Steps to reproduce

Just start it

## Proposed changes

Not sure, something must be broken

**Comment by reinder83** [comment]
Same here, not starting after update, also I don't see logs in supervisor

**Comment by almostserious** [comment]
Its the same Issue as #70 
Apparently if your AdGuardHome.yaml is set to use TLS but has the https port set to 0 the issue starts.

I was able to copy the AdGuardHome.yaml from my container to my host, edit the yaml to:
```
tls:
  enabled: false
```
and copy it back to the container. AdGuard is starting backup fine :)

The file is in the following folder /data/adguard/AdGuardHome.yaml

**Comment by sinclairpaul** [comment]
It's really not the same issue as it has been resolved.

There are two logs to check, the Addon/Log tab and also Supervisor/System/System Log.

There will be an issue in one of them

**Comment by Razer0123** [comment]
This is the error

`20-05-31 11:15:58 ERROR (SyncWorker_17) [supervisor.docker] Can't create container from addon_a0d7b954_adguard: 404 Client Error: Not Found ("No such image: hassioaddons/adguard-armv7:2.4.1")`

**Comment by frenck** [comment]
@Razer0123 That means the download failed, probably not enough diskspace to complete the upgrade operation.

**Comment by Razer0123** [comment]
> @Razer0123 That means the download failed, probably not enough diskspace to complete the upgrade operation.

I have over 24gb available

**Comment by frenck** [comment]
Hmm, interesting, @Razer0123 Have you followed step 1 of the AdGuard installation guide? Does your box have a statically configured IP (not DHCP reservation in your router) and external DNS servers?

**Comment by Razer0123** [comment]
I have now, but not sure it changes anything
Any way i could download the file manually?

**Comment by frenck** [comment]
You could try using `ha supervisor repair` from one of the add-on terminals. Please note, if you have customizations (custom Docker container), those would be erased.

**Comment by Razer0123** [comment]
I have uninstalled and reinstalled the addon, works now
Not sure if it was a bad install or a config issue

**Comment by frenck** [comment]
You can partially import a snapshot to restore.

**Comment by Razer0123** [comment]
> You can partially import a snapshot to restore.

Importing the broken backup to this new install would just broke Adguard again. I need to move config files into the addon folder, not sure which though

**Comment by JoelS04** [comment]
I had the same issue - Addon not starting after update. A reboot fixed this for me.

**Comment by reinder83** [comment]
Fixed it with help from @frenck by setting a static IP address and external DNS server

**Comment by undauntedjogging** [comment]
Same issue here - not starting anymore 

20-05-31 19:33:38 ERROR (SyncWorker_18) [supervisor.docker] Can't create container from addon_a0d7b954_adguard: 404 Client Error: Not Found ("No such image: hassioaddons/adguard-armv7:2.4.1")

**Comment by benyafai** [comment]
> You could try using `ha supervisor repair` from one of the add-on terminals. 

I had the same issue, this fixed it for me.

**Comment by Gaff** [comment]
Quite a few people had this issue, see thread here:
https://community.home-assistant.io/t/adguard-addon-stopped-working-cant-create-container-no-such-image/200790/9

@frenck  - I'm wondering if it could be a bootstrapping issue. I require adguard to resolve the dockeregistry in order to pull the new image. So if the order of events is:

1. shutdown adguard
2. pull new docker image
3. restart adguard

Then we will have an issue in step 2 because of no DNS?


If there's a simple check I can do to test I'd be willing to help?

**Comment by frenck** [comment]
@Gaff I can't fix people not reading. It is clearly defined as the first step. All reports until now have come down to skipping that first step.

**Comment by Gaff** [comment]
Ok Fair enough - I accept that I, too, didn't read it properly.

Still - would be good if there was some sort of warning / check. There's a few things I can think of:
* Have the container error (or refuse to start?) if it detects that it is it's own DNS server.
* Download the new image before shutting down the old one.
* If an image doesn't start up (or pull) then fall back.
* Attempt to pull the image on every startup [for some reasson HASS didn't attempt to re-pull] even after I rerouted my DNS.

Appreciate most of these are upstream issues. Do any of them have any merit do you think?

**Comment by frenck** [comment]
> Have the container error (or refuse to start?) if it detects that it is it's own DNS server.

We can't. Or else I would have build that.

> Download the new image before shutting down the old one.

That is not fixable for an add-on.

> If an image doesn't start up (or pull) then fall back.

Again not fixable for an add-on.

> Attempt to pull the image on every startup [for some reasson HASS didn't attempt to re-pull] even after I rerouted my DNS.

Outside of add-on scope.


> Do any of them have any merit do you think?

🤷

**Comment by Gaff** [comment]
Sure. I did say they were upstream / home-assistant issues.


You could ping a randomly generated name, then check the logs to see if it's present?

I accept this is pretty convoluted... but it's techinically doable! 😛

**Comment by frenck** [comment]
No, we can't. You now assume logging is enabled.

**Comment by dominik-doll** [comment]
Hi,

after the issue with Adguard I uninstalled it but I am not able to reinstall it. also no update of either core, supervisor or any other add-on could be performed. I always get 500 internal server errors about refused connections. resolving hosts doesn't work anymore. 
@frenck: how can Hassio on docker on NUC/Ubuntu be brought back to normal dns config "pre-adguard"?

`20-06-03 23:07:07 ERROR (SyncWorker_18) [supervisor.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:226 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35943->[::1]:53: read: connection refused").
20-06-03 23:07:07 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!`

`20-06-03 23:07:09 ERROR (SyncWorker_10) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.110.4 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:37962->[::1]:53: read: connection refused").
20-06-03 23:07:09 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails`

![image](https://user-images.githubusercontent.com/35460627/83698384-96004680-a601-11ea-8c1c-7bd9384a7026.png)


Best
  Dominik

**Comment by frenck** [comment]
"Hassio on docker" does not exist and has never existed. I guess you mean you are running a Supervised installation.

Your host system has DNS issues. Probably related to changes you've made to your host system in order to be able to run AdGuard.

Please note, that the host system is your responsibility and not supported.

**Comment by dmstr82U2** [comment]
> You could try using `ha supervisor repair` from one of the add-on terminals. Please note, if you have customizations (custom Docker container), those would be erased.

This worked for me.

**Comment by Simperdy** [comment]
> You could try using `ha supervisor repair` from one of the add-on terminals. Please note, if you have customizations (custom Docker container), those would be erased.

This worked for me. 

Running hassio as vm on Synology NAS.
Synology NAS has a static ip and dns servers, hassio vm has a dhcp reservation.

**Comment by frenck** [comment]
@Simperdy The VM should NOT have a DHCP reservation when using AdGuard, but instead must be statically configured. You will run into the same issue again if you don't do this.

**Comment by gordonthree** [comment]
> I have uninstalled and reinstalled the addon, works now
> Not sure if it was a bad install or a config issue

Uninstall and reinstall worked for me too.

**Comment by frenck** [comment]
Fully solved with the latest version of the add-on.

⬆️ AdGuard Home v2.6.0

https://github.com/hassio-addons/addon-adguard-home/releases/tag/v2.6.0
