### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by lyonrt** [hassio-addons/addon-adguard-home#72]
# Problem/Motivation
Cant install adguard from home assistant.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
20-06-11 19:00:22 INFO (SyncWorker_18) [supervisor.docker.interface] Pull image hassioaddons/adguard-armv7 tag 2.4.1.
20-06-11 19:00:37 ERROR (SyncWorker_18) [supervisor.docker.interface] Can't install hassioaddons/adguard-armv7:2.4.1 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)").
> (What actually happened)

## Steps to reproduce
When I click on install.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote></blockquote>

**Comment by frenck** [comment]
That is not an add-on problem. Looks like you are having network issues.
