### ISSUE TITLE
Can't enable DHCP

### ISSUE THREAD

**Issue by ndarilek** [hassio-addons/addon-adguard-home#73]
# Problem/Motivation

I can't configure AGH's internal DHCP server.

## Expected behavior

DHCP is configured and works.

## Actual behavior

I have HassOS configured with a static IP, 192.168.0.2, assigned directly to the interface. I see 3 interfaces in my dropdown: eth0/192.168.0.2, docker0/172.17.0.1, hassio/172.30.32.1. No matter which I select, I get the following message:

```
In order to use DHCP server a static IP address must be set. We failed to determine if this network interface is configured using static IP address. Please set a static IP address manually.
```

I don't understand where else AGH expects the interface to be manually configured. Further, selecting eth0 in the configuration dropdown displays:

```
    MTU: 1500
    Hardware address: b8:27:eb:79:dc:60
    IP addresses: 192.168.0.2
```

so it does seem to see an address. Further, clicking the error details link displays:

```
open /etc/dhcpcd.conf: no such file or directory
```

which is true, the file doesn't exist. Odd that these appear to be two different errors--one network, one file-related, and that the file-related error is displayed as a failure to determine the static IP.

## Steps to reproduce

1. From the DHCP settings screen, select the router-facing network interface with a statically-configured IP--eth0, in my case.
2. Set gateway to 192.168.0.1.
3. Set netmask to 192.168.255.255.
4. Set start to 192.168.0.100.
5. Set end to 192.168.0.254.
6. Click Save.

**Comment by sinclairpaul** [comment]
Is the button available?
![image](https://user-images.githubusercontent.com/24625998/84770979-9c4dd580-afa6-11ea-91c0-d1717adc02aa.png)

From what I see it's a warning not a terminating error.

**Comment by ndarilek** [comment]
The Enable button is not available. The Save button is.

**Comment by sinclairpaul** [comment]
Click Save, Click Enable.

If the details you posted initially is correct, your Subnet Mask is incorrect (as it most likely should be 255.255.255.0).

The method used to detect won't work in a container, however it does not stop you from continuing, so I would suggest you have a different issue, which would be shown in the addon logs.

**Comment by ndarilek** [comment]
Aw, crap, you're right. Was the netmask. I was thinking broadcast. Shouldn't set this stuff up before coffee.

Works now. Thanks.
