### ISSUE TITLE
Integrate with ZeroTier addon

### ISSUE THREAD

**Issue by That-Dude** [hassio-addons/addon-adguard-home#74]
Motivation: Make the ZeroTier addon use the Adguard addon

I've set both addons up and directed my iPhone to use the HomeAssistant server as a DNS address and default route.

However, adverts are not being blocked and nothing in the Adguard query logs justs the remote client is using Adguard to resolve addresses.

Is there a way to make the Adguard addon listen on the ZeroTier IP address?

**Comment by frenck** [comment]
The zerotier add-on current does not allow routing. For these kind of setups the HassOS or Supervised installation methods are not advised. Consider a installation of Home Assistant Container or Core instead.
