### ISSUE TITLE
Stopped resolving unblocked domains after 2 days

### ISSUE THREAD

**Issue by abooysen** [hassio-addons/addon-adguard-home#76]
Hi

The plugin worked great for two days then it stopped resolving domains that are not blocked, The requests for these domains does not even show in the Query Log, it only shows the blocked requests.
No errors in HomeAssistant's log file
I switched of Protection but that also did not resolve the issue
The only way to get my internet working again was to not use Adguard as the DNS anymore.
(I did not try rebooting homeAssitant, perhaps I should have)
Using the default "https://dns10.quad9.net/dns-query" configuration

Let me know if there's any other information you will require

Kind Regards
Andre

 

<blockquote></blockquote>

**Comment by benjivm** [comment]
I have had issues with the quad9 DNS servers in the past: loss of internet connectivity for a few hours, etc. Switching and/or adding other DNS servers to the upstream list may resolve your issue as it did mine, though they may be unrelated.

**Comment by frenck** [comment]
There is not much I can do with the current description and provided information.
Using different upstream, check all the logs. There more must be some kind of hint somewhere.

**Comment by RichLewis007** [comment]
You should definitely try rebooting HomeAssistant @abooysen ..

**Comment by RichLewis007** [comment]
I suggest this old, vague issue be closed.
