### ISSUE TITLE
Letsencrypt SSL certs not available to AdGuard.

### ISSUE THREAD

**Issue by cromulus** [hassio-addons/addon-adguard-home#77]
# Problem/Motivation

Attempting to use letsencrypt generated ssl certificates in AdGuard for encryption/dns-over-tls

## Expected behavior

I expected the `ssl/` directory to be available on the AdGuard host.

## Actual behavior

When I add the path to my live letsencrypt certs, the interface tells me that they are not available.

## Steps to reproduce

See above.

## Proposed changes
Mount the /ssl/ directory in the AdGuard docker so that it's contents are available to the AdGuard process.

It appears that the config.json maps the ssl directory, but it doesn't appear to be available.
Thanks!

**Comment by sinclairpaul** [comment]
It already is mounted, what are you using for the path?

**Comment by cromulus** [comment]
I'm currently in the docker image, and I can't see it mounted.

**Comment by cromulus** [comment]
I'll try restarting the add-on.

**Comment by cromulus** [comment]
Oops, found it. Thanks!
