### ISSUE TITLE
Call to AdGuard API "disable_url" removes URL and name instead of disabling it.

### ISSUE THREAD

**Issue by mostlychris** [hassio-addons/addon-adguard-home#79]
# Problem/Motivation

When I use the AdGuard API call "disable url", it is deleting the URL information (name, url) and leaving a blank line in AdGuard Block Lists. 

## Expected behavior

When calling "disable_url" it should uncheck the box and disable the url in the block list settings.

## Actual behavior

The name and URL are removed from the block list, leaving a blank line. This prevents re-enabling the same URL again using the "enable_url" call since the URL has been blanked out.

## Steps to reproduce

Add a new URL and name using the "add_url" API call.
Disable the URL using the "disable_url" API call.
Try re-enabling the URL using the "enable-url" API call.

**Comment by frenck** [comment]
The API is provided by AdGuard itself, not the add-on.
Please report direct use of the API and issues with it, with the AdGuard Home team.
