### ISSUE TITLE
Make text "This add-on is not available on your system” more informative

### ISSUE THREAD

**Issue by Andrew49** [hassio-addons/addon-adguard-home#80]
# Problem/Motivation
If the user is running an earlier version of HA, the text "This add-on is not available on your system” is shown in red below the badges on the addon page. It needs to be more informative - apparently this happens when the installed version is earlier than the required version for the addon. This needs to be explained.
> (Why the issue was filed)
To improve a fairly meaningless message!
## Expected behavior
Show the reason WHY the addon isn't available, and what I need to do to fix it!
> (What you expected to happen)

## Actual behavior
As bove
> (What actually happened)

## Steps to reproduce
Go into the addon page when installed version is before 113.x
> (How can someone else make/see it happen)

## Proposed changes
See above, make the message informative.
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not a thing an add-on controls. Sorry m8.
