### ISSUE TITLE
AdGuard appears to be automatically disabling itself

### ISSUE THREAD

**Issue by benjivm** [hassio-addons/addon-adguard-home#82]
# Problem/Motivation

Repeated occurences of the issue (about 3 times in the past 4 months).

## Expected behavior

AdGuard should never turn itself off; whether from a crash or post-update, it should recover its last state.

## Actual behavior

AdGuard turns itself off automatically in two areas.

1) Header badge should be **ON** and the toggle should read **Disable protection**:
![](https://i.imgur.com/rlHotRv.png)

2) The option **Block domains using filters and hosts file** should be checked.
![](https://i.imgur.com/CP8k6do.png)

## Steps to reproduce

Unfortunately I have not been able to consistently reproduce this issue.

## Proposed changes

Ensure there is a way for AdGuard to maintain and recover its state, even from crashes.

**Comment by frenck** [comment]
It doesn't.

All similar reports we have got and researched where caused by Home Assistant automations (usually as a side effect of targeting area's, groups or using incorrect services to turn on/off things).

**Comment by benjivm** [comment]
Hi Frenck, can you link to some of these resolved cases?

I don't have many automations, and as far as I can tell they are configured and working correctly.

**Comment by frenck** [comment]
That is out of scope for the addon and am not planning on chasing another ghost again.


Remove the integration from Home Assistant and see if it solves the issue.

**Comment by benjivm** [comment]
I don't understand, I am using the AdGuard addon, how would removing it resolve the issue?

**Comment by frenck** [comment]
I didn't say: remove the add-on. I said integrations. Add-ons and integrations are not the same thing.

**Comment by benjivm** [comment]
Ah I see, thanks. And as I mentioned before all AdGuard entities are already disabled, is this not functionally the same? I have deleted the integration now regardless.
