### ISSUE TITLE
No add-on updates on raspberrypi3

### ISSUE THREAD

**Issue by regystro** [hassio-addons/addon-adguard-home#84]
# Problem/Motivation

Hi. Similar to [this](https://github.com/hassio-addons/addon-adguard-home/issues/78) issue, in my case AdGuard Home version remains 0.101.0 in add-on version 2.3.3.

I thought that 2.5.1 release would fix my system too, but that's not the case, since I'm stuck at version 2.3.3.

## Expected behavior

2.5.1 add-on update available for my system

## Actual behavior

Only 2.3.3 version appears to be available

## Steps to reproduce

I tried uninstalling add-on, rebooting and reinstalling, but the only available version is 2.3.3.

That's the relevant log:
```
 Add-on version: 2.3.3
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 0.115.3
 Home Assistant Supervisor: 245
...
INFO: Starting AdGuard Home server...
[info] AdGuard Home, version v0.101.0, channel release, arch linux arm v6%!(EXTRA string=6)
```

It seems it should be downloading armv7 release but is getting armv6 instead.

Thank you.

**Comment by frenck** [comment]
If you reload the add-on store, what does the supervisor log say at that point?

**Comment by regystro** [comment]
Indeed throws [this same error](https://github.com/hassio-addons/repository/issues/178), and now I see I'm not receiving updates from Home Assistant Community Add-ons repo.

Filesystem corruption as suggested. I just applied your fix in that answer and all is working properly.

Thanks a lot!! ...and sorry to bother / alarm.
