### ISSUE TITLE
Nginx Proxy Manager entry to expose Adguard Home UI

### ISSUE THREAD

**Issue by saikarthikp9** [hassio-addons/addon-adguard-home#85]
# Problem/Motivation

How to expose Adguard Home UI using Nginx Proxy Manager? Not sure what the destination address/IP and port should be set to. 

## Expected behavior

Custom Domain URL to open Adguard Home UI

## Actual behavior

All tests do not open the Adguard Home UI. I have however successfully setup Nginx Proxy Manager to route to other services.

**Comment by frenck** [comment]
I don't know either, depends on where you Adguard Home is running.

In case you are running the AdGuard Home add-on, it is not exposed. That add-on uses Ingress and thus the interface is exposed through Home Assistant itself.
