### ISSUE TITLE
lb._dns-sd._udp.0.1.168.192.in-addr.arpa

### ISSUE THREAD

**Issue by Zendio** [hassio-addons/addon-adguard-home#86]
# Problem/Motivation
Since the last update I'm seeing a lot of requests (from my Apple devices) to lb._dns-sd._udp.0.1.168.192.in-addr.arpa and a few similar addresses. Googling "lb._dns-sd._udp.0.1.168.192.in-addr.arpa" brings up posts from PiHole saying I shouldn't be seeing this.

> (Why the issue was filed)

Shouldn't appear

> (What you expected to happen)

## Actual behavior

Over 1000 hits on every lb.dns-sd address evert 24 hours

## Steps to reproduce

Upstream DNS set to 192.168.1.1 (router DNS)
Parallel Requests
No Encryption
No changed client settings
Not using the DHCP from Adguard, instead using router
Router DNS on LAN pointing to Pi IP address

**Comment by frenck** [comment]
Sounds like you are experiencing circular traffic.

Nevertheless, from an add-on perspective, there is nothing I can do. Please report your issue with the AdGuard Home team.

Thanks 👍
