### ISSUE TITLE
Static IP documentation doesn't refer to Supervisor UI possibility.

### ISSUE THREAD

**Issue by carras** [hassio-addons/addon-adguard-home#90]
Hi:

Can you use the **supervisor static ip** feature in the IU to do the first step in the documentation configuration process?

If so, I think it could be added to the documentation as an alternative way.

Thanks.

**Comment by frenck** [comment]
Feel free to help out and make a PR instead of an issue. Thanks 👍 

Happy Holidays 🎄

**Comment by carras** [comment]
https://github.com/home-assistant/operating-system/pull/1114
