### ISSUE TITLE
Feature request: Control adguard outside of HA containers

### ISSUE THREAD

**Issue by fribse** [hassio-addons/addon-adguard-home#92]
# Problem/Motivation

Having adguard is great, it removes quite a lot of annoying stuff. But having adguard one home assistant as the only dns server is a problem if you restart the entire host. While it is down, other devices on the network will fail the DNS queries, which could be unfortunate, or even reestablishing a crashed HA would require extra steps with DNS setup.
Currently I have a small RPi 1a (I think) that I have a second ADGuard on, and this will handle DNS queries if the HA host is down.
But I love the feature that I can turn of the filter for testing, and from within HA, so I can make an automation that reactivates it again, or the case where the rest of the household can turn it of, if it somehow disturbs functionality.

I don't know if the ADGuard software supports this kind of remote management?

## Proposed changes

An add on that looks like the full adguard addon, but controls a 'remote' adguard (if it could be inside the existing adguard, so that one could manage both from the same interface would be even better)

**Comment by frenck** [comment]
Your question doesn't make any sense to this add-on project.

If your question is about the Home Assistant integration, it can connect to whatever host you like and does not limit you.

**Comment by fribse** [comment]
If it doesn't make any sense, then maybe I didn't explain myself well enough, or you misunderstood it.
I have the addon, and I love it. I also have a second add guard, and I would like to have the same switches for that.
But the integration does not allow me to add a second one? So it does limit me.
