### ISSUE TITLE
Management of 'remote' adguard

### ISSUE THREAD

**Issue by fribse** [hassio-addons/addon-adguard-home#93]
# Problem/Motivation

Having adguard is great, it removes quite a lot of annoying stuff. But having adguard on home assistant as the only dns server is a problem if you restart the entire host. While it is down, other devices on the network will fail the DNS queries, which could be unfortunate, or even reestablishing a crashed HA would require extra steps with DNS setup.

Currently I have a small RPi 1a (I think) that I have a second ADGuard on, and this will handle DNS queries if the HA host is down.
But I love the feature that I can turn of the filter for testing, and from within HA, so I can make an automation that reactivates it again, or the case where the rest of the household can turn it of, if it somehow disturbs functionality.

I don't know if the ADGuard software supports this kind of remote management?

## Proposed changes

An add on that looks like the full adguard addon, but controls a 'remote' adguard (if it could be inside the existing adguard, so that one could manage both from the same interface would be even better)

**Comment by Golab** [comment]
You can do remote if you open port like on my picture and then go to integration and select AdGuard and put in information and port
![B02DD0FE-F375-4482-BC7E-2C75B94331CF](https://user-images.githubusercontent.com/1252745/104456845-8e4a4c80-55a9-11eb-8035-41c75b1862ae.jpeg)
![80FCAB2A-B93F-453E-8EA2-803B35C09F5B](https://user-images.githubusercontent.com/1252745/104456851-90aca680-55a9-11eb-9a51-925b01ab98aa.jpeg)

**Comment by Golab** [comment]
You can do remote if you open port like on my picture and then go to integration and select AdGuard and put in information and port
![2AEF5E23-1726-4DE6-9B82-A94A30257A28](https://user-images.githubusercontent.com/1252745/104457106-e08b6d80-55a9-11eb-8e79-e7adf1b213fd.jpeg)
![664BC0F6-256F-4CA5-A8B7-420298DAF5D4](https://user-images.githubusercontent.com/1252745/104457114-e2553100-55a9-11eb-82f5-1a43ff826e5d.jpeg)
![264E79FE-D87B-42FC-B44F-46277D037726](https://user-images.githubusercontent.com/1252745/104457120-e3865e00-55a9-11eb-8497-dc514962e376.jpeg)

**Comment by fribse** [comment]
Hi @Golab 
So as I understand your suggestion, you suggest that I have another HA with adguard to be able to remote administration?
Well, as I see it, there are two problems, I have the other adguard on a rpi1 which is a very a basic installation, that can just manage to handle adguard, there is no container or virtualization on that.
Secondly, the integration only allows 1 adguard to be set up in HA.

**Comment by frenck** [comment]
Add-on does not run remotely. If you want a manual remote instance, go ahead, but that is out of scope for our project.
