### ISSUE TITLE
AdGuard only saves 15 minutes of logging

### ISSUE THREAD

**Issue by scorpinus** [hassio-addons/addon-adguard-home#94]
Version of AdGuard Home server: v2.6.1 running as an add-on in Home Assistant. HA is running of an SSD on a Pi4.
Using the default HA installation (burned img to ssd with Balena Etcher).

I'm having issues with the logging of AdGuardHome, the problem is that I have enabled the logging and set it to 90 days retention (through the generic settings in the WebUI), but when I check the 'Query Log' in the WebUI I can always only see the last 15 minutes. Also when I restart the AdGuard add-on I start with an empty log. Why isn't it logging more?

What can I check or do?

**Comment by frenck** [comment]
The add-on log is not related to that logging option in the UI. The logging option in the UI is about the logging of DNS queries.

Add-on logs are a Home Assistant feature, not an AdGuard feature.

**Comment by scorpinus** [comment]
So what you are trying to tell me is that I need to move this issue to AdGuard's issue log instead of the hassio-addons issue log?

**Comment by frenck** [comment]
No, I'm telling you that the configuration option in the UI and `Also when I restart the AdGuard add-on I start with an empty log.` have no relation to each other.

**Comment by scorpinus** [comment]
Ok...thanks...but how does that help me? AdGuard is clearly not saving it's logs properly? Cause where is my 90 days retention? But I guess I have to move this issue to the actuall AdGuard site then? Figured it might have something to do with the add-on integration or something.

**Comment by frenck** [comment]
I think you are mixing up 2 kinds of logs in your logic.

1) The add-on log, which is a couple of hundred lines buffer. Not related to AdGuard itself. (which is the empty add-on log you talked about).

2) The query log in AdGuard. The query log is available for viewing inside AdGuard itself and can be controlled/tuned using the setting you mentioned in the UI.

I've checked, but on 3 of my test systems, I can just go back as long as I've set it to (90 days in my case as well).

**Comment by scorpinus** [comment]
Yeah I guess I am. The problem I am trying to fix is the #2 one. I have set it to 90 days but can only go back 15 minutes in time. And when I restart the add-on I start with an empty query log. I have no clue where to look for the problem tho.

Thanks for replying, i'll see if the AdGuard github can help me further.

**Comment by scorpinus** [comment]
It looks like it was just a graphical glitch? I just updated to the latest v3.0.0 (AdGuard v0.104.3) and now it immediately shows all the logging, just browsed back an hour in time.

Thanks Frenck!

**Comment by frenck** [comment]
Nice! @scorpinus! Thanks for letting me know!
