### ISSUE TITLE
DNS o/HTTPS Not Responding

### ISSUE THREAD

**Issue by Pre10der** [hassio-addons/addon-adguard-home#97]
# Problem/Motivation

> According to the doco, I should be able to leverage DNS o/HTTPS in the Adguard config which I do. DNS o/TLS and DNS oQUIC both work as expected, however DNS o/HTTPS does not. I am using ingress, and not port forwarding any ports in the container other than 53 (Configuration tab in HASS' --> Supervisor menu). I have tried custom ports (in case 443 was in use elsewhere, but to no avail).

## Expected behavior

> I should be able to query DNS o/HTTPS

## Actual behavior

> DNS o/TLS and DNS oQUIC both work as expected, however DNS o/HTTPS does not.

## Steps to reproduce

> Configure Encrypted DNS as per the documentation within Adguard. Attempt to connect to Adguard Home on 443 which subsequently fails.

What am I missing and whats the best approach to troubleshooting this?

**Comment by matt-FFFFFF** [comment]
See #118
